// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/gitprovider/bitbucket"
)

type CurrentUserFetcher struct {
	FetchCurrentUserStub        func(context.Context) string
	fetchCurrentUserMutex       sync.RWMutex
	fetchCurrentUserArgsForCall []struct {
		arg1 context.Context
	}
	fetchCurrentUserReturns struct {
		result1 string
	}
	fetchCurrentUserReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CurrentUserFetcher) FetchCurrentUser(arg1 context.Context) string {
	fake.fetchCurrentUserMutex.Lock()
	ret, specificReturn := fake.fetchCurrentUserReturnsOnCall[len(fake.fetchCurrentUserArgsForCall)]
	fake.fetchCurrentUserArgsForCall = append(fake.fetchCurrentUserArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.FetchCurrentUserStub
	fakeReturns := fake.fetchCurrentUserReturns
	fake.recordInvocation("FetchCurrentUser", []interface{}{arg1})
	fake.fetchCurrentUserMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CurrentUserFetcher) FetchCurrentUserCallCount() int {
	fake.fetchCurrentUserMutex.RLock()
	defer fake.fetchCurrentUserMutex.RUnlock()
	return len(fake.fetchCurrentUserArgsForCall)
}

func (fake *CurrentUserFetcher) FetchCurrentUserCalls(stub func(context.Context) string) {
	fake.fetchCurrentUserMutex.Lock()
	defer fake.fetchCurrentUserMutex.Unlock()
	fake.FetchCurrentUserStub = stub
}

func (fake *CurrentUserFetcher) FetchCurrentUserArgsForCall(i int) context.Context {
	fake.fetchCurrentUserMutex.RLock()
	defer fake.fetchCurrentUserMutex.RUnlock()
	argsForCall := fake.fetchCurrentUserArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CurrentUserFetcher) FetchCurrentUserReturns(result1 string) {
	fake.fetchCurrentUserMutex.Lock()
	defer fake.fetchCurrentUserMutex.Unlock()
	fake.FetchCurrentUserStub = nil
	fake.fetchCurrentUserReturns = struct {
		result1 string
	}{result1}
}

func (fake *CurrentUserFetcher) FetchCurrentUserReturnsOnCall(i int, result1 string) {
	fake.fetchCurrentUserMutex.Lock()
	defer fake.fetchCurrentUserMutex.Unlock()
	fake.FetchCurrentUserStub = nil
	if fake.fetchCurrentUserReturnsOnCall == nil {
		fake.fetchCurrentUserReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.fetchCurrentUserReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *CurrentUserFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CurrentUserFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ bitbucket.CurrentUserFetcher = new(CurrentUserFetcher)
