// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/git"
)

type Brancher struct {
	CreateAndSwitchStub        func(context.Context, string) error
	createAndSwitchMutex       sync.RWMutex
	createAndSwitchArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	createAndSwitchReturns struct {
		result1 error
	}
	createAndSwitchReturnsOnCall map[int]struct {
		result1 error
	}
	CurrentBranchStub        func(context.Context) (string, error)
	currentBranchMutex       sync.RWMutex
	currentBranchArgsForCall []struct {
		arg1 context.Context
	}
	currentBranchReturns struct {
		result1 string
		result2 error
	}
	currentBranchReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	DefaultBranchStub        func(context.Context) (string, error)
	defaultBranchMutex       sync.RWMutex
	defaultBranchArgsForCall []struct {
		arg1 context.Context
	}
	defaultBranchReturns struct {
		result1 string
		result2 error
	}
	defaultBranchReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	FetchStub        func(context.Context) error
	fetchMutex       sync.RWMutex
	fetchArgsForCall []struct {
		arg1 context.Context
	}
	fetchReturns struct {
		result1 error
	}
	fetchReturnsOnCall map[int]struct {
		result1 error
	}
	FetchAndVerifyBranchStub        func(context.Context, string) error
	fetchAndVerifyBranchMutex       sync.RWMutex
	fetchAndVerifyBranchArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	fetchAndVerifyBranchReturns struct {
		result1 error
	}
	fetchAndVerifyBranchReturnsOnCall map[int]struct {
		result1 error
	}
	ForcePushStub        func(context.Context, string) error
	forcePushMutex       sync.RWMutex
	forcePushArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	forcePushReturns struct {
		result1 error
	}
	forcePushReturnsOnCall map[int]struct {
		result1 error
	}
	MergeOriginDefaultStub        func(context.Context) error
	mergeOriginDefaultMutex       sync.RWMutex
	mergeOriginDefaultArgsForCall []struct {
		arg1 context.Context
	}
	mergeOriginDefaultReturns struct {
		result1 error
	}
	mergeOriginDefaultReturnsOnCall map[int]struct {
		result1 error
	}
	PullStub        func(context.Context) error
	pullMutex       sync.RWMutex
	pullArgsForCall []struct {
		arg1 context.Context
	}
	pullReturns struct {
		result1 error
	}
	pullReturnsOnCall map[int]struct {
		result1 error
	}
	PushStub        func(context.Context, string) error
	pushMutex       sync.RWMutex
	pushArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	pushReturns struct {
		result1 error
	}
	pushReturnsOnCall map[int]struct {
		result1 error
	}
	SwitchStub        func(context.Context, string) error
	switchMutex       sync.RWMutex
	switchArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	switchReturns struct {
		result1 error
	}
	switchReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Brancher) CreateAndSwitch(arg1 context.Context, arg2 string) error {
	fake.createAndSwitchMutex.Lock()
	ret, specificReturn := fake.createAndSwitchReturnsOnCall[len(fake.createAndSwitchArgsForCall)]
	fake.createAndSwitchArgsForCall = append(fake.createAndSwitchArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CreateAndSwitchStub
	fakeReturns := fake.createAndSwitchReturns
	fake.recordInvocation("CreateAndSwitch", []interface{}{arg1, arg2})
	fake.createAndSwitchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Brancher) CreateAndSwitchCallCount() int {
	fake.createAndSwitchMutex.RLock()
	defer fake.createAndSwitchMutex.RUnlock()
	return len(fake.createAndSwitchArgsForCall)
}

func (fake *Brancher) CreateAndSwitchCalls(stub func(context.Context, string) error) {
	fake.createAndSwitchMutex.Lock()
	defer fake.createAndSwitchMutex.Unlock()
	fake.CreateAndSwitchStub = stub
}

func (fake *Brancher) CreateAndSwitchArgsForCall(i int) (context.Context, string) {
	fake.createAndSwitchMutex.RLock()
	defer fake.createAndSwitchMutex.RUnlock()
	argsForCall := fake.createAndSwitchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Brancher) CreateAndSwitchReturns(result1 error) {
	fake.createAndSwitchMutex.Lock()
	defer fake.createAndSwitchMutex.Unlock()
	fake.CreateAndSwitchStub = nil
	fake.createAndSwitchReturns = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) CreateAndSwitchReturnsOnCall(i int, result1 error) {
	fake.createAndSwitchMutex.Lock()
	defer fake.createAndSwitchMutex.Unlock()
	fake.CreateAndSwitchStub = nil
	if fake.createAndSwitchReturnsOnCall == nil {
		fake.createAndSwitchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createAndSwitchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) CurrentBranch(arg1 context.Context) (string, error) {
	fake.currentBranchMutex.Lock()
	ret, specificReturn := fake.currentBranchReturnsOnCall[len(fake.currentBranchArgsForCall)]
	fake.currentBranchArgsForCall = append(fake.currentBranchArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CurrentBranchStub
	fakeReturns := fake.currentBranchReturns
	fake.recordInvocation("CurrentBranch", []interface{}{arg1})
	fake.currentBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Brancher) CurrentBranchCallCount() int {
	fake.currentBranchMutex.RLock()
	defer fake.currentBranchMutex.RUnlock()
	return len(fake.currentBranchArgsForCall)
}

func (fake *Brancher) CurrentBranchCalls(stub func(context.Context) (string, error)) {
	fake.currentBranchMutex.Lock()
	defer fake.currentBranchMutex.Unlock()
	fake.CurrentBranchStub = stub
}

func (fake *Brancher) CurrentBranchArgsForCall(i int) context.Context {
	fake.currentBranchMutex.RLock()
	defer fake.currentBranchMutex.RUnlock()
	argsForCall := fake.currentBranchArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Brancher) CurrentBranchReturns(result1 string, result2 error) {
	fake.currentBranchMutex.Lock()
	defer fake.currentBranchMutex.Unlock()
	fake.CurrentBranchStub = nil
	fake.currentBranchReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Brancher) CurrentBranchReturnsOnCall(i int, result1 string, result2 error) {
	fake.currentBranchMutex.Lock()
	defer fake.currentBranchMutex.Unlock()
	fake.CurrentBranchStub = nil
	if fake.currentBranchReturnsOnCall == nil {
		fake.currentBranchReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.currentBranchReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Brancher) DefaultBranch(arg1 context.Context) (string, error) {
	fake.defaultBranchMutex.Lock()
	ret, specificReturn := fake.defaultBranchReturnsOnCall[len(fake.defaultBranchArgsForCall)]
	fake.defaultBranchArgsForCall = append(fake.defaultBranchArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.DefaultBranchStub
	fakeReturns := fake.defaultBranchReturns
	fake.recordInvocation("DefaultBranch", []interface{}{arg1})
	fake.defaultBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Brancher) DefaultBranchCallCount() int {
	fake.defaultBranchMutex.RLock()
	defer fake.defaultBranchMutex.RUnlock()
	return len(fake.defaultBranchArgsForCall)
}

func (fake *Brancher) DefaultBranchCalls(stub func(context.Context) (string, error)) {
	fake.defaultBranchMutex.Lock()
	defer fake.defaultBranchMutex.Unlock()
	fake.DefaultBranchStub = stub
}

func (fake *Brancher) DefaultBranchArgsForCall(i int) context.Context {
	fake.defaultBranchMutex.RLock()
	defer fake.defaultBranchMutex.RUnlock()
	argsForCall := fake.defaultBranchArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Brancher) DefaultBranchReturns(result1 string, result2 error) {
	fake.defaultBranchMutex.Lock()
	defer fake.defaultBranchMutex.Unlock()
	fake.DefaultBranchStub = nil
	fake.defaultBranchReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Brancher) DefaultBranchReturnsOnCall(i int, result1 string, result2 error) {
	fake.defaultBranchMutex.Lock()
	defer fake.defaultBranchMutex.Unlock()
	fake.DefaultBranchStub = nil
	if fake.defaultBranchReturnsOnCall == nil {
		fake.defaultBranchReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.defaultBranchReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Brancher) Fetch(arg1 context.Context) error {
	fake.fetchMutex.Lock()
	ret, specificReturn := fake.fetchReturnsOnCall[len(fake.fetchArgsForCall)]
	fake.fetchArgsForCall = append(fake.fetchArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.FetchStub
	fakeReturns := fake.fetchReturns
	fake.recordInvocation("Fetch", []interface{}{arg1})
	fake.fetchMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Brancher) FetchCallCount() int {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	return len(fake.fetchArgsForCall)
}

func (fake *Brancher) FetchCalls(stub func(context.Context) error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = stub
}

func (fake *Brancher) FetchArgsForCall(i int) context.Context {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	argsForCall := fake.fetchArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Brancher) FetchReturns(result1 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	fake.fetchReturns = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) FetchReturnsOnCall(i int, result1 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	if fake.fetchReturnsOnCall == nil {
		fake.fetchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fetchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) FetchAndVerifyBranch(arg1 context.Context, arg2 string) error {
	fake.fetchAndVerifyBranchMutex.Lock()
	ret, specificReturn := fake.fetchAndVerifyBranchReturnsOnCall[len(fake.fetchAndVerifyBranchArgsForCall)]
	fake.fetchAndVerifyBranchArgsForCall = append(fake.fetchAndVerifyBranchArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FetchAndVerifyBranchStub
	fakeReturns := fake.fetchAndVerifyBranchReturns
	fake.recordInvocation("FetchAndVerifyBranch", []interface{}{arg1, arg2})
	fake.fetchAndVerifyBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Brancher) FetchAndVerifyBranchCallCount() int {
	fake.fetchAndVerifyBranchMutex.RLock()
	defer fake.fetchAndVerifyBranchMutex.RUnlock()
	return len(fake.fetchAndVerifyBranchArgsForCall)
}

func (fake *Brancher) FetchAndVerifyBranchCalls(stub func(context.Context, string) error) {
	fake.fetchAndVerifyBranchMutex.Lock()
	defer fake.fetchAndVerifyBranchMutex.Unlock()
	fake.FetchAndVerifyBranchStub = stub
}

func (fake *Brancher) FetchAndVerifyBranchArgsForCall(i int) (context.Context, string) {
	fake.fetchAndVerifyBranchMutex.RLock()
	defer fake.fetchAndVerifyBranchMutex.RUnlock()
	argsForCall := fake.fetchAndVerifyBranchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Brancher) FetchAndVerifyBranchReturns(result1 error) {
	fake.fetchAndVerifyBranchMutex.Lock()
	defer fake.fetchAndVerifyBranchMutex.Unlock()
	fake.FetchAndVerifyBranchStub = nil
	fake.fetchAndVerifyBranchReturns = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) FetchAndVerifyBranchReturnsOnCall(i int, result1 error) {
	fake.fetchAndVerifyBranchMutex.Lock()
	defer fake.fetchAndVerifyBranchMutex.Unlock()
	fake.FetchAndVerifyBranchStub = nil
	if fake.fetchAndVerifyBranchReturnsOnCall == nil {
		fake.fetchAndVerifyBranchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fetchAndVerifyBranchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) ForcePush(arg1 context.Context, arg2 string) error {
	fake.forcePushMutex.Lock()
	ret, specificReturn := fake.forcePushReturnsOnCall[len(fake.forcePushArgsForCall)]
	fake.forcePushArgsForCall = append(fake.forcePushArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ForcePushStub
	fakeReturns := fake.forcePushReturns
	fake.recordInvocation("ForcePush", []interface{}{arg1, arg2})
	fake.forcePushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Brancher) ForcePushCallCount() int {
	fake.forcePushMutex.RLock()
	defer fake.forcePushMutex.RUnlock()
	return len(fake.forcePushArgsForCall)
}

func (fake *Brancher) ForcePushCalls(stub func(context.Context, string) error) {
	fake.forcePushMutex.Lock()
	defer fake.forcePushMutex.Unlock()
	fake.ForcePushStub = stub
}

func (fake *Brancher) ForcePushArgsForCall(i int) (context.Context, string) {
	fake.forcePushMutex.RLock()
	defer fake.forcePushMutex.RUnlock()
	argsForCall := fake.forcePushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Brancher) ForcePushReturns(result1 error) {
	fake.forcePushMutex.Lock()
	defer fake.forcePushMutex.Unlock()
	fake.ForcePushStub = nil
	fake.forcePushReturns = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) ForcePushReturnsOnCall(i int, result1 error) {
	fake.forcePushMutex.Lock()
	defer fake.forcePushMutex.Unlock()
	fake.ForcePushStub = nil
	if fake.forcePushReturnsOnCall == nil {
		fake.forcePushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.forcePushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) MergeOriginDefault(arg1 context.Context) error {
	fake.mergeOriginDefaultMutex.Lock()
	ret, specificReturn := fake.mergeOriginDefaultReturnsOnCall[len(fake.mergeOriginDefaultArgsForCall)]
	fake.mergeOriginDefaultArgsForCall = append(fake.mergeOriginDefaultArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.MergeOriginDefaultStub
	fakeReturns := fake.mergeOriginDefaultReturns
	fake.recordInvocation("MergeOriginDefault", []interface{}{arg1})
	fake.mergeOriginDefaultMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Brancher) MergeOriginDefaultCallCount() int {
	fake.mergeOriginDefaultMutex.RLock()
	defer fake.mergeOriginDefaultMutex.RUnlock()
	return len(fake.mergeOriginDefaultArgsForCall)
}

func (fake *Brancher) MergeOriginDefaultCalls(stub func(context.Context) error) {
	fake.mergeOriginDefaultMutex.Lock()
	defer fake.mergeOriginDefaultMutex.Unlock()
	fake.MergeOriginDefaultStub = stub
}

func (fake *Brancher) MergeOriginDefaultArgsForCall(i int) context.Context {
	fake.mergeOriginDefaultMutex.RLock()
	defer fake.mergeOriginDefaultMutex.RUnlock()
	argsForCall := fake.mergeOriginDefaultArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Brancher) MergeOriginDefaultReturns(result1 error) {
	fake.mergeOriginDefaultMutex.Lock()
	defer fake.mergeOriginDefaultMutex.Unlock()
	fake.MergeOriginDefaultStub = nil
	fake.mergeOriginDefaultReturns = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) MergeOriginDefaultReturnsOnCall(i int, result1 error) {
	fake.mergeOriginDefaultMutex.Lock()
	defer fake.mergeOriginDefaultMutex.Unlock()
	fake.MergeOriginDefaultStub = nil
	if fake.mergeOriginDefaultReturnsOnCall == nil {
		fake.mergeOriginDefaultReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.mergeOriginDefaultReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) Pull(arg1 context.Context) error {
	fake.pullMutex.Lock()
	ret, specificReturn := fake.pullReturnsOnCall[len(fake.pullArgsForCall)]
	fake.pullArgsForCall = append(fake.pullArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.PullStub
	fakeReturns := fake.pullReturns
	fake.recordInvocation("Pull", []interface{}{arg1})
	fake.pullMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Brancher) PullCallCount() int {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	return len(fake.pullArgsForCall)
}

func (fake *Brancher) PullCalls(stub func(context.Context) error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = stub
}

func (fake *Brancher) PullArgsForCall(i int) context.Context {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	argsForCall := fake.pullArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Brancher) PullReturns(result1 error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = nil
	fake.pullReturns = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) PullReturnsOnCall(i int, result1 error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = nil
	if fake.pullReturnsOnCall == nil {
		fake.pullReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pullReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) Push(arg1 context.Context, arg2 string) error {
	fake.pushMutex.Lock()
	ret, specificReturn := fake.pushReturnsOnCall[len(fake.pushArgsForCall)]
	fake.pushArgsForCall = append(fake.pushArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.PushStub
	fakeReturns := fake.pushReturns
	fake.recordInvocation("Push", []interface{}{arg1, arg2})
	fake.pushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Brancher) PushCallCount() int {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	return len(fake.pushArgsForCall)
}

func (fake *Brancher) PushCalls(stub func(context.Context, string) error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = stub
}

func (fake *Brancher) PushArgsForCall(i int) (context.Context, string) {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	argsForCall := fake.pushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Brancher) PushReturns(result1 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	fake.pushReturns = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) PushReturnsOnCall(i int, result1 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	if fake.pushReturnsOnCall == nil {
		fake.pushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) Switch(arg1 context.Context, arg2 string) error {
	fake.switchMutex.Lock()
	ret, specificReturn := fake.switchReturnsOnCall[len(fake.switchArgsForCall)]
	fake.switchArgsForCall = append(fake.switchArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.SwitchStub
	fakeReturns := fake.switchReturns
	fake.recordInvocation("Switch", []interface{}{arg1, arg2})
	fake.switchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Brancher) SwitchCallCount() int {
	fake.switchMutex.RLock()
	defer fake.switchMutex.RUnlock()
	return len(fake.switchArgsForCall)
}

func (fake *Brancher) SwitchCalls(stub func(context.Context, string) error) {
	fake.switchMutex.Lock()
	defer fake.switchMutex.Unlock()
	fake.SwitchStub = stub
}

func (fake *Brancher) SwitchArgsForCall(i int) (context.Context, string) {
	fake.switchMutex.RLock()
	defer fake.switchMutex.RUnlock()
	argsForCall := fake.switchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Brancher) SwitchReturns(result1 error) {
	fake.switchMutex.Lock()
	defer fake.switchMutex.Unlock()
	fake.SwitchStub = nil
	fake.switchReturns = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) SwitchReturnsOnCall(i int, result1 error) {
	fake.switchMutex.Lock()
	defer fake.switchMutex.Unlock()
	fake.SwitchStub = nil
	if fake.switchReturnsOnCall == nil {
		fake.switchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.switchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Brancher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ git.Brancher = new(Brancher)
