// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/git"
)

type Brancher struct {
	CreateAndSwitchStub        func(context.Context, string) error
	createAndSwitchMutex       sync.RWMutex
	createAndSwitchArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	createAndSwitchReturns struct {
		result1 error
	}
	createAndSwitchReturnsOnCall map[int]struct {
		result1 error
	}
	CurrentBranchStub        func(context.Context) (string, error)
	currentBranchMutex       sync.RWMutex
	currentBranchArgsForCall []struct {
		arg1 context.Context
	}
	currentBranchReturns struct {
		result1 string
		result2 error
	}
	currentBranchReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	PushStub        func(context.Context, string) error
	pushMutex       sync.RWMutex
	pushArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	pushReturns struct {
		result1 error
	}
	pushReturnsOnCall map[int]struct {
		result1 error
	}
	SwitchStub        func(context.Context, string) error
	switchMutex       sync.RWMutex
	switchArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	switchReturns struct {
		result1 error
	}
	switchReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Brancher) CreateAndSwitch(arg1 context.Context, arg2 string) error {
	fake.createAndSwitchMutex.Lock()
	ret, specificReturn := fake.createAndSwitchReturnsOnCall[len(fake.createAndSwitchArgsForCall)]
	fake.createAndSwitchArgsForCall = append(fake.createAndSwitchArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CreateAndSwitchStub
	fakeReturns := fake.createAndSwitchReturns
	fake.recordInvocation("CreateAndSwitch", []interface{}{arg1, arg2})
	fake.createAndSwitchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Brancher) CreateAndSwitchCallCount() int {
	fake.createAndSwitchMutex.RLock()
	defer fake.createAndSwitchMutex.RUnlock()
	return len(fake.createAndSwitchArgsForCall)
}

func (fake *Brancher) CreateAndSwitchCalls(stub func(context.Context, string) error) {
	fake.createAndSwitchMutex.Lock()
	defer fake.createAndSwitchMutex.Unlock()
	fake.CreateAndSwitchStub = stub
}

func (fake *Brancher) CreateAndSwitchArgsForCall(i int) (context.Context, string) {
	fake.createAndSwitchMutex.RLock()
	defer fake.createAndSwitchMutex.RUnlock()
	argsForCall := fake.createAndSwitchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Brancher) CreateAndSwitchReturns(result1 error) {
	fake.createAndSwitchMutex.Lock()
	defer fake.createAndSwitchMutex.Unlock()
	fake.CreateAndSwitchStub = nil
	fake.createAndSwitchReturns = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) CreateAndSwitchReturnsOnCall(i int, result1 error) {
	fake.createAndSwitchMutex.Lock()
	defer fake.createAndSwitchMutex.Unlock()
	fake.CreateAndSwitchStub = nil
	if fake.createAndSwitchReturnsOnCall == nil {
		fake.createAndSwitchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createAndSwitchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) CurrentBranch(arg1 context.Context) (string, error) {
	fake.currentBranchMutex.Lock()
	ret, specificReturn := fake.currentBranchReturnsOnCall[len(fake.currentBranchArgsForCall)]
	fake.currentBranchArgsForCall = append(fake.currentBranchArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CurrentBranchStub
	fakeReturns := fake.currentBranchReturns
	fake.recordInvocation("CurrentBranch", []interface{}{arg1})
	fake.currentBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Brancher) CurrentBranchCallCount() int {
	fake.currentBranchMutex.RLock()
	defer fake.currentBranchMutex.RUnlock()
	return len(fake.currentBranchArgsForCall)
}

func (fake *Brancher) CurrentBranchCalls(stub func(context.Context) (string, error)) {
	fake.currentBranchMutex.Lock()
	defer fake.currentBranchMutex.Unlock()
	fake.CurrentBranchStub = stub
}

func (fake *Brancher) CurrentBranchArgsForCall(i int) context.Context {
	fake.currentBranchMutex.RLock()
	defer fake.currentBranchMutex.RUnlock()
	argsForCall := fake.currentBranchArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Brancher) CurrentBranchReturns(result1 string, result2 error) {
	fake.currentBranchMutex.Lock()
	defer fake.currentBranchMutex.Unlock()
	fake.CurrentBranchStub = nil
	fake.currentBranchReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Brancher) CurrentBranchReturnsOnCall(i int, result1 string, result2 error) {
	fake.currentBranchMutex.Lock()
	defer fake.currentBranchMutex.Unlock()
	fake.CurrentBranchStub = nil
	if fake.currentBranchReturnsOnCall == nil {
		fake.currentBranchReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.currentBranchReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Brancher) Push(arg1 context.Context, arg2 string) error {
	fake.pushMutex.Lock()
	ret, specificReturn := fake.pushReturnsOnCall[len(fake.pushArgsForCall)]
	fake.pushArgsForCall = append(fake.pushArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.PushStub
	fakeReturns := fake.pushReturns
	fake.recordInvocation("Push", []interface{}{arg1, arg2})
	fake.pushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Brancher) PushCallCount() int {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	return len(fake.pushArgsForCall)
}

func (fake *Brancher) PushCalls(stub func(context.Context, string) error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = stub
}

func (fake *Brancher) PushArgsForCall(i int) (context.Context, string) {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	argsForCall := fake.pushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Brancher) PushReturns(result1 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	fake.pushReturns = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) PushReturnsOnCall(i int, result1 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	if fake.pushReturnsOnCall == nil {
		fake.pushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) Switch(arg1 context.Context, arg2 string) error {
	fake.switchMutex.Lock()
	ret, specificReturn := fake.switchReturnsOnCall[len(fake.switchArgsForCall)]
	fake.switchArgsForCall = append(fake.switchArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.SwitchStub
	fakeReturns := fake.switchReturns
	fake.recordInvocation("Switch", []interface{}{arg1, arg2})
	fake.switchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Brancher) SwitchCallCount() int {
	fake.switchMutex.RLock()
	defer fake.switchMutex.RUnlock()
	return len(fake.switchArgsForCall)
}

func (fake *Brancher) SwitchCalls(stub func(context.Context, string) error) {
	fake.switchMutex.Lock()
	defer fake.switchMutex.Unlock()
	fake.SwitchStub = stub
}

func (fake *Brancher) SwitchArgsForCall(i int) (context.Context, string) {
	fake.switchMutex.RLock()
	defer fake.switchMutex.RUnlock()
	argsForCall := fake.switchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Brancher) SwitchReturns(result1 error) {
	fake.switchMutex.Lock()
	defer fake.switchMutex.Unlock()
	fake.SwitchStub = nil
	fake.switchReturns = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) SwitchReturnsOnCall(i int, result1 error) {
	fake.switchMutex.Lock()
	defer fake.switchMutex.Unlock()
	fake.SwitchStub = nil
	if fake.switchReturnsOnCall == nil {
		fake.switchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.switchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Brancher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Brancher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ git.Brancher = new(Brancher)
