// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/cmd"
	"github.com/bborbe/dark-factory/pkg/prompt"
)

type CmdPromptManager struct {
	LoadStub        func(context.Context, string) (*prompt.PromptFile, error)
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	loadReturns struct {
		result1 *prompt.PromptFile
		result2 error
	}
	loadReturnsOnCall map[int]struct {
		result1 *prompt.PromptFile
		result2 error
	}
	MoveToCompletedStub        func(context.Context, string) error
	moveToCompletedMutex       sync.RWMutex
	moveToCompletedArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	moveToCompletedReturns struct {
		result1 error
	}
	moveToCompletedReturnsOnCall map[int]struct {
		result1 error
	}
	NormalizeFilenamesStub        func(context.Context, string) ([]prompt.Rename, error)
	normalizeFilenamesMutex       sync.RWMutex
	normalizeFilenamesArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	normalizeFilenamesReturns struct {
		result1 []prompt.Rename
		result2 error
	}
	normalizeFilenamesReturnsOnCall map[int]struct {
		result1 []prompt.Rename
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CmdPromptManager) Load(arg1 context.Context, arg2 string) (*prompt.PromptFile, error) {
	fake.loadMutex.Lock()
	ret, specificReturn := fake.loadReturnsOnCall[len(fake.loadArgsForCall)]
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LoadStub
	fakeReturns := fake.loadReturns
	fake.recordInvocation("Load", []interface{}{arg1, arg2})
	fake.loadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CmdPromptManager) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *CmdPromptManager) LoadCalls(stub func(context.Context, string) (*prompt.PromptFile, error)) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = stub
}

func (fake *CmdPromptManager) LoadArgsForCall(i int) (context.Context, string) {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	argsForCall := fake.loadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *CmdPromptManager) LoadReturns(result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *CmdPromptManager) LoadReturnsOnCall(i int, result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	if fake.loadReturnsOnCall == nil {
		fake.loadReturnsOnCall = make(map[int]struct {
			result1 *prompt.PromptFile
			result2 error
		})
	}
	fake.loadReturnsOnCall[i] = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *CmdPromptManager) MoveToCompleted(arg1 context.Context, arg2 string) error {
	fake.moveToCompletedMutex.Lock()
	ret, specificReturn := fake.moveToCompletedReturnsOnCall[len(fake.moveToCompletedArgsForCall)]
	fake.moveToCompletedArgsForCall = append(fake.moveToCompletedArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.MoveToCompletedStub
	fakeReturns := fake.moveToCompletedReturns
	fake.recordInvocation("MoveToCompleted", []interface{}{arg1, arg2})
	fake.moveToCompletedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CmdPromptManager) MoveToCompletedCallCount() int {
	fake.moveToCompletedMutex.RLock()
	defer fake.moveToCompletedMutex.RUnlock()
	return len(fake.moveToCompletedArgsForCall)
}

func (fake *CmdPromptManager) MoveToCompletedCalls(stub func(context.Context, string) error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = stub
}

func (fake *CmdPromptManager) MoveToCompletedArgsForCall(i int) (context.Context, string) {
	fake.moveToCompletedMutex.RLock()
	defer fake.moveToCompletedMutex.RUnlock()
	argsForCall := fake.moveToCompletedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *CmdPromptManager) MoveToCompletedReturns(result1 error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = nil
	fake.moveToCompletedReturns = struct {
		result1 error
	}{result1}
}

func (fake *CmdPromptManager) MoveToCompletedReturnsOnCall(i int, result1 error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = nil
	if fake.moveToCompletedReturnsOnCall == nil {
		fake.moveToCompletedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.moveToCompletedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CmdPromptManager) NormalizeFilenames(arg1 context.Context, arg2 string) ([]prompt.Rename, error) {
	fake.normalizeFilenamesMutex.Lock()
	ret, specificReturn := fake.normalizeFilenamesReturnsOnCall[len(fake.normalizeFilenamesArgsForCall)]
	fake.normalizeFilenamesArgsForCall = append(fake.normalizeFilenamesArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.NormalizeFilenamesStub
	fakeReturns := fake.normalizeFilenamesReturns
	fake.recordInvocation("NormalizeFilenames", []interface{}{arg1, arg2})
	fake.normalizeFilenamesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CmdPromptManager) NormalizeFilenamesCallCount() int {
	fake.normalizeFilenamesMutex.RLock()
	defer fake.normalizeFilenamesMutex.RUnlock()
	return len(fake.normalizeFilenamesArgsForCall)
}

func (fake *CmdPromptManager) NormalizeFilenamesCalls(stub func(context.Context, string) ([]prompt.Rename, error)) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = stub
}

func (fake *CmdPromptManager) NormalizeFilenamesArgsForCall(i int) (context.Context, string) {
	fake.normalizeFilenamesMutex.RLock()
	defer fake.normalizeFilenamesMutex.RUnlock()
	argsForCall := fake.normalizeFilenamesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *CmdPromptManager) NormalizeFilenamesReturns(result1 []prompt.Rename, result2 error) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = nil
	fake.normalizeFilenamesReturns = struct {
		result1 []prompt.Rename
		result2 error
	}{result1, result2}
}

func (fake *CmdPromptManager) NormalizeFilenamesReturnsOnCall(i int, result1 []prompt.Rename, result2 error) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = nil
	if fake.normalizeFilenamesReturnsOnCall == nil {
		fake.normalizeFilenamesReturnsOnCall = make(map[int]struct {
			result1 []prompt.Rename
			result2 error
		})
	}
	fake.normalizeFilenamesReturnsOnCall[i] = struct {
		result1 []prompt.Rename
		result2 error
	}{result1, result2}
}

func (fake *CmdPromptManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CmdPromptManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cmd.PromptManager = new(CmdPromptManager)
