// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/committingrecoverer"
)

type CommittingRecoverer struct {
	RecoverStub        func(context.Context, string) error
	recoverMutex       sync.RWMutex
	recoverArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	recoverReturns struct {
		result1 error
	}
	recoverReturnsOnCall map[int]struct {
		result1 error
	}
	RecoverAllStub        func(context.Context)
	recoverAllMutex       sync.RWMutex
	recoverAllArgsForCall []struct {
		arg1 context.Context
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CommittingRecoverer) Recover(arg1 context.Context, arg2 string) error {
	fake.recoverMutex.Lock()
	ret, specificReturn := fake.recoverReturnsOnCall[len(fake.recoverArgsForCall)]
	fake.recoverArgsForCall = append(fake.recoverArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.RecoverStub
	fakeReturns := fake.recoverReturns
	fake.recordInvocation("Recover", []interface{}{arg1, arg2})
	fake.recoverMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CommittingRecoverer) RecoverCallCount() int {
	fake.recoverMutex.RLock()
	defer fake.recoverMutex.RUnlock()
	return len(fake.recoverArgsForCall)
}

func (fake *CommittingRecoverer) RecoverCalls(stub func(context.Context, string) error) {
	fake.recoverMutex.Lock()
	defer fake.recoverMutex.Unlock()
	fake.RecoverStub = stub
}

func (fake *CommittingRecoverer) RecoverArgsForCall(i int) (context.Context, string) {
	fake.recoverMutex.RLock()
	defer fake.recoverMutex.RUnlock()
	argsForCall := fake.recoverArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *CommittingRecoverer) RecoverReturns(result1 error) {
	fake.recoverMutex.Lock()
	defer fake.recoverMutex.Unlock()
	fake.RecoverStub = nil
	fake.recoverReturns = struct {
		result1 error
	}{result1}
}

func (fake *CommittingRecoverer) RecoverReturnsOnCall(i int, result1 error) {
	fake.recoverMutex.Lock()
	defer fake.recoverMutex.Unlock()
	fake.RecoverStub = nil
	if fake.recoverReturnsOnCall == nil {
		fake.recoverReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.recoverReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CommittingRecoverer) RecoverAll(arg1 context.Context) {
	fake.recoverAllMutex.Lock()
	fake.recoverAllArgsForCall = append(fake.recoverAllArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RecoverAllStub
	fake.recordInvocation("RecoverAll", []interface{}{arg1})
	fake.recoverAllMutex.Unlock()
	if stub != nil {
		fake.RecoverAllStub(arg1)
	}
}

func (fake *CommittingRecoverer) RecoverAllCallCount() int {
	fake.recoverAllMutex.RLock()
	defer fake.recoverAllMutex.RUnlock()
	return len(fake.recoverAllArgsForCall)
}

func (fake *CommittingRecoverer) RecoverAllCalls(stub func(context.Context)) {
	fake.recoverAllMutex.Lock()
	defer fake.recoverAllMutex.Unlock()
	fake.RecoverAllStub = stub
}

func (fake *CommittingRecoverer) RecoverAllArgsForCall(i int) context.Context {
	fake.recoverAllMutex.RLock()
	defer fake.recoverAllMutex.RUnlock()
	argsForCall := fake.recoverAllArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CommittingRecoverer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CommittingRecoverer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ committingrecoverer.Recoverer = new(CommittingRecoverer)
