// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/executor"
)

type ContainerCounter struct {
	CountRunningStub        func(context.Context) (int, error)
	countRunningMutex       sync.RWMutex
	countRunningArgsForCall []struct {
		arg1 context.Context
	}
	countRunningReturns struct {
		result1 int
		result2 error
	}
	countRunningReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ContainerCounter) CountRunning(arg1 context.Context) (int, error) {
	fake.countRunningMutex.Lock()
	ret, specificReturn := fake.countRunningReturnsOnCall[len(fake.countRunningArgsForCall)]
	fake.countRunningArgsForCall = append(fake.countRunningArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CountRunningStub
	fakeReturns := fake.countRunningReturns
	fake.recordInvocation("CountRunning", []interface{}{arg1})
	fake.countRunningMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ContainerCounter) CountRunningCallCount() int {
	fake.countRunningMutex.RLock()
	defer fake.countRunningMutex.RUnlock()
	return len(fake.countRunningArgsForCall)
}

func (fake *ContainerCounter) CountRunningCalls(stub func(context.Context) (int, error)) {
	fake.countRunningMutex.Lock()
	defer fake.countRunningMutex.Unlock()
	fake.CountRunningStub = stub
}

func (fake *ContainerCounter) CountRunningArgsForCall(i int) context.Context {
	fake.countRunningMutex.RLock()
	defer fake.countRunningMutex.RUnlock()
	argsForCall := fake.countRunningArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ContainerCounter) CountRunningReturns(result1 int, result2 error) {
	fake.countRunningMutex.Lock()
	defer fake.countRunningMutex.Unlock()
	fake.CountRunningStub = nil
	fake.countRunningReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *ContainerCounter) CountRunningReturnsOnCall(i int, result1 int, result2 error) {
	fake.countRunningMutex.Lock()
	defer fake.countRunningMutex.Unlock()
	fake.CountRunningStub = nil
	if fake.countRunningReturnsOnCall == nil {
		fake.countRunningReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.countRunningReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *ContainerCounter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ContainerCounter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ executor.ContainerCounter = new(ContainerCounter)
