// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/containerslot"
)

type Manager struct {
	AcquireStub        func(context.Context) (func(), error)
	acquireMutex       sync.RWMutex
	acquireArgsForCall []struct {
		arg1 context.Context
	}
	acquireReturns struct {
		result1 func()
		result2 error
	}
	acquireReturnsOnCall map[int]struct {
		result1 func()
		result2 error
	}
	ReleaseAfterStartStub        func(context.Context, string, func())
	releaseAfterStartMutex       sync.RWMutex
	releaseAfterStartArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 func()
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Manager) Acquire(arg1 context.Context) (func(), error) {
	fake.acquireMutex.Lock()
	ret, specificReturn := fake.acquireReturnsOnCall[len(fake.acquireArgsForCall)]
	fake.acquireArgsForCall = append(fake.acquireArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.AcquireStub
	fakeReturns := fake.acquireReturns
	fake.recordInvocation("Acquire", []interface{}{arg1})
	fake.acquireMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Manager) AcquireCallCount() int {
	fake.acquireMutex.RLock()
	defer fake.acquireMutex.RUnlock()
	return len(fake.acquireArgsForCall)
}

func (fake *Manager) AcquireCalls(stub func(context.Context) (func(), error)) {
	fake.acquireMutex.Lock()
	defer fake.acquireMutex.Unlock()
	fake.AcquireStub = stub
}

func (fake *Manager) AcquireArgsForCall(i int) context.Context {
	fake.acquireMutex.RLock()
	defer fake.acquireMutex.RUnlock()
	argsForCall := fake.acquireArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Manager) AcquireReturns(result1 func(), result2 error) {
	fake.acquireMutex.Lock()
	defer fake.acquireMutex.Unlock()
	fake.AcquireStub = nil
	fake.acquireReturns = struct {
		result1 func()
		result2 error
	}{result1, result2}
}

func (fake *Manager) AcquireReturnsOnCall(i int, result1 func(), result2 error) {
	fake.acquireMutex.Lock()
	defer fake.acquireMutex.Unlock()
	fake.AcquireStub = nil
	if fake.acquireReturnsOnCall == nil {
		fake.acquireReturnsOnCall = make(map[int]struct {
			result1 func()
			result2 error
		})
	}
	fake.acquireReturnsOnCall[i] = struct {
		result1 func()
		result2 error
	}{result1, result2}
}

func (fake *Manager) ReleaseAfterStart(arg1 context.Context, arg2 string, arg3 func()) {
	fake.releaseAfterStartMutex.Lock()
	fake.releaseAfterStartArgsForCall = append(fake.releaseAfterStartArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 func()
	}{arg1, arg2, arg3})
	stub := fake.ReleaseAfterStartStub
	fake.recordInvocation("ReleaseAfterStart", []interface{}{arg1, arg2, arg3})
	fake.releaseAfterStartMutex.Unlock()
	if stub != nil {
		fake.ReleaseAfterStartStub(arg1, arg2, arg3)
	}
}

func (fake *Manager) ReleaseAfterStartCallCount() int {
	fake.releaseAfterStartMutex.RLock()
	defer fake.releaseAfterStartMutex.RUnlock()
	return len(fake.releaseAfterStartArgsForCall)
}

func (fake *Manager) ReleaseAfterStartCalls(stub func(context.Context, string, func())) {
	fake.releaseAfterStartMutex.Lock()
	defer fake.releaseAfterStartMutex.Unlock()
	fake.ReleaseAfterStartStub = stub
}

func (fake *Manager) ReleaseAfterStartArgsForCall(i int) (context.Context, string, func()) {
	fake.releaseAfterStartMutex.RLock()
	defer fake.releaseAfterStartMutex.RUnlock()
	argsForCall := fake.releaseAfterStartArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Manager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Manager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ containerslot.Manager = new(Manager)
