// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"
	"time"

	"github.com/bborbe/dark-factory/pkg/executor"
)

type ContainerChecker struct {
	IsRunningStub        func(context.Context, string) (bool, error)
	isRunningMutex       sync.RWMutex
	isRunningArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	isRunningReturns struct {
		result1 bool
		result2 error
	}
	isRunningReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	WaitUntilRunningStub        func(context.Context, string, time.Duration) error
	waitUntilRunningMutex       sync.RWMutex
	waitUntilRunningArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.Duration
	}
	waitUntilRunningReturns struct {
		result1 error
	}
	waitUntilRunningReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ContainerChecker) IsRunning(arg1 context.Context, arg2 string) (bool, error) {
	fake.isRunningMutex.Lock()
	ret, specificReturn := fake.isRunningReturnsOnCall[len(fake.isRunningArgsForCall)]
	fake.isRunningArgsForCall = append(fake.isRunningArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.IsRunningStub
	fakeReturns := fake.isRunningReturns
	fake.recordInvocation("IsRunning", []interface{}{arg1, arg2})
	fake.isRunningMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ContainerChecker) IsRunningCallCount() int {
	fake.isRunningMutex.RLock()
	defer fake.isRunningMutex.RUnlock()
	return len(fake.isRunningArgsForCall)
}

func (fake *ContainerChecker) IsRunningCalls(stub func(context.Context, string) (bool, error)) {
	fake.isRunningMutex.Lock()
	defer fake.isRunningMutex.Unlock()
	fake.IsRunningStub = stub
}

func (fake *ContainerChecker) IsRunningArgsForCall(i int) (context.Context, string) {
	fake.isRunningMutex.RLock()
	defer fake.isRunningMutex.RUnlock()
	argsForCall := fake.isRunningArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ContainerChecker) IsRunningReturns(result1 bool, result2 error) {
	fake.isRunningMutex.Lock()
	defer fake.isRunningMutex.Unlock()
	fake.IsRunningStub = nil
	fake.isRunningReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *ContainerChecker) IsRunningReturnsOnCall(i int, result1 bool, result2 error) {
	fake.isRunningMutex.Lock()
	defer fake.isRunningMutex.Unlock()
	fake.IsRunningStub = nil
	if fake.isRunningReturnsOnCall == nil {
		fake.isRunningReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.isRunningReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *ContainerChecker) WaitUntilRunning(arg1 context.Context, arg2 string, arg3 time.Duration) error {
	fake.waitUntilRunningMutex.Lock()
	ret, specificReturn := fake.waitUntilRunningReturnsOnCall[len(fake.waitUntilRunningArgsForCall)]
	fake.waitUntilRunningArgsForCall = append(fake.waitUntilRunningArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.Duration
	}{arg1, arg2, arg3})
	stub := fake.WaitUntilRunningStub
	fakeReturns := fake.waitUntilRunningReturns
	fake.recordInvocation("WaitUntilRunning", []interface{}{arg1, arg2, arg3})
	fake.waitUntilRunningMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ContainerChecker) WaitUntilRunningCallCount() int {
	fake.waitUntilRunningMutex.RLock()
	defer fake.waitUntilRunningMutex.RUnlock()
	return len(fake.waitUntilRunningArgsForCall)
}

func (fake *ContainerChecker) WaitUntilRunningCalls(stub func(context.Context, string, time.Duration) error) {
	fake.waitUntilRunningMutex.Lock()
	defer fake.waitUntilRunningMutex.Unlock()
	fake.WaitUntilRunningStub = stub
}

func (fake *ContainerChecker) WaitUntilRunningArgsForCall(i int) (context.Context, string, time.Duration) {
	fake.waitUntilRunningMutex.RLock()
	defer fake.waitUntilRunningMutex.RUnlock()
	argsForCall := fake.waitUntilRunningArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ContainerChecker) WaitUntilRunningReturns(result1 error) {
	fake.waitUntilRunningMutex.Lock()
	defer fake.waitUntilRunningMutex.Unlock()
	fake.WaitUntilRunningStub = nil
	fake.waitUntilRunningReturns = struct {
		result1 error
	}{result1}
}

func (fake *ContainerChecker) WaitUntilRunningReturnsOnCall(i int, result1 error) {
	fake.waitUntilRunningMutex.Lock()
	defer fake.waitUntilRunningMutex.Unlock()
	fake.WaitUntilRunningStub = nil
	if fake.waitUntilRunningReturnsOnCall == nil {
		fake.waitUntilRunningReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.waitUntilRunningReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ContainerChecker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ContainerChecker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ executor.ContainerChecker = new(ContainerChecker)
