// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/processor"
)

type DirtyFileChecker struct {
	CountDirtyFilesStub        func(context.Context) (int, error)
	countDirtyFilesMutex       sync.RWMutex
	countDirtyFilesArgsForCall []struct {
		arg1 context.Context
	}
	countDirtyFilesReturns struct {
		result1 int
		result2 error
	}
	countDirtyFilesReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *DirtyFileChecker) CountDirtyFiles(arg1 context.Context) (int, error) {
	fake.countDirtyFilesMutex.Lock()
	ret, specificReturn := fake.countDirtyFilesReturnsOnCall[len(fake.countDirtyFilesArgsForCall)]
	fake.countDirtyFilesArgsForCall = append(fake.countDirtyFilesArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CountDirtyFilesStub
	fakeReturns := fake.countDirtyFilesReturns
	fake.recordInvocation("CountDirtyFiles", []interface{}{arg1})
	fake.countDirtyFilesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *DirtyFileChecker) CountDirtyFilesCallCount() int {
	fake.countDirtyFilesMutex.RLock()
	defer fake.countDirtyFilesMutex.RUnlock()
	return len(fake.countDirtyFilesArgsForCall)
}

func (fake *DirtyFileChecker) CountDirtyFilesCalls(stub func(context.Context) (int, error)) {
	fake.countDirtyFilesMutex.Lock()
	defer fake.countDirtyFilesMutex.Unlock()
	fake.CountDirtyFilesStub = stub
}

func (fake *DirtyFileChecker) CountDirtyFilesArgsForCall(i int) context.Context {
	fake.countDirtyFilesMutex.RLock()
	defer fake.countDirtyFilesMutex.RUnlock()
	argsForCall := fake.countDirtyFilesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *DirtyFileChecker) CountDirtyFilesReturns(result1 int, result2 error) {
	fake.countDirtyFilesMutex.Lock()
	defer fake.countDirtyFilesMutex.Unlock()
	fake.CountDirtyFilesStub = nil
	fake.countDirtyFilesReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *DirtyFileChecker) CountDirtyFilesReturnsOnCall(i int, result1 int, result2 error) {
	fake.countDirtyFilesMutex.Lock()
	defer fake.countDirtyFilesMutex.Unlock()
	fake.CountDirtyFilesStub = nil
	if fake.countDirtyFilesReturnsOnCall == nil {
		fake.countDirtyFilesReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.countDirtyFilesReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *DirtyFileChecker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DirtyFileChecker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ processor.DirtyFileChecker = new(DirtyFileChecker)
