// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/doctor"
)

type DoctorFixer struct {
	ApplyStub        func(context.Context, []doctor.Finding, doctor.ApplyOptions) (doctor.ApplyResult, error)
	applyMutex       sync.RWMutex
	applyArgsForCall []struct {
		arg1 context.Context
		arg2 []doctor.Finding
		arg3 doctor.ApplyOptions
	}
	applyReturns struct {
		result1 doctor.ApplyResult
		result2 error
	}
	applyReturnsOnCall map[int]struct {
		result1 doctor.ApplyResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *DoctorFixer) Apply(arg1 context.Context, arg2 []doctor.Finding, arg3 doctor.ApplyOptions) (doctor.ApplyResult, error) {
	var arg2Copy []doctor.Finding
	if arg2 != nil {
		arg2Copy = make([]doctor.Finding, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.applyMutex.Lock()
	ret, specificReturn := fake.applyReturnsOnCall[len(fake.applyArgsForCall)]
	fake.applyArgsForCall = append(fake.applyArgsForCall, struct {
		arg1 context.Context
		arg2 []doctor.Finding
		arg3 doctor.ApplyOptions
	}{arg1, arg2Copy, arg3})
	stub := fake.ApplyStub
	fakeReturns := fake.applyReturns
	fake.recordInvocation("Apply", []interface{}{arg1, arg2Copy, arg3})
	fake.applyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *DoctorFixer) ApplyCallCount() int {
	fake.applyMutex.RLock()
	defer fake.applyMutex.RUnlock()
	return len(fake.applyArgsForCall)
}

func (fake *DoctorFixer) ApplyCalls(stub func(context.Context, []doctor.Finding, doctor.ApplyOptions) (doctor.ApplyResult, error)) {
	fake.applyMutex.Lock()
	defer fake.applyMutex.Unlock()
	fake.ApplyStub = stub
}

func (fake *DoctorFixer) ApplyArgsForCall(i int) (context.Context, []doctor.Finding, doctor.ApplyOptions) {
	fake.applyMutex.RLock()
	defer fake.applyMutex.RUnlock()
	argsForCall := fake.applyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *DoctorFixer) ApplyReturns(result1 doctor.ApplyResult, result2 error) {
	fake.applyMutex.Lock()
	defer fake.applyMutex.Unlock()
	fake.ApplyStub = nil
	fake.applyReturns = struct {
		result1 doctor.ApplyResult
		result2 error
	}{result1, result2}
}

func (fake *DoctorFixer) ApplyReturnsOnCall(i int, result1 doctor.ApplyResult, result2 error) {
	fake.applyMutex.Lock()
	defer fake.applyMutex.Unlock()
	fake.ApplyStub = nil
	if fake.applyReturnsOnCall == nil {
		fake.applyReturnsOnCall = make(map[int]struct {
			result1 doctor.ApplyResult
			result2 error
		})
	}
	fake.applyReturnsOnCall[i] = struct {
		result1 doctor.ApplyResult
		result2 error
	}{result1, result2}
}

func (fake *DoctorFixer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DoctorFixer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ doctor.Fixer = new(DoctorFixer)
