// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/doctor"
	"github.com/bborbe/dark-factory/pkg/prompt"
)

type DoctorPromptManager struct {
	LoadStub        func(context.Context, string) (*prompt.PromptFile, error)
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	loadReturns struct {
		result1 *prompt.PromptFile
		result2 error
	}
	loadReturnsOnCall map[int]struct {
		result1 *prompt.PromptFile
		result2 error
	}
	MoveToCancelledStub        func(context.Context, string) error
	moveToCancelledMutex       sync.RWMutex
	moveToCancelledArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	moveToCancelledReturns struct {
		result1 error
	}
	moveToCancelledReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *DoctorPromptManager) Load(arg1 context.Context, arg2 string) (*prompt.PromptFile, error) {
	fake.loadMutex.Lock()
	ret, specificReturn := fake.loadReturnsOnCall[len(fake.loadArgsForCall)]
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LoadStub
	fakeReturns := fake.loadReturns
	fake.recordInvocation("Load", []interface{}{arg1, arg2})
	fake.loadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *DoctorPromptManager) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *DoctorPromptManager) LoadCalls(stub func(context.Context, string) (*prompt.PromptFile, error)) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = stub
}

func (fake *DoctorPromptManager) LoadArgsForCall(i int) (context.Context, string) {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	argsForCall := fake.loadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *DoctorPromptManager) LoadReturns(result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *DoctorPromptManager) LoadReturnsOnCall(i int, result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	if fake.loadReturnsOnCall == nil {
		fake.loadReturnsOnCall = make(map[int]struct {
			result1 *prompt.PromptFile
			result2 error
		})
	}
	fake.loadReturnsOnCall[i] = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *DoctorPromptManager) MoveToCancelled(arg1 context.Context, arg2 string) error {
	fake.moveToCancelledMutex.Lock()
	ret, specificReturn := fake.moveToCancelledReturnsOnCall[len(fake.moveToCancelledArgsForCall)]
	fake.moveToCancelledArgsForCall = append(fake.moveToCancelledArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.MoveToCancelledStub
	fakeReturns := fake.moveToCancelledReturns
	fake.recordInvocation("MoveToCancelled", []interface{}{arg1, arg2})
	fake.moveToCancelledMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *DoctorPromptManager) MoveToCancelledCallCount() int {
	fake.moveToCancelledMutex.RLock()
	defer fake.moveToCancelledMutex.RUnlock()
	return len(fake.moveToCancelledArgsForCall)
}

func (fake *DoctorPromptManager) MoveToCancelledCalls(stub func(context.Context, string) error) {
	fake.moveToCancelledMutex.Lock()
	defer fake.moveToCancelledMutex.Unlock()
	fake.MoveToCancelledStub = stub
}

func (fake *DoctorPromptManager) MoveToCancelledArgsForCall(i int) (context.Context, string) {
	fake.moveToCancelledMutex.RLock()
	defer fake.moveToCancelledMutex.RUnlock()
	argsForCall := fake.moveToCancelledArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *DoctorPromptManager) MoveToCancelledReturns(result1 error) {
	fake.moveToCancelledMutex.Lock()
	defer fake.moveToCancelledMutex.Unlock()
	fake.MoveToCancelledStub = nil
	fake.moveToCancelledReturns = struct {
		result1 error
	}{result1}
}

func (fake *DoctorPromptManager) MoveToCancelledReturnsOnCall(i int, result1 error) {
	fake.moveToCancelledMutex.Lock()
	defer fake.moveToCancelledMutex.Unlock()
	fake.MoveToCancelledStub = nil
	if fake.moveToCancelledReturnsOnCall == nil {
		fake.moveToCancelledReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.moveToCancelledReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *DoctorPromptManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DoctorPromptManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ doctor.PromptManager = new(DoctorPromptManager)
