// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/executor"
)

type Executor struct {
	ExecuteStub        func(context.Context, string, string, string) error
	executeMutex       sync.RWMutex
	executeArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	executeReturns struct {
		result1 error
	}
	executeReturnsOnCall map[int]struct {
		result1 error
	}
	ReattachStub        func(context.Context, string, string) error
	reattachMutex       sync.RWMutex
	reattachArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	reattachReturns struct {
		result1 error
	}
	reattachReturnsOnCall map[int]struct {
		result1 error
	}
	StopAndRemoveContainerStub        func(context.Context, string)
	stopAndRemoveContainerMutex       sync.RWMutex
	stopAndRemoveContainerArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Executor) Execute(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.executeMutex.Lock()
	ret, specificReturn := fake.executeReturnsOnCall[len(fake.executeArgsForCall)]
	fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.ExecuteStub
	fakeReturns := fake.executeReturns
	fake.recordInvocation("Execute", []interface{}{arg1, arg2, arg3, arg4})
	fake.executeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Executor) ExecuteCallCount() int {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return len(fake.executeArgsForCall)
}

func (fake *Executor) ExecuteCalls(stub func(context.Context, string, string, string) error) {
	fake.executeMutex.Lock()
	defer fake.executeMutex.Unlock()
	fake.ExecuteStub = stub
}

func (fake *Executor) ExecuteArgsForCall(i int) (context.Context, string, string, string) {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	argsForCall := fake.executeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *Executor) ExecuteReturns(result1 error) {
	fake.executeMutex.Lock()
	defer fake.executeMutex.Unlock()
	fake.ExecuteStub = nil
	fake.executeReturns = struct {
		result1 error
	}{result1}
}

func (fake *Executor) ExecuteReturnsOnCall(i int, result1 error) {
	fake.executeMutex.Lock()
	defer fake.executeMutex.Unlock()
	fake.ExecuteStub = nil
	if fake.executeReturnsOnCall == nil {
		fake.executeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.executeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Executor) Reattach(arg1 context.Context, arg2 string, arg3 string) error {
	fake.reattachMutex.Lock()
	ret, specificReturn := fake.reattachReturnsOnCall[len(fake.reattachArgsForCall)]
	fake.reattachArgsForCall = append(fake.reattachArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ReattachStub
	fakeReturns := fake.reattachReturns
	fake.recordInvocation("Reattach", []interface{}{arg1, arg2, arg3})
	fake.reattachMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Executor) ReattachCallCount() int {
	fake.reattachMutex.RLock()
	defer fake.reattachMutex.RUnlock()
	return len(fake.reattachArgsForCall)
}

func (fake *Executor) ReattachCalls(stub func(context.Context, string, string) error) {
	fake.reattachMutex.Lock()
	defer fake.reattachMutex.Unlock()
	fake.ReattachStub = stub
}

func (fake *Executor) ReattachArgsForCall(i int) (context.Context, string, string) {
	fake.reattachMutex.RLock()
	defer fake.reattachMutex.RUnlock()
	argsForCall := fake.reattachArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Executor) ReattachReturns(result1 error) {
	fake.reattachMutex.Lock()
	defer fake.reattachMutex.Unlock()
	fake.ReattachStub = nil
	fake.reattachReturns = struct {
		result1 error
	}{result1}
}

func (fake *Executor) ReattachReturnsOnCall(i int, result1 error) {
	fake.reattachMutex.Lock()
	defer fake.reattachMutex.Unlock()
	fake.ReattachStub = nil
	if fake.reattachReturnsOnCall == nil {
		fake.reattachReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.reattachReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Executor) StopAndRemoveContainer(arg1 context.Context, arg2 string) {
	fake.stopAndRemoveContainerMutex.Lock()
	fake.stopAndRemoveContainerArgsForCall = append(fake.stopAndRemoveContainerArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.StopAndRemoveContainerStub
	fake.recordInvocation("StopAndRemoveContainer", []interface{}{arg1, arg2})
	fake.stopAndRemoveContainerMutex.Unlock()
	if stub != nil {
		fake.StopAndRemoveContainerStub(arg1, arg2)
	}
}

func (fake *Executor) StopAndRemoveContainerCallCount() int {
	fake.stopAndRemoveContainerMutex.RLock()
	defer fake.stopAndRemoveContainerMutex.RUnlock()
	return len(fake.stopAndRemoveContainerArgsForCall)
}

func (fake *Executor) StopAndRemoveContainerCalls(stub func(context.Context, string)) {
	fake.stopAndRemoveContainerMutex.Lock()
	defer fake.stopAndRemoveContainerMutex.Unlock()
	fake.StopAndRemoveContainerStub = stub
}

func (fake *Executor) StopAndRemoveContainerArgsForCall(i int) (context.Context, string) {
	fake.stopAndRemoveContainerMutex.RLock()
	defer fake.stopAndRemoveContainerMutex.RUnlock()
	argsForCall := fake.stopAndRemoveContainerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Executor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Executor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ executor.Executor = new(Executor)
