// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/failurehandler"
)

type FailureHandler struct {
	HandleStub        func(context.Context, string, error) error
	handleMutex       sync.RWMutex
	handleArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 error
	}
	handleReturns struct {
		result1 error
	}
	handleReturnsOnCall map[int]struct {
		result1 error
	}
	NotifyFromReportStub        func(context.Context, string, string)
	notifyFromReportMutex       sync.RWMutex
	notifyFromReportArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FailureHandler) Handle(arg1 context.Context, arg2 string, arg3 error) error {
	fake.handleMutex.Lock()
	ret, specificReturn := fake.handleReturnsOnCall[len(fake.handleArgsForCall)]
	fake.handleArgsForCall = append(fake.handleArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 error
	}{arg1, arg2, arg3})
	stub := fake.HandleStub
	fakeReturns := fake.handleReturns
	fake.recordInvocation("Handle", []interface{}{arg1, arg2, arg3})
	fake.handleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FailureHandler) HandleCallCount() int {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	return len(fake.handleArgsForCall)
}

func (fake *FailureHandler) HandleCalls(stub func(context.Context, string, error) error) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = stub
}

func (fake *FailureHandler) HandleArgsForCall(i int) (context.Context, string, error) {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	argsForCall := fake.handleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FailureHandler) HandleReturns(result1 error) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = nil
	fake.handleReturns = struct {
		result1 error
	}{result1}
}

func (fake *FailureHandler) HandleReturnsOnCall(i int, result1 error) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = nil
	if fake.handleReturnsOnCall == nil {
		fake.handleReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.handleReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FailureHandler) NotifyFromReport(arg1 context.Context, arg2 string, arg3 string) {
	fake.notifyFromReportMutex.Lock()
	fake.notifyFromReportArgsForCall = append(fake.notifyFromReportArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.NotifyFromReportStub
	fake.recordInvocation("NotifyFromReport", []interface{}{arg1, arg2, arg3})
	fake.notifyFromReportMutex.Unlock()
	if stub != nil {
		fake.NotifyFromReportStub(arg1, arg2, arg3)
	}
}

func (fake *FailureHandler) NotifyFromReportCallCount() int {
	fake.notifyFromReportMutex.RLock()
	defer fake.notifyFromReportMutex.RUnlock()
	return len(fake.notifyFromReportArgsForCall)
}

func (fake *FailureHandler) NotifyFromReportCalls(stub func(context.Context, string, string)) {
	fake.notifyFromReportMutex.Lock()
	defer fake.notifyFromReportMutex.Unlock()
	fake.NotifyFromReportStub = stub
}

func (fake *FailureHandler) NotifyFromReportArgsForCall(i int) (context.Context, string, string) {
	fake.notifyFromReportMutex.RLock()
	defer fake.notifyFromReportMutex.RUnlock()
	argsForCall := fake.notifyFromReportArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FailureHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FailureHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ failurehandler.Handler = new(FailureHandler)
