// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/prompt"
)

type FileMover struct {
	MoveFileStub        func(context.Context, string, string) error
	moveFileMutex       sync.RWMutex
	moveFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	moveFileReturns struct {
		result1 error
	}
	moveFileReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FileMover) MoveFile(arg1 context.Context, arg2 string, arg3 string) error {
	fake.moveFileMutex.Lock()
	ret, specificReturn := fake.moveFileReturnsOnCall[len(fake.moveFileArgsForCall)]
	fake.moveFileArgsForCall = append(fake.moveFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.MoveFileStub
	fakeReturns := fake.moveFileReturns
	fake.recordInvocation("MoveFile", []interface{}{arg1, arg2, arg3})
	fake.moveFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FileMover) MoveFileCallCount() int {
	fake.moveFileMutex.RLock()
	defer fake.moveFileMutex.RUnlock()
	return len(fake.moveFileArgsForCall)
}

func (fake *FileMover) MoveFileCalls(stub func(context.Context, string, string) error) {
	fake.moveFileMutex.Lock()
	defer fake.moveFileMutex.Unlock()
	fake.MoveFileStub = stub
}

func (fake *FileMover) MoveFileArgsForCall(i int) (context.Context, string, string) {
	fake.moveFileMutex.RLock()
	defer fake.moveFileMutex.RUnlock()
	argsForCall := fake.moveFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FileMover) MoveFileReturns(result1 error) {
	fake.moveFileMutex.Lock()
	defer fake.moveFileMutex.Unlock()
	fake.MoveFileStub = nil
	fake.moveFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FileMover) MoveFileReturnsOnCall(i int, result1 error) {
	fake.moveFileMutex.Lock()
	defer fake.moveFileMutex.Unlock()
	fake.MoveFileStub = nil
	if fake.moveFileReturnsOnCall == nil {
		fake.moveFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.moveFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FileMover) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FileMover) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ prompt.FileMover = new(FileMover)
