// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"io"
	"sync"

	"github.com/bborbe/dark-factory/pkg/formatter"
)

type StreamFormatter struct {
	ProcessStreamStub        func(context.Context, io.Reader, io.Writer, io.Writer) error
	processStreamMutex       sync.RWMutex
	processStreamArgsForCall []struct {
		arg1 context.Context
		arg2 io.Reader
		arg3 io.Writer
		arg4 io.Writer
	}
	processStreamReturns struct {
		result1 error
	}
	processStreamReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *StreamFormatter) ProcessStream(arg1 context.Context, arg2 io.Reader, arg3 io.Writer, arg4 io.Writer) error {
	fake.processStreamMutex.Lock()
	ret, specificReturn := fake.processStreamReturnsOnCall[len(fake.processStreamArgsForCall)]
	fake.processStreamArgsForCall = append(fake.processStreamArgsForCall, struct {
		arg1 context.Context
		arg2 io.Reader
		arg3 io.Writer
		arg4 io.Writer
	}{arg1, arg2, arg3, arg4})
	stub := fake.ProcessStreamStub
	fakeReturns := fake.processStreamReturns
	fake.recordInvocation("ProcessStream", []interface{}{arg1, arg2, arg3, arg4})
	fake.processStreamMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *StreamFormatter) ProcessStreamCallCount() int {
	fake.processStreamMutex.RLock()
	defer fake.processStreamMutex.RUnlock()
	return len(fake.processStreamArgsForCall)
}

func (fake *StreamFormatter) ProcessStreamCalls(stub func(context.Context, io.Reader, io.Writer, io.Writer) error) {
	fake.processStreamMutex.Lock()
	defer fake.processStreamMutex.Unlock()
	fake.ProcessStreamStub = stub
}

func (fake *StreamFormatter) ProcessStreamArgsForCall(i int) (context.Context, io.Reader, io.Writer, io.Writer) {
	fake.processStreamMutex.RLock()
	defer fake.processStreamMutex.RUnlock()
	argsForCall := fake.processStreamArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *StreamFormatter) ProcessStreamReturns(result1 error) {
	fake.processStreamMutex.Lock()
	defer fake.processStreamMutex.Unlock()
	fake.ProcessStreamStub = nil
	fake.processStreamReturns = struct {
		result1 error
	}{result1}
}

func (fake *StreamFormatter) ProcessStreamReturnsOnCall(i int, result1 error) {
	fake.processStreamMutex.Lock()
	defer fake.processStreamMutex.Unlock()
	fake.ProcessStreamStub = nil
	if fake.processStreamReturnsOnCall == nil {
		fake.processStreamReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.processStreamReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *StreamFormatter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *StreamFormatter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ formatter.Formatter = new(StreamFormatter)
