// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"
	"time"

	"github.com/bborbe/dark-factory/pkg/healthcheckgate"
)

type HealthcheckGateCache struct {
	FreshStub        func(context.Context, string, time.Duration, time.Time) bool
	freshMutex       sync.RWMutex
	freshArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.Duration
		arg4 time.Time
	}
	freshReturns struct {
		result1 bool
	}
	freshReturnsOnCall map[int]struct {
		result1 bool
	}
	WriteStub        func(context.Context, string, time.Time)
	writeMutex       sync.RWMutex
	writeArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *HealthcheckGateCache) Fresh(arg1 context.Context, arg2 string, arg3 time.Duration, arg4 time.Time) bool {
	fake.freshMutex.Lock()
	ret, specificReturn := fake.freshReturnsOnCall[len(fake.freshArgsForCall)]
	fake.freshArgsForCall = append(fake.freshArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.Duration
		arg4 time.Time
	}{arg1, arg2, arg3, arg4})
	stub := fake.FreshStub
	fakeReturns := fake.freshReturns
	fake.recordInvocation("Fresh", []interface{}{arg1, arg2, arg3, arg4})
	fake.freshMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *HealthcheckGateCache) FreshCallCount() int {
	fake.freshMutex.RLock()
	defer fake.freshMutex.RUnlock()
	return len(fake.freshArgsForCall)
}

func (fake *HealthcheckGateCache) FreshCalls(stub func(context.Context, string, time.Duration, time.Time) bool) {
	fake.freshMutex.Lock()
	defer fake.freshMutex.Unlock()
	fake.FreshStub = stub
}

func (fake *HealthcheckGateCache) FreshArgsForCall(i int) (context.Context, string, time.Duration, time.Time) {
	fake.freshMutex.RLock()
	defer fake.freshMutex.RUnlock()
	argsForCall := fake.freshArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *HealthcheckGateCache) FreshReturns(result1 bool) {
	fake.freshMutex.Lock()
	defer fake.freshMutex.Unlock()
	fake.FreshStub = nil
	fake.freshReturns = struct {
		result1 bool
	}{result1}
}

func (fake *HealthcheckGateCache) FreshReturnsOnCall(i int, result1 bool) {
	fake.freshMutex.Lock()
	defer fake.freshMutex.Unlock()
	fake.FreshStub = nil
	if fake.freshReturnsOnCall == nil {
		fake.freshReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.freshReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *HealthcheckGateCache) Write(arg1 context.Context, arg2 string, arg3 time.Time) {
	fake.writeMutex.Lock()
	fake.writeArgsForCall = append(fake.writeArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
	}{arg1, arg2, arg3})
	stub := fake.WriteStub
	fake.recordInvocation("Write", []interface{}{arg1, arg2, arg3})
	fake.writeMutex.Unlock()
	if stub != nil {
		fake.WriteStub(arg1, arg2, arg3)
	}
}

func (fake *HealthcheckGateCache) WriteCallCount() int {
	fake.writeMutex.RLock()
	defer fake.writeMutex.RUnlock()
	return len(fake.writeArgsForCall)
}

func (fake *HealthcheckGateCache) WriteCalls(stub func(context.Context, string, time.Time)) {
	fake.writeMutex.Lock()
	defer fake.writeMutex.Unlock()
	fake.WriteStub = stub
}

func (fake *HealthcheckGateCache) WriteArgsForCall(i int) (context.Context, string, time.Time) {
	fake.writeMutex.RLock()
	defer fake.writeMutex.RUnlock()
	argsForCall := fake.writeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *HealthcheckGateCache) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *HealthcheckGateCache) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ healthcheckgate.Cache = new(HealthcheckGateCache)
