// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/git"
)

type PRCreator struct {
	CreateStub        func(context.Context, string, string) (string, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	createReturns struct {
		result1 string
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	FindOpenPRStub        func(context.Context, string) (string, error)
	findOpenPRMutex       sync.RWMutex
	findOpenPRArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	findOpenPRReturns struct {
		result1 string
		result2 error
	}
	findOpenPRReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PRCreator) Create(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2, arg3})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PRCreator) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *PRCreator) CreateCalls(stub func(context.Context, string, string) (string, error)) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *PRCreator) CreateArgsForCall(i int) (context.Context, string, string) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *PRCreator) CreateReturns(result1 string, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *PRCreator) CreateReturnsOnCall(i int, result1 string, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *PRCreator) FindOpenPR(arg1 context.Context, arg2 string) (string, error) {
	fake.findOpenPRMutex.Lock()
	ret, specificReturn := fake.findOpenPRReturnsOnCall[len(fake.findOpenPRArgsForCall)]
	fake.findOpenPRArgsForCall = append(fake.findOpenPRArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FindOpenPRStub
	fakeReturns := fake.findOpenPRReturns
	fake.recordInvocation("FindOpenPR", []interface{}{arg1, arg2})
	fake.findOpenPRMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PRCreator) FindOpenPRCallCount() int {
	fake.findOpenPRMutex.RLock()
	defer fake.findOpenPRMutex.RUnlock()
	return len(fake.findOpenPRArgsForCall)
}

func (fake *PRCreator) FindOpenPRCalls(stub func(context.Context, string) (string, error)) {
	fake.findOpenPRMutex.Lock()
	defer fake.findOpenPRMutex.Unlock()
	fake.FindOpenPRStub = stub
}

func (fake *PRCreator) FindOpenPRArgsForCall(i int) (context.Context, string) {
	fake.findOpenPRMutex.RLock()
	defer fake.findOpenPRMutex.RUnlock()
	argsForCall := fake.findOpenPRArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PRCreator) FindOpenPRReturns(result1 string, result2 error) {
	fake.findOpenPRMutex.Lock()
	defer fake.findOpenPRMutex.Unlock()
	fake.FindOpenPRStub = nil
	fake.findOpenPRReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *PRCreator) FindOpenPRReturnsOnCall(i int, result1 string, result2 error) {
	fake.findOpenPRMutex.Lock()
	defer fake.findOpenPRMutex.Unlock()
	fake.FindOpenPRStub = nil
	if fake.findOpenPRReturnsOnCall == nil {
		fake.findOpenPRReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.findOpenPRReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *PRCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PRCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ git.PRCreator = new(PRCreator)
