// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/git"
)

type PRMerger struct {
	WaitAndMergeStub        func(context.Context, string) error
	waitAndMergeMutex       sync.RWMutex
	waitAndMergeArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	waitAndMergeReturns struct {
		result1 error
	}
	waitAndMergeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PRMerger) WaitAndMerge(arg1 context.Context, arg2 string) error {
	fake.waitAndMergeMutex.Lock()
	ret, specificReturn := fake.waitAndMergeReturnsOnCall[len(fake.waitAndMergeArgsForCall)]
	fake.waitAndMergeArgsForCall = append(fake.waitAndMergeArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.WaitAndMergeStub
	fakeReturns := fake.waitAndMergeReturns
	fake.recordInvocation("WaitAndMerge", []interface{}{arg1, arg2})
	fake.waitAndMergeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PRMerger) WaitAndMergeCallCount() int {
	fake.waitAndMergeMutex.RLock()
	defer fake.waitAndMergeMutex.RUnlock()
	return len(fake.waitAndMergeArgsForCall)
}

func (fake *PRMerger) WaitAndMergeCalls(stub func(context.Context, string) error) {
	fake.waitAndMergeMutex.Lock()
	defer fake.waitAndMergeMutex.Unlock()
	fake.WaitAndMergeStub = stub
}

func (fake *PRMerger) WaitAndMergeArgsForCall(i int) (context.Context, string) {
	fake.waitAndMergeMutex.RLock()
	defer fake.waitAndMergeMutex.RUnlock()
	argsForCall := fake.waitAndMergeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PRMerger) WaitAndMergeReturns(result1 error) {
	fake.waitAndMergeMutex.Lock()
	defer fake.waitAndMergeMutex.Unlock()
	fake.WaitAndMergeStub = nil
	fake.waitAndMergeReturns = struct {
		result1 error
	}{result1}
}

func (fake *PRMerger) WaitAndMergeReturnsOnCall(i int, result1 error) {
	fake.waitAndMergeMutex.Lock()
	defer fake.waitAndMergeMutex.Unlock()
	fake.WaitAndMergeStub = nil
	if fake.waitAndMergeReturnsOnCall == nil {
		fake.waitAndMergeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.waitAndMergeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PRMerger) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PRMerger) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ git.PRMerger = new(PRMerger)
