// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/preflightconditions"
)

type Conditions struct {
	ShouldSkipStub        func(context.Context) (bool, error)
	shouldSkipMutex       sync.RWMutex
	shouldSkipArgsForCall []struct {
		arg1 context.Context
	}
	shouldSkipReturns struct {
		result1 bool
		result2 error
	}
	shouldSkipReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Conditions) ShouldSkip(arg1 context.Context) (bool, error) {
	fake.shouldSkipMutex.Lock()
	ret, specificReturn := fake.shouldSkipReturnsOnCall[len(fake.shouldSkipArgsForCall)]
	fake.shouldSkipArgsForCall = append(fake.shouldSkipArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ShouldSkipStub
	fakeReturns := fake.shouldSkipReturns
	fake.recordInvocation("ShouldSkip", []interface{}{arg1})
	fake.shouldSkipMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Conditions) ShouldSkipCallCount() int {
	fake.shouldSkipMutex.RLock()
	defer fake.shouldSkipMutex.RUnlock()
	return len(fake.shouldSkipArgsForCall)
}

func (fake *Conditions) ShouldSkipCalls(stub func(context.Context) (bool, error)) {
	fake.shouldSkipMutex.Lock()
	defer fake.shouldSkipMutex.Unlock()
	fake.ShouldSkipStub = stub
}

func (fake *Conditions) ShouldSkipArgsForCall(i int) context.Context {
	fake.shouldSkipMutex.RLock()
	defer fake.shouldSkipMutex.RUnlock()
	argsForCall := fake.shouldSkipArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Conditions) ShouldSkipReturns(result1 bool, result2 error) {
	fake.shouldSkipMutex.Lock()
	defer fake.shouldSkipMutex.Unlock()
	fake.ShouldSkipStub = nil
	fake.shouldSkipReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *Conditions) ShouldSkipReturnsOnCall(i int, result1 bool, result2 error) {
	fake.shouldSkipMutex.Lock()
	defer fake.shouldSkipMutex.Unlock()
	fake.ShouldSkipStub = nil
	if fake.shouldSkipReturnsOnCall == nil {
		fake.shouldSkipReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.shouldSkipReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *Conditions) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Conditions) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ preflightconditions.Conditions = new(Conditions)
