// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/processor"
	"github.com/bborbe/dark-factory/pkg/prompt"
)

type ProcessorPromptManager struct {
	AllPreviousCompletedStub        func(context.Context, int) bool
	allPreviousCompletedMutex       sync.RWMutex
	allPreviousCompletedArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	allPreviousCompletedReturns struct {
		result1 bool
	}
	allPreviousCompletedReturnsOnCall map[int]struct {
		result1 bool
	}
	FindMissingCompletedStub        func(context.Context, int) []int
	findMissingCompletedMutex       sync.RWMutex
	findMissingCompletedArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	findMissingCompletedReturns struct {
		result1 []int
	}
	findMissingCompletedReturnsOnCall map[int]struct {
		result1 []int
	}
	FindPromptStatusInProgressStub        func(context.Context, int) string
	findPromptStatusInProgressMutex       sync.RWMutex
	findPromptStatusInProgressArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	findPromptStatusInProgressReturns struct {
		result1 string
	}
	findPromptStatusInProgressReturnsOnCall map[int]struct {
		result1 string
	}
	HasQueuedPromptsOnBranchStub        func(context.Context, string, string) (bool, error)
	hasQueuedPromptsOnBranchMutex       sync.RWMutex
	hasQueuedPromptsOnBranchArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	hasQueuedPromptsOnBranchReturns struct {
		result1 bool
		result2 error
	}
	hasQueuedPromptsOnBranchReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	ListQueuedStub        func(context.Context) ([]prompt.Prompt, error)
	listQueuedMutex       sync.RWMutex
	listQueuedArgsForCall []struct {
		arg1 context.Context
	}
	listQueuedReturns struct {
		result1 []prompt.Prompt
		result2 error
	}
	listQueuedReturnsOnCall map[int]struct {
		result1 []prompt.Prompt
		result2 error
	}
	LoadStub        func(context.Context, string) (*prompt.PromptFile, error)
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	loadReturns struct {
		result1 *prompt.PromptFile
		result2 error
	}
	loadReturnsOnCall map[int]struct {
		result1 *prompt.PromptFile
		result2 error
	}
	MoveToCompletedStub        func(context.Context, string) error
	moveToCompletedMutex       sync.RWMutex
	moveToCompletedArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	moveToCompletedReturns struct {
		result1 error
	}
	moveToCompletedReturnsOnCall map[int]struct {
		result1 error
	}
	SetPRURLStub        func(context.Context, string, string) error
	setPRURLMutex       sync.RWMutex
	setPRURLArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	setPRURLReturns struct {
		result1 error
	}
	setPRURLReturnsOnCall map[int]struct {
		result1 error
	}
	SetStatusStub        func(context.Context, string, string) error
	setStatusMutex       sync.RWMutex
	setStatusArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	setStatusReturns struct {
		result1 error
	}
	setStatusReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ProcessorPromptManager) AllPreviousCompleted(arg1 context.Context, arg2 int) bool {
	fake.allPreviousCompletedMutex.Lock()
	ret, specificReturn := fake.allPreviousCompletedReturnsOnCall[len(fake.allPreviousCompletedArgsForCall)]
	fake.allPreviousCompletedArgsForCall = append(fake.allPreviousCompletedArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.AllPreviousCompletedStub
	fakeReturns := fake.allPreviousCompletedReturns
	fake.recordInvocation("AllPreviousCompleted", []interface{}{arg1, arg2})
	fake.allPreviousCompletedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ProcessorPromptManager) AllPreviousCompletedCallCount() int {
	fake.allPreviousCompletedMutex.RLock()
	defer fake.allPreviousCompletedMutex.RUnlock()
	return len(fake.allPreviousCompletedArgsForCall)
}

func (fake *ProcessorPromptManager) AllPreviousCompletedCalls(stub func(context.Context, int) bool) {
	fake.allPreviousCompletedMutex.Lock()
	defer fake.allPreviousCompletedMutex.Unlock()
	fake.AllPreviousCompletedStub = stub
}

func (fake *ProcessorPromptManager) AllPreviousCompletedArgsForCall(i int) (context.Context, int) {
	fake.allPreviousCompletedMutex.RLock()
	defer fake.allPreviousCompletedMutex.RUnlock()
	argsForCall := fake.allPreviousCompletedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ProcessorPromptManager) AllPreviousCompletedReturns(result1 bool) {
	fake.allPreviousCompletedMutex.Lock()
	defer fake.allPreviousCompletedMutex.Unlock()
	fake.AllPreviousCompletedStub = nil
	fake.allPreviousCompletedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *ProcessorPromptManager) AllPreviousCompletedReturnsOnCall(i int, result1 bool) {
	fake.allPreviousCompletedMutex.Lock()
	defer fake.allPreviousCompletedMutex.Unlock()
	fake.AllPreviousCompletedStub = nil
	if fake.allPreviousCompletedReturnsOnCall == nil {
		fake.allPreviousCompletedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.allPreviousCompletedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *ProcessorPromptManager) FindMissingCompleted(arg1 context.Context, arg2 int) []int {
	fake.findMissingCompletedMutex.Lock()
	ret, specificReturn := fake.findMissingCompletedReturnsOnCall[len(fake.findMissingCompletedArgsForCall)]
	fake.findMissingCompletedArgsForCall = append(fake.findMissingCompletedArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.FindMissingCompletedStub
	fakeReturns := fake.findMissingCompletedReturns
	fake.recordInvocation("FindMissingCompleted", []interface{}{arg1, arg2})
	fake.findMissingCompletedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ProcessorPromptManager) FindMissingCompletedCallCount() int {
	fake.findMissingCompletedMutex.RLock()
	defer fake.findMissingCompletedMutex.RUnlock()
	return len(fake.findMissingCompletedArgsForCall)
}

func (fake *ProcessorPromptManager) FindMissingCompletedCalls(stub func(context.Context, int) []int) {
	fake.findMissingCompletedMutex.Lock()
	defer fake.findMissingCompletedMutex.Unlock()
	fake.FindMissingCompletedStub = stub
}

func (fake *ProcessorPromptManager) FindMissingCompletedArgsForCall(i int) (context.Context, int) {
	fake.findMissingCompletedMutex.RLock()
	defer fake.findMissingCompletedMutex.RUnlock()
	argsForCall := fake.findMissingCompletedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ProcessorPromptManager) FindMissingCompletedReturns(result1 []int) {
	fake.findMissingCompletedMutex.Lock()
	defer fake.findMissingCompletedMutex.Unlock()
	fake.FindMissingCompletedStub = nil
	fake.findMissingCompletedReturns = struct {
		result1 []int
	}{result1}
}

func (fake *ProcessorPromptManager) FindMissingCompletedReturnsOnCall(i int, result1 []int) {
	fake.findMissingCompletedMutex.Lock()
	defer fake.findMissingCompletedMutex.Unlock()
	fake.FindMissingCompletedStub = nil
	if fake.findMissingCompletedReturnsOnCall == nil {
		fake.findMissingCompletedReturnsOnCall = make(map[int]struct {
			result1 []int
		})
	}
	fake.findMissingCompletedReturnsOnCall[i] = struct {
		result1 []int
	}{result1}
}

func (fake *ProcessorPromptManager) FindPromptStatusInProgress(arg1 context.Context, arg2 int) string {
	fake.findPromptStatusInProgressMutex.Lock()
	ret, specificReturn := fake.findPromptStatusInProgressReturnsOnCall[len(fake.findPromptStatusInProgressArgsForCall)]
	fake.findPromptStatusInProgressArgsForCall = append(fake.findPromptStatusInProgressArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.FindPromptStatusInProgressStub
	fakeReturns := fake.findPromptStatusInProgressReturns
	fake.recordInvocation("FindPromptStatusInProgress", []interface{}{arg1, arg2})
	fake.findPromptStatusInProgressMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ProcessorPromptManager) FindPromptStatusInProgressCallCount() int {
	fake.findPromptStatusInProgressMutex.RLock()
	defer fake.findPromptStatusInProgressMutex.RUnlock()
	return len(fake.findPromptStatusInProgressArgsForCall)
}

func (fake *ProcessorPromptManager) FindPromptStatusInProgressCalls(stub func(context.Context, int) string) {
	fake.findPromptStatusInProgressMutex.Lock()
	defer fake.findPromptStatusInProgressMutex.Unlock()
	fake.FindPromptStatusInProgressStub = stub
}

func (fake *ProcessorPromptManager) FindPromptStatusInProgressArgsForCall(i int) (context.Context, int) {
	fake.findPromptStatusInProgressMutex.RLock()
	defer fake.findPromptStatusInProgressMutex.RUnlock()
	argsForCall := fake.findPromptStatusInProgressArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ProcessorPromptManager) FindPromptStatusInProgressReturns(result1 string) {
	fake.findPromptStatusInProgressMutex.Lock()
	defer fake.findPromptStatusInProgressMutex.Unlock()
	fake.FindPromptStatusInProgressStub = nil
	fake.findPromptStatusInProgressReturns = struct {
		result1 string
	}{result1}
}

func (fake *ProcessorPromptManager) FindPromptStatusInProgressReturnsOnCall(i int, result1 string) {
	fake.findPromptStatusInProgressMutex.Lock()
	defer fake.findPromptStatusInProgressMutex.Unlock()
	fake.FindPromptStatusInProgressStub = nil
	if fake.findPromptStatusInProgressReturnsOnCall == nil {
		fake.findPromptStatusInProgressReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.findPromptStatusInProgressReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *ProcessorPromptManager) HasQueuedPromptsOnBranch(arg1 context.Context, arg2 string, arg3 string) (bool, error) {
	fake.hasQueuedPromptsOnBranchMutex.Lock()
	ret, specificReturn := fake.hasQueuedPromptsOnBranchReturnsOnCall[len(fake.hasQueuedPromptsOnBranchArgsForCall)]
	fake.hasQueuedPromptsOnBranchArgsForCall = append(fake.hasQueuedPromptsOnBranchArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.HasQueuedPromptsOnBranchStub
	fakeReturns := fake.hasQueuedPromptsOnBranchReturns
	fake.recordInvocation("HasQueuedPromptsOnBranch", []interface{}{arg1, arg2, arg3})
	fake.hasQueuedPromptsOnBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ProcessorPromptManager) HasQueuedPromptsOnBranchCallCount() int {
	fake.hasQueuedPromptsOnBranchMutex.RLock()
	defer fake.hasQueuedPromptsOnBranchMutex.RUnlock()
	return len(fake.hasQueuedPromptsOnBranchArgsForCall)
}

func (fake *ProcessorPromptManager) HasQueuedPromptsOnBranchCalls(stub func(context.Context, string, string) (bool, error)) {
	fake.hasQueuedPromptsOnBranchMutex.Lock()
	defer fake.hasQueuedPromptsOnBranchMutex.Unlock()
	fake.HasQueuedPromptsOnBranchStub = stub
}

func (fake *ProcessorPromptManager) HasQueuedPromptsOnBranchArgsForCall(i int) (context.Context, string, string) {
	fake.hasQueuedPromptsOnBranchMutex.RLock()
	defer fake.hasQueuedPromptsOnBranchMutex.RUnlock()
	argsForCall := fake.hasQueuedPromptsOnBranchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ProcessorPromptManager) HasQueuedPromptsOnBranchReturns(result1 bool, result2 error) {
	fake.hasQueuedPromptsOnBranchMutex.Lock()
	defer fake.hasQueuedPromptsOnBranchMutex.Unlock()
	fake.HasQueuedPromptsOnBranchStub = nil
	fake.hasQueuedPromptsOnBranchReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *ProcessorPromptManager) HasQueuedPromptsOnBranchReturnsOnCall(i int, result1 bool, result2 error) {
	fake.hasQueuedPromptsOnBranchMutex.Lock()
	defer fake.hasQueuedPromptsOnBranchMutex.Unlock()
	fake.HasQueuedPromptsOnBranchStub = nil
	if fake.hasQueuedPromptsOnBranchReturnsOnCall == nil {
		fake.hasQueuedPromptsOnBranchReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.hasQueuedPromptsOnBranchReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *ProcessorPromptManager) ListQueued(arg1 context.Context) ([]prompt.Prompt, error) {
	fake.listQueuedMutex.Lock()
	ret, specificReturn := fake.listQueuedReturnsOnCall[len(fake.listQueuedArgsForCall)]
	fake.listQueuedArgsForCall = append(fake.listQueuedArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListQueuedStub
	fakeReturns := fake.listQueuedReturns
	fake.recordInvocation("ListQueued", []interface{}{arg1})
	fake.listQueuedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ProcessorPromptManager) ListQueuedCallCount() int {
	fake.listQueuedMutex.RLock()
	defer fake.listQueuedMutex.RUnlock()
	return len(fake.listQueuedArgsForCall)
}

func (fake *ProcessorPromptManager) ListQueuedCalls(stub func(context.Context) ([]prompt.Prompt, error)) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = stub
}

func (fake *ProcessorPromptManager) ListQueuedArgsForCall(i int) context.Context {
	fake.listQueuedMutex.RLock()
	defer fake.listQueuedMutex.RUnlock()
	argsForCall := fake.listQueuedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ProcessorPromptManager) ListQueuedReturns(result1 []prompt.Prompt, result2 error) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = nil
	fake.listQueuedReturns = struct {
		result1 []prompt.Prompt
		result2 error
	}{result1, result2}
}

func (fake *ProcessorPromptManager) ListQueuedReturnsOnCall(i int, result1 []prompt.Prompt, result2 error) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = nil
	if fake.listQueuedReturnsOnCall == nil {
		fake.listQueuedReturnsOnCall = make(map[int]struct {
			result1 []prompt.Prompt
			result2 error
		})
	}
	fake.listQueuedReturnsOnCall[i] = struct {
		result1 []prompt.Prompt
		result2 error
	}{result1, result2}
}

func (fake *ProcessorPromptManager) Load(arg1 context.Context, arg2 string) (*prompt.PromptFile, error) {
	fake.loadMutex.Lock()
	ret, specificReturn := fake.loadReturnsOnCall[len(fake.loadArgsForCall)]
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LoadStub
	fakeReturns := fake.loadReturns
	fake.recordInvocation("Load", []interface{}{arg1, arg2})
	fake.loadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ProcessorPromptManager) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *ProcessorPromptManager) LoadCalls(stub func(context.Context, string) (*prompt.PromptFile, error)) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = stub
}

func (fake *ProcessorPromptManager) LoadArgsForCall(i int) (context.Context, string) {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	argsForCall := fake.loadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ProcessorPromptManager) LoadReturns(result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *ProcessorPromptManager) LoadReturnsOnCall(i int, result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	if fake.loadReturnsOnCall == nil {
		fake.loadReturnsOnCall = make(map[int]struct {
			result1 *prompt.PromptFile
			result2 error
		})
	}
	fake.loadReturnsOnCall[i] = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *ProcessorPromptManager) MoveToCompleted(arg1 context.Context, arg2 string) error {
	fake.moveToCompletedMutex.Lock()
	ret, specificReturn := fake.moveToCompletedReturnsOnCall[len(fake.moveToCompletedArgsForCall)]
	fake.moveToCompletedArgsForCall = append(fake.moveToCompletedArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.MoveToCompletedStub
	fakeReturns := fake.moveToCompletedReturns
	fake.recordInvocation("MoveToCompleted", []interface{}{arg1, arg2})
	fake.moveToCompletedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ProcessorPromptManager) MoveToCompletedCallCount() int {
	fake.moveToCompletedMutex.RLock()
	defer fake.moveToCompletedMutex.RUnlock()
	return len(fake.moveToCompletedArgsForCall)
}

func (fake *ProcessorPromptManager) MoveToCompletedCalls(stub func(context.Context, string) error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = stub
}

func (fake *ProcessorPromptManager) MoveToCompletedArgsForCall(i int) (context.Context, string) {
	fake.moveToCompletedMutex.RLock()
	defer fake.moveToCompletedMutex.RUnlock()
	argsForCall := fake.moveToCompletedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ProcessorPromptManager) MoveToCompletedReturns(result1 error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = nil
	fake.moveToCompletedReturns = struct {
		result1 error
	}{result1}
}

func (fake *ProcessorPromptManager) MoveToCompletedReturnsOnCall(i int, result1 error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = nil
	if fake.moveToCompletedReturnsOnCall == nil {
		fake.moveToCompletedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.moveToCompletedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ProcessorPromptManager) SetPRURL(arg1 context.Context, arg2 string, arg3 string) error {
	fake.setPRURLMutex.Lock()
	ret, specificReturn := fake.setPRURLReturnsOnCall[len(fake.setPRURLArgsForCall)]
	fake.setPRURLArgsForCall = append(fake.setPRURLArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SetPRURLStub
	fakeReturns := fake.setPRURLReturns
	fake.recordInvocation("SetPRURL", []interface{}{arg1, arg2, arg3})
	fake.setPRURLMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ProcessorPromptManager) SetPRURLCallCount() int {
	fake.setPRURLMutex.RLock()
	defer fake.setPRURLMutex.RUnlock()
	return len(fake.setPRURLArgsForCall)
}

func (fake *ProcessorPromptManager) SetPRURLCalls(stub func(context.Context, string, string) error) {
	fake.setPRURLMutex.Lock()
	defer fake.setPRURLMutex.Unlock()
	fake.SetPRURLStub = stub
}

func (fake *ProcessorPromptManager) SetPRURLArgsForCall(i int) (context.Context, string, string) {
	fake.setPRURLMutex.RLock()
	defer fake.setPRURLMutex.RUnlock()
	argsForCall := fake.setPRURLArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ProcessorPromptManager) SetPRURLReturns(result1 error) {
	fake.setPRURLMutex.Lock()
	defer fake.setPRURLMutex.Unlock()
	fake.SetPRURLStub = nil
	fake.setPRURLReturns = struct {
		result1 error
	}{result1}
}

func (fake *ProcessorPromptManager) SetPRURLReturnsOnCall(i int, result1 error) {
	fake.setPRURLMutex.Lock()
	defer fake.setPRURLMutex.Unlock()
	fake.SetPRURLStub = nil
	if fake.setPRURLReturnsOnCall == nil {
		fake.setPRURLReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setPRURLReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ProcessorPromptManager) SetStatus(arg1 context.Context, arg2 string, arg3 string) error {
	fake.setStatusMutex.Lock()
	ret, specificReturn := fake.setStatusReturnsOnCall[len(fake.setStatusArgsForCall)]
	fake.setStatusArgsForCall = append(fake.setStatusArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SetStatusStub
	fakeReturns := fake.setStatusReturns
	fake.recordInvocation("SetStatus", []interface{}{arg1, arg2, arg3})
	fake.setStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ProcessorPromptManager) SetStatusCallCount() int {
	fake.setStatusMutex.RLock()
	defer fake.setStatusMutex.RUnlock()
	return len(fake.setStatusArgsForCall)
}

func (fake *ProcessorPromptManager) SetStatusCalls(stub func(context.Context, string, string) error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = stub
}

func (fake *ProcessorPromptManager) SetStatusArgsForCall(i int) (context.Context, string, string) {
	fake.setStatusMutex.RLock()
	defer fake.setStatusMutex.RUnlock()
	argsForCall := fake.setStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ProcessorPromptManager) SetStatusReturns(result1 error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = nil
	fake.setStatusReturns = struct {
		result1 error
	}{result1}
}

func (fake *ProcessorPromptManager) SetStatusReturnsOnCall(i int, result1 error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = nil
	if fake.setStatusReturnsOnCall == nil {
		fake.setStatusReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setStatusReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ProcessorPromptManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ProcessorPromptManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ processor.PromptManager = new(ProcessorPromptManager)
