// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/processor"
)

type Processor struct {
	ProcessStub        func(context.Context) error
	processMutex       sync.RWMutex
	processArgsForCall []struct {
		arg1 context.Context
	}
	processReturns struct {
		result1 error
	}
	processReturnsOnCall map[int]struct {
		result1 error
	}
	ResumeCommittingStub        func(context.Context) error
	resumeCommittingMutex       sync.RWMutex
	resumeCommittingArgsForCall []struct {
		arg1 context.Context
	}
	resumeCommittingReturns struct {
		result1 error
	}
	resumeCommittingReturnsOnCall map[int]struct {
		result1 error
	}
	ResumeExecutingStub        func(context.Context) error
	resumeExecutingMutex       sync.RWMutex
	resumeExecutingArgsForCall []struct {
		arg1 context.Context
	}
	resumeExecutingReturns struct {
		result1 error
	}
	resumeExecutingReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Processor) Process(arg1 context.Context) error {
	fake.processMutex.Lock()
	ret, specificReturn := fake.processReturnsOnCall[len(fake.processArgsForCall)]
	fake.processArgsForCall = append(fake.processArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ProcessStub
	fakeReturns := fake.processReturns
	fake.recordInvocation("Process", []interface{}{arg1})
	fake.processMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Processor) ProcessCallCount() int {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	return len(fake.processArgsForCall)
}

func (fake *Processor) ProcessCalls(stub func(context.Context) error) {
	fake.processMutex.Lock()
	defer fake.processMutex.Unlock()
	fake.ProcessStub = stub
}

func (fake *Processor) ProcessArgsForCall(i int) context.Context {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	argsForCall := fake.processArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Processor) ProcessReturns(result1 error) {
	fake.processMutex.Lock()
	defer fake.processMutex.Unlock()
	fake.ProcessStub = nil
	fake.processReturns = struct {
		result1 error
	}{result1}
}

func (fake *Processor) ProcessReturnsOnCall(i int, result1 error) {
	fake.processMutex.Lock()
	defer fake.processMutex.Unlock()
	fake.ProcessStub = nil
	if fake.processReturnsOnCall == nil {
		fake.processReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.processReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Processor) ResumeCommitting(arg1 context.Context) error {
	fake.resumeCommittingMutex.Lock()
	ret, specificReturn := fake.resumeCommittingReturnsOnCall[len(fake.resumeCommittingArgsForCall)]
	fake.resumeCommittingArgsForCall = append(fake.resumeCommittingArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ResumeCommittingStub
	fakeReturns := fake.resumeCommittingReturns
	fake.recordInvocation("ResumeCommitting", []interface{}{arg1})
	fake.resumeCommittingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Processor) ResumeCommittingCallCount() int {
	fake.resumeCommittingMutex.RLock()
	defer fake.resumeCommittingMutex.RUnlock()
	return len(fake.resumeCommittingArgsForCall)
}

func (fake *Processor) ResumeCommittingCalls(stub func(context.Context) error) {
	fake.resumeCommittingMutex.Lock()
	defer fake.resumeCommittingMutex.Unlock()
	fake.ResumeCommittingStub = stub
}

func (fake *Processor) ResumeCommittingArgsForCall(i int) context.Context {
	fake.resumeCommittingMutex.RLock()
	defer fake.resumeCommittingMutex.RUnlock()
	argsForCall := fake.resumeCommittingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Processor) ResumeCommittingReturns(result1 error) {
	fake.resumeCommittingMutex.Lock()
	defer fake.resumeCommittingMutex.Unlock()
	fake.ResumeCommittingStub = nil
	fake.resumeCommittingReturns = struct {
		result1 error
	}{result1}
}

func (fake *Processor) ResumeCommittingReturnsOnCall(i int, result1 error) {
	fake.resumeCommittingMutex.Lock()
	defer fake.resumeCommittingMutex.Unlock()
	fake.ResumeCommittingStub = nil
	if fake.resumeCommittingReturnsOnCall == nil {
		fake.resumeCommittingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resumeCommittingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Processor) ResumeExecuting(arg1 context.Context) error {
	fake.resumeExecutingMutex.Lock()
	ret, specificReturn := fake.resumeExecutingReturnsOnCall[len(fake.resumeExecutingArgsForCall)]
	fake.resumeExecutingArgsForCall = append(fake.resumeExecutingArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ResumeExecutingStub
	fakeReturns := fake.resumeExecutingReturns
	fake.recordInvocation("ResumeExecuting", []interface{}{arg1})
	fake.resumeExecutingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Processor) ResumeExecutingCallCount() int {
	fake.resumeExecutingMutex.RLock()
	defer fake.resumeExecutingMutex.RUnlock()
	return len(fake.resumeExecutingArgsForCall)
}

func (fake *Processor) ResumeExecutingCalls(stub func(context.Context) error) {
	fake.resumeExecutingMutex.Lock()
	defer fake.resumeExecutingMutex.Unlock()
	fake.ResumeExecutingStub = stub
}

func (fake *Processor) ResumeExecutingArgsForCall(i int) context.Context {
	fake.resumeExecutingMutex.RLock()
	defer fake.resumeExecutingMutex.RUnlock()
	argsForCall := fake.resumeExecutingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Processor) ResumeExecutingReturns(result1 error) {
	fake.resumeExecutingMutex.Lock()
	defer fake.resumeExecutingMutex.Unlock()
	fake.ResumeExecutingStub = nil
	fake.resumeExecutingReturns = struct {
		result1 error
	}{result1}
}

func (fake *Processor) ResumeExecutingReturnsOnCall(i int, result1 error) {
	fake.resumeExecutingMutex.Lock()
	defer fake.resumeExecutingMutex.Unlock()
	fake.ResumeExecutingStub = nil
	if fake.resumeExecutingReturnsOnCall == nil {
		fake.resumeExecutingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resumeExecutingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Processor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Processor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ processor.Processor = new(Processor)
