// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/processor"
)

type Processor struct {
	ProcessStub        func(context.Context) error
	processMutex       sync.RWMutex
	processArgsForCall []struct {
		arg1 context.Context
	}
	processReturns struct {
		result1 error
	}
	processReturnsOnCall map[int]struct {
		result1 error
	}
	ProcessQueueStub        func(context.Context) error
	processQueueMutex       sync.RWMutex
	processQueueArgsForCall []struct {
		arg1 context.Context
	}
	processQueueReturns struct {
		result1 error
	}
	processQueueReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Processor) Process(arg1 context.Context) error {
	fake.processMutex.Lock()
	ret, specificReturn := fake.processReturnsOnCall[len(fake.processArgsForCall)]
	fake.processArgsForCall = append(fake.processArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ProcessStub
	fakeReturns := fake.processReturns
	fake.recordInvocation("Process", []interface{}{arg1})
	fake.processMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Processor) ProcessCallCount() int {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	return len(fake.processArgsForCall)
}

func (fake *Processor) ProcessCalls(stub func(context.Context) error) {
	fake.processMutex.Lock()
	defer fake.processMutex.Unlock()
	fake.ProcessStub = stub
}

func (fake *Processor) ProcessArgsForCall(i int) context.Context {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	argsForCall := fake.processArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Processor) ProcessReturns(result1 error) {
	fake.processMutex.Lock()
	defer fake.processMutex.Unlock()
	fake.ProcessStub = nil
	fake.processReturns = struct {
		result1 error
	}{result1}
}

func (fake *Processor) ProcessReturnsOnCall(i int, result1 error) {
	fake.processMutex.Lock()
	defer fake.processMutex.Unlock()
	fake.ProcessStub = nil
	if fake.processReturnsOnCall == nil {
		fake.processReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.processReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Processor) ProcessQueue(arg1 context.Context) error {
	fake.processQueueMutex.Lock()
	ret, specificReturn := fake.processQueueReturnsOnCall[len(fake.processQueueArgsForCall)]
	fake.processQueueArgsForCall = append(fake.processQueueArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ProcessQueueStub
	fakeReturns := fake.processQueueReturns
	fake.recordInvocation("ProcessQueue", []interface{}{arg1})
	fake.processQueueMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Processor) ProcessQueueCallCount() int {
	fake.processQueueMutex.RLock()
	defer fake.processQueueMutex.RUnlock()
	return len(fake.processQueueArgsForCall)
}

func (fake *Processor) ProcessQueueCalls(stub func(context.Context) error) {
	fake.processQueueMutex.Lock()
	defer fake.processQueueMutex.Unlock()
	fake.ProcessQueueStub = stub
}

func (fake *Processor) ProcessQueueArgsForCall(i int) context.Context {
	fake.processQueueMutex.RLock()
	defer fake.processQueueMutex.RUnlock()
	argsForCall := fake.processQueueArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Processor) ProcessQueueReturns(result1 error) {
	fake.processQueueMutex.Lock()
	defer fake.processQueueMutex.Unlock()
	fake.ProcessQueueStub = nil
	fake.processQueueReturns = struct {
		result1 error
	}{result1}
}

func (fake *Processor) ProcessQueueReturnsOnCall(i int, result1 error) {
	fake.processQueueMutex.Lock()
	defer fake.processQueueMutex.Unlock()
	fake.ProcessQueueStub = nil
	if fake.processQueueReturnsOnCall == nil {
		fake.processQueueReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.processQueueReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Processor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Processor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ processor.Processor = new(Processor)
