// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/promptenricher"
)

type PromptEnricher struct {
	EnrichStub        func(context.Context, string) string
	enrichMutex       sync.RWMutex
	enrichArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	enrichReturns struct {
		result1 string
	}
	enrichReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PromptEnricher) Enrich(arg1 context.Context, arg2 string) string {
	fake.enrichMutex.Lock()
	ret, specificReturn := fake.enrichReturnsOnCall[len(fake.enrichArgsForCall)]
	fake.enrichArgsForCall = append(fake.enrichArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.EnrichStub
	fakeReturns := fake.enrichReturns
	fake.recordInvocation("Enrich", []interface{}{arg1, arg2})
	fake.enrichMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PromptEnricher) EnrichCallCount() int {
	fake.enrichMutex.RLock()
	defer fake.enrichMutex.RUnlock()
	return len(fake.enrichArgsForCall)
}

func (fake *PromptEnricher) EnrichCalls(stub func(context.Context, string) string) {
	fake.enrichMutex.Lock()
	defer fake.enrichMutex.Unlock()
	fake.EnrichStub = stub
}

func (fake *PromptEnricher) EnrichArgsForCall(i int) (context.Context, string) {
	fake.enrichMutex.RLock()
	defer fake.enrichMutex.RUnlock()
	argsForCall := fake.enrichArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PromptEnricher) EnrichReturns(result1 string) {
	fake.enrichMutex.Lock()
	defer fake.enrichMutex.Unlock()
	fake.EnrichStub = nil
	fake.enrichReturns = struct {
		result1 string
	}{result1}
}

func (fake *PromptEnricher) EnrichReturnsOnCall(i int, result1 string) {
	fake.enrichMutex.Lock()
	defer fake.enrichMutex.Unlock()
	fake.EnrichStub = nil
	if fake.enrichReturnsOnCall == nil {
		fake.enrichReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.enrichReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *PromptEnricher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PromptEnricher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ promptenricher.Enricher = new(PromptEnricher)
