// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/promptresumer"
)

type Resumer struct {
	ResumeAllStub        func(context.Context) error
	resumeAllMutex       sync.RWMutex
	resumeAllArgsForCall []struct {
		arg1 context.Context
	}
	resumeAllReturns struct {
		result1 error
	}
	resumeAllReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Resumer) ResumeAll(arg1 context.Context) error {
	fake.resumeAllMutex.Lock()
	ret, specificReturn := fake.resumeAllReturnsOnCall[len(fake.resumeAllArgsForCall)]
	fake.resumeAllArgsForCall = append(fake.resumeAllArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ResumeAllStub
	fakeReturns := fake.resumeAllReturns
	fake.recordInvocation("ResumeAll", []interface{}{arg1})
	fake.resumeAllMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Resumer) ResumeAllCallCount() int {
	fake.resumeAllMutex.RLock()
	defer fake.resumeAllMutex.RUnlock()
	return len(fake.resumeAllArgsForCall)
}

func (fake *Resumer) ResumeAllCalls(stub func(context.Context) error) {
	fake.resumeAllMutex.Lock()
	defer fake.resumeAllMutex.Unlock()
	fake.ResumeAllStub = stub
}

func (fake *Resumer) ResumeAllArgsForCall(i int) context.Context {
	fake.resumeAllMutex.RLock()
	defer fake.resumeAllMutex.RUnlock()
	argsForCall := fake.resumeAllArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Resumer) ResumeAllReturns(result1 error) {
	fake.resumeAllMutex.Lock()
	defer fake.resumeAllMutex.Unlock()
	fake.ResumeAllStub = nil
	fake.resumeAllReturns = struct {
		result1 error
	}{result1}
}

func (fake *Resumer) ResumeAllReturnsOnCall(i int, result1 error) {
	fake.resumeAllMutex.Lock()
	defer fake.resumeAllMutex.Unlock()
	fake.ResumeAllStub = nil
	if fake.resumeAllReturnsOnCall == nil {
		fake.resumeAllReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resumeAllReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Resumer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Resumer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ promptresumer.Resumer = new(Resumer)
