// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/prompt"
)

type Manager struct {
	ContentStub        func(context.Context, string) (string, error)
	contentMutex       sync.RWMutex
	contentArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	contentReturns struct {
		result1 string
		result2 error
	}
	contentReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	HasExecutingStub        func(context.Context) bool
	hasExecutingMutex       sync.RWMutex
	hasExecutingArgsForCall []struct {
		arg1 context.Context
	}
	hasExecutingReturns struct {
		result1 bool
	}
	hasExecutingReturnsOnCall map[int]struct {
		result1 bool
	}
	ListQueuedStub        func(context.Context) ([]prompt.Prompt, error)
	listQueuedMutex       sync.RWMutex
	listQueuedArgsForCall []struct {
		arg1 context.Context
	}
	listQueuedReturns struct {
		result1 []prompt.Prompt
		result2 error
	}
	listQueuedReturnsOnCall map[int]struct {
		result1 []prompt.Prompt
		result2 error
	}
	MoveToCompletedStub        func(context.Context, string) error
	moveToCompletedMutex       sync.RWMutex
	moveToCompletedArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	moveToCompletedReturns struct {
		result1 error
	}
	moveToCompletedReturnsOnCall map[int]struct {
		result1 error
	}
	NormalizeFilenamesStub        func(context.Context) ([]prompt.Rename, error)
	normalizeFilenamesMutex       sync.RWMutex
	normalizeFilenamesArgsForCall []struct {
		arg1 context.Context
	}
	normalizeFilenamesReturns struct {
		result1 []prompt.Rename
		result2 error
	}
	normalizeFilenamesReturnsOnCall map[int]struct {
		result1 []prompt.Rename
		result2 error
	}
	ReadFrontmatterStub        func(context.Context, string) (*prompt.Frontmatter, error)
	readFrontmatterMutex       sync.RWMutex
	readFrontmatterArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	readFrontmatterReturns struct {
		result1 *prompt.Frontmatter
		result2 error
	}
	readFrontmatterReturnsOnCall map[int]struct {
		result1 *prompt.Frontmatter
		result2 error
	}
	ResetExecutingStub        func(context.Context) error
	resetExecutingMutex       sync.RWMutex
	resetExecutingArgsForCall []struct {
		arg1 context.Context
	}
	resetExecutingReturns struct {
		result1 error
	}
	resetExecutingReturnsOnCall map[int]struct {
		result1 error
	}
	SetContainerStub        func(context.Context, string, string) error
	setContainerMutex       sync.RWMutex
	setContainerArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	setContainerReturns struct {
		result1 error
	}
	setContainerReturnsOnCall map[int]struct {
		result1 error
	}
	SetStatusStub        func(context.Context, string, string) error
	setStatusMutex       sync.RWMutex
	setStatusArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	setStatusReturns struct {
		result1 error
	}
	setStatusReturnsOnCall map[int]struct {
		result1 error
	}
	TitleStub        func(context.Context, string) (string, error)
	titleMutex       sync.RWMutex
	titleArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	titleReturns struct {
		result1 string
		result2 error
	}
	titleReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Manager) Content(arg1 context.Context, arg2 string) (string, error) {
	fake.contentMutex.Lock()
	ret, specificReturn := fake.contentReturnsOnCall[len(fake.contentArgsForCall)]
	fake.contentArgsForCall = append(fake.contentArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ContentStub
	fakeReturns := fake.contentReturns
	fake.recordInvocation("Content", []interface{}{arg1, arg2})
	fake.contentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Manager) ContentCallCount() int {
	fake.contentMutex.RLock()
	defer fake.contentMutex.RUnlock()
	return len(fake.contentArgsForCall)
}

func (fake *Manager) ContentCalls(stub func(context.Context, string) (string, error)) {
	fake.contentMutex.Lock()
	defer fake.contentMutex.Unlock()
	fake.ContentStub = stub
}

func (fake *Manager) ContentArgsForCall(i int) (context.Context, string) {
	fake.contentMutex.RLock()
	defer fake.contentMutex.RUnlock()
	argsForCall := fake.contentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Manager) ContentReturns(result1 string, result2 error) {
	fake.contentMutex.Lock()
	defer fake.contentMutex.Unlock()
	fake.ContentStub = nil
	fake.contentReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Manager) ContentReturnsOnCall(i int, result1 string, result2 error) {
	fake.contentMutex.Lock()
	defer fake.contentMutex.Unlock()
	fake.ContentStub = nil
	if fake.contentReturnsOnCall == nil {
		fake.contentReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.contentReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Manager) HasExecuting(arg1 context.Context) bool {
	fake.hasExecutingMutex.Lock()
	ret, specificReturn := fake.hasExecutingReturnsOnCall[len(fake.hasExecutingArgsForCall)]
	fake.hasExecutingArgsForCall = append(fake.hasExecutingArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.HasExecutingStub
	fakeReturns := fake.hasExecutingReturns
	fake.recordInvocation("HasExecuting", []interface{}{arg1})
	fake.hasExecutingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Manager) HasExecutingCallCount() int {
	fake.hasExecutingMutex.RLock()
	defer fake.hasExecutingMutex.RUnlock()
	return len(fake.hasExecutingArgsForCall)
}

func (fake *Manager) HasExecutingCalls(stub func(context.Context) bool) {
	fake.hasExecutingMutex.Lock()
	defer fake.hasExecutingMutex.Unlock()
	fake.HasExecutingStub = stub
}

func (fake *Manager) HasExecutingArgsForCall(i int) context.Context {
	fake.hasExecutingMutex.RLock()
	defer fake.hasExecutingMutex.RUnlock()
	argsForCall := fake.hasExecutingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Manager) HasExecutingReturns(result1 bool) {
	fake.hasExecutingMutex.Lock()
	defer fake.hasExecutingMutex.Unlock()
	fake.HasExecutingStub = nil
	fake.hasExecutingReturns = struct {
		result1 bool
	}{result1}
}

func (fake *Manager) HasExecutingReturnsOnCall(i int, result1 bool) {
	fake.hasExecutingMutex.Lock()
	defer fake.hasExecutingMutex.Unlock()
	fake.HasExecutingStub = nil
	if fake.hasExecutingReturnsOnCall == nil {
		fake.hasExecutingReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.hasExecutingReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *Manager) ListQueued(arg1 context.Context) ([]prompt.Prompt, error) {
	fake.listQueuedMutex.Lock()
	ret, specificReturn := fake.listQueuedReturnsOnCall[len(fake.listQueuedArgsForCall)]
	fake.listQueuedArgsForCall = append(fake.listQueuedArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListQueuedStub
	fakeReturns := fake.listQueuedReturns
	fake.recordInvocation("ListQueued", []interface{}{arg1})
	fake.listQueuedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Manager) ListQueuedCallCount() int {
	fake.listQueuedMutex.RLock()
	defer fake.listQueuedMutex.RUnlock()
	return len(fake.listQueuedArgsForCall)
}

func (fake *Manager) ListQueuedCalls(stub func(context.Context) ([]prompt.Prompt, error)) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = stub
}

func (fake *Manager) ListQueuedArgsForCall(i int) context.Context {
	fake.listQueuedMutex.RLock()
	defer fake.listQueuedMutex.RUnlock()
	argsForCall := fake.listQueuedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Manager) ListQueuedReturns(result1 []prompt.Prompt, result2 error) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = nil
	fake.listQueuedReturns = struct {
		result1 []prompt.Prompt
		result2 error
	}{result1, result2}
}

func (fake *Manager) ListQueuedReturnsOnCall(i int, result1 []prompt.Prompt, result2 error) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = nil
	if fake.listQueuedReturnsOnCall == nil {
		fake.listQueuedReturnsOnCall = make(map[int]struct {
			result1 []prompt.Prompt
			result2 error
		})
	}
	fake.listQueuedReturnsOnCall[i] = struct {
		result1 []prompt.Prompt
		result2 error
	}{result1, result2}
}

func (fake *Manager) MoveToCompleted(arg1 context.Context, arg2 string) error {
	fake.moveToCompletedMutex.Lock()
	ret, specificReturn := fake.moveToCompletedReturnsOnCall[len(fake.moveToCompletedArgsForCall)]
	fake.moveToCompletedArgsForCall = append(fake.moveToCompletedArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.MoveToCompletedStub
	fakeReturns := fake.moveToCompletedReturns
	fake.recordInvocation("MoveToCompleted", []interface{}{arg1, arg2})
	fake.moveToCompletedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Manager) MoveToCompletedCallCount() int {
	fake.moveToCompletedMutex.RLock()
	defer fake.moveToCompletedMutex.RUnlock()
	return len(fake.moveToCompletedArgsForCall)
}

func (fake *Manager) MoveToCompletedCalls(stub func(context.Context, string) error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = stub
}

func (fake *Manager) MoveToCompletedArgsForCall(i int) (context.Context, string) {
	fake.moveToCompletedMutex.RLock()
	defer fake.moveToCompletedMutex.RUnlock()
	argsForCall := fake.moveToCompletedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Manager) MoveToCompletedReturns(result1 error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = nil
	fake.moveToCompletedReturns = struct {
		result1 error
	}{result1}
}

func (fake *Manager) MoveToCompletedReturnsOnCall(i int, result1 error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = nil
	if fake.moveToCompletedReturnsOnCall == nil {
		fake.moveToCompletedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.moveToCompletedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Manager) NormalizeFilenames(arg1 context.Context) ([]prompt.Rename, error) {
	fake.normalizeFilenamesMutex.Lock()
	ret, specificReturn := fake.normalizeFilenamesReturnsOnCall[len(fake.normalizeFilenamesArgsForCall)]
	fake.normalizeFilenamesArgsForCall = append(fake.normalizeFilenamesArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.NormalizeFilenamesStub
	fakeReturns := fake.normalizeFilenamesReturns
	fake.recordInvocation("NormalizeFilenames", []interface{}{arg1})
	fake.normalizeFilenamesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Manager) NormalizeFilenamesCallCount() int {
	fake.normalizeFilenamesMutex.RLock()
	defer fake.normalizeFilenamesMutex.RUnlock()
	return len(fake.normalizeFilenamesArgsForCall)
}

func (fake *Manager) NormalizeFilenamesCalls(stub func(context.Context) ([]prompt.Rename, error)) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = stub
}

func (fake *Manager) NormalizeFilenamesArgsForCall(i int) context.Context {
	fake.normalizeFilenamesMutex.RLock()
	defer fake.normalizeFilenamesMutex.RUnlock()
	argsForCall := fake.normalizeFilenamesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Manager) NormalizeFilenamesReturns(result1 []prompt.Rename, result2 error) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = nil
	fake.normalizeFilenamesReturns = struct {
		result1 []prompt.Rename
		result2 error
	}{result1, result2}
}

func (fake *Manager) NormalizeFilenamesReturnsOnCall(i int, result1 []prompt.Rename, result2 error) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = nil
	if fake.normalizeFilenamesReturnsOnCall == nil {
		fake.normalizeFilenamesReturnsOnCall = make(map[int]struct {
			result1 []prompt.Rename
			result2 error
		})
	}
	fake.normalizeFilenamesReturnsOnCall[i] = struct {
		result1 []prompt.Rename
		result2 error
	}{result1, result2}
}

func (fake *Manager) ReadFrontmatter(arg1 context.Context, arg2 string) (*prompt.Frontmatter, error) {
	fake.readFrontmatterMutex.Lock()
	ret, specificReturn := fake.readFrontmatterReturnsOnCall[len(fake.readFrontmatterArgsForCall)]
	fake.readFrontmatterArgsForCall = append(fake.readFrontmatterArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ReadFrontmatterStub
	fakeReturns := fake.readFrontmatterReturns
	fake.recordInvocation("ReadFrontmatter", []interface{}{arg1, arg2})
	fake.readFrontmatterMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Manager) ReadFrontmatterCallCount() int {
	fake.readFrontmatterMutex.RLock()
	defer fake.readFrontmatterMutex.RUnlock()
	return len(fake.readFrontmatterArgsForCall)
}

func (fake *Manager) ReadFrontmatterCalls(stub func(context.Context, string) (*prompt.Frontmatter, error)) {
	fake.readFrontmatterMutex.Lock()
	defer fake.readFrontmatterMutex.Unlock()
	fake.ReadFrontmatterStub = stub
}

func (fake *Manager) ReadFrontmatterArgsForCall(i int) (context.Context, string) {
	fake.readFrontmatterMutex.RLock()
	defer fake.readFrontmatterMutex.RUnlock()
	argsForCall := fake.readFrontmatterArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Manager) ReadFrontmatterReturns(result1 *prompt.Frontmatter, result2 error) {
	fake.readFrontmatterMutex.Lock()
	defer fake.readFrontmatterMutex.Unlock()
	fake.ReadFrontmatterStub = nil
	fake.readFrontmatterReturns = struct {
		result1 *prompt.Frontmatter
		result2 error
	}{result1, result2}
}

func (fake *Manager) ReadFrontmatterReturnsOnCall(i int, result1 *prompt.Frontmatter, result2 error) {
	fake.readFrontmatterMutex.Lock()
	defer fake.readFrontmatterMutex.Unlock()
	fake.ReadFrontmatterStub = nil
	if fake.readFrontmatterReturnsOnCall == nil {
		fake.readFrontmatterReturnsOnCall = make(map[int]struct {
			result1 *prompt.Frontmatter
			result2 error
		})
	}
	fake.readFrontmatterReturnsOnCall[i] = struct {
		result1 *prompt.Frontmatter
		result2 error
	}{result1, result2}
}

func (fake *Manager) ResetExecuting(arg1 context.Context) error {
	fake.resetExecutingMutex.Lock()
	ret, specificReturn := fake.resetExecutingReturnsOnCall[len(fake.resetExecutingArgsForCall)]
	fake.resetExecutingArgsForCall = append(fake.resetExecutingArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ResetExecutingStub
	fakeReturns := fake.resetExecutingReturns
	fake.recordInvocation("ResetExecuting", []interface{}{arg1})
	fake.resetExecutingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Manager) ResetExecutingCallCount() int {
	fake.resetExecutingMutex.RLock()
	defer fake.resetExecutingMutex.RUnlock()
	return len(fake.resetExecutingArgsForCall)
}

func (fake *Manager) ResetExecutingCalls(stub func(context.Context) error) {
	fake.resetExecutingMutex.Lock()
	defer fake.resetExecutingMutex.Unlock()
	fake.ResetExecutingStub = stub
}

func (fake *Manager) ResetExecutingArgsForCall(i int) context.Context {
	fake.resetExecutingMutex.RLock()
	defer fake.resetExecutingMutex.RUnlock()
	argsForCall := fake.resetExecutingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Manager) ResetExecutingReturns(result1 error) {
	fake.resetExecutingMutex.Lock()
	defer fake.resetExecutingMutex.Unlock()
	fake.ResetExecutingStub = nil
	fake.resetExecutingReturns = struct {
		result1 error
	}{result1}
}

func (fake *Manager) ResetExecutingReturnsOnCall(i int, result1 error) {
	fake.resetExecutingMutex.Lock()
	defer fake.resetExecutingMutex.Unlock()
	fake.ResetExecutingStub = nil
	if fake.resetExecutingReturnsOnCall == nil {
		fake.resetExecutingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resetExecutingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Manager) SetContainer(arg1 context.Context, arg2 string, arg3 string) error {
	fake.setContainerMutex.Lock()
	ret, specificReturn := fake.setContainerReturnsOnCall[len(fake.setContainerArgsForCall)]
	fake.setContainerArgsForCall = append(fake.setContainerArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SetContainerStub
	fakeReturns := fake.setContainerReturns
	fake.recordInvocation("SetContainer", []interface{}{arg1, arg2, arg3})
	fake.setContainerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Manager) SetContainerCallCount() int {
	fake.setContainerMutex.RLock()
	defer fake.setContainerMutex.RUnlock()
	return len(fake.setContainerArgsForCall)
}

func (fake *Manager) SetContainerCalls(stub func(context.Context, string, string) error) {
	fake.setContainerMutex.Lock()
	defer fake.setContainerMutex.Unlock()
	fake.SetContainerStub = stub
}

func (fake *Manager) SetContainerArgsForCall(i int) (context.Context, string, string) {
	fake.setContainerMutex.RLock()
	defer fake.setContainerMutex.RUnlock()
	argsForCall := fake.setContainerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Manager) SetContainerReturns(result1 error) {
	fake.setContainerMutex.Lock()
	defer fake.setContainerMutex.Unlock()
	fake.SetContainerStub = nil
	fake.setContainerReturns = struct {
		result1 error
	}{result1}
}

func (fake *Manager) SetContainerReturnsOnCall(i int, result1 error) {
	fake.setContainerMutex.Lock()
	defer fake.setContainerMutex.Unlock()
	fake.SetContainerStub = nil
	if fake.setContainerReturnsOnCall == nil {
		fake.setContainerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setContainerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Manager) SetStatus(arg1 context.Context, arg2 string, arg3 string) error {
	fake.setStatusMutex.Lock()
	ret, specificReturn := fake.setStatusReturnsOnCall[len(fake.setStatusArgsForCall)]
	fake.setStatusArgsForCall = append(fake.setStatusArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SetStatusStub
	fakeReturns := fake.setStatusReturns
	fake.recordInvocation("SetStatus", []interface{}{arg1, arg2, arg3})
	fake.setStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Manager) SetStatusCallCount() int {
	fake.setStatusMutex.RLock()
	defer fake.setStatusMutex.RUnlock()
	return len(fake.setStatusArgsForCall)
}

func (fake *Manager) SetStatusCalls(stub func(context.Context, string, string) error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = stub
}

func (fake *Manager) SetStatusArgsForCall(i int) (context.Context, string, string) {
	fake.setStatusMutex.RLock()
	defer fake.setStatusMutex.RUnlock()
	argsForCall := fake.setStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Manager) SetStatusReturns(result1 error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = nil
	fake.setStatusReturns = struct {
		result1 error
	}{result1}
}

func (fake *Manager) SetStatusReturnsOnCall(i int, result1 error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = nil
	if fake.setStatusReturnsOnCall == nil {
		fake.setStatusReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setStatusReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Manager) Title(arg1 context.Context, arg2 string) (string, error) {
	fake.titleMutex.Lock()
	ret, specificReturn := fake.titleReturnsOnCall[len(fake.titleArgsForCall)]
	fake.titleArgsForCall = append(fake.titleArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.TitleStub
	fakeReturns := fake.titleReturns
	fake.recordInvocation("Title", []interface{}{arg1, arg2})
	fake.titleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Manager) TitleCallCount() int {
	fake.titleMutex.RLock()
	defer fake.titleMutex.RUnlock()
	return len(fake.titleArgsForCall)
}

func (fake *Manager) TitleCalls(stub func(context.Context, string) (string, error)) {
	fake.titleMutex.Lock()
	defer fake.titleMutex.Unlock()
	fake.TitleStub = stub
}

func (fake *Manager) TitleArgsForCall(i int) (context.Context, string) {
	fake.titleMutex.RLock()
	defer fake.titleMutex.RUnlock()
	argsForCall := fake.titleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Manager) TitleReturns(result1 string, result2 error) {
	fake.titleMutex.Lock()
	defer fake.titleMutex.Unlock()
	fake.TitleStub = nil
	fake.titleReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Manager) TitleReturnsOnCall(i int, result1 string, result2 error) {
	fake.titleMutex.Lock()
	defer fake.titleMutex.Unlock()
	fake.TitleStub = nil
	if fake.titleReturnsOnCall == nil {
		fake.titleReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.titleReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Manager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Manager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ prompt.Manager = new(Manager)
