// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/prompt"
)

type PromptCounter struct {
	CountBySpecStub        func(context.Context, string) (int, int, error)
	countBySpecMutex       sync.RWMutex
	countBySpecArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	countBySpecReturns struct {
		result1 int
		result2 int
		result3 error
	}
	countBySpecReturnsOnCall map[int]struct {
		result1 int
		result2 int
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PromptCounter) CountBySpec(arg1 context.Context, arg2 string) (int, int, error) {
	fake.countBySpecMutex.Lock()
	ret, specificReturn := fake.countBySpecReturnsOnCall[len(fake.countBySpecArgsForCall)]
	fake.countBySpecArgsForCall = append(fake.countBySpecArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CountBySpecStub
	fakeReturns := fake.countBySpecReturns
	fake.recordInvocation("CountBySpec", []interface{}{arg1, arg2})
	fake.countBySpecMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *PromptCounter) CountBySpecCallCount() int {
	fake.countBySpecMutex.RLock()
	defer fake.countBySpecMutex.RUnlock()
	return len(fake.countBySpecArgsForCall)
}

func (fake *PromptCounter) CountBySpecCalls(stub func(context.Context, string) (int, int, error)) {
	fake.countBySpecMutex.Lock()
	defer fake.countBySpecMutex.Unlock()
	fake.CountBySpecStub = stub
}

func (fake *PromptCounter) CountBySpecArgsForCall(i int) (context.Context, string) {
	fake.countBySpecMutex.RLock()
	defer fake.countBySpecMutex.RUnlock()
	argsForCall := fake.countBySpecArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PromptCounter) CountBySpecReturns(result1 int, result2 int, result3 error) {
	fake.countBySpecMutex.Lock()
	defer fake.countBySpecMutex.Unlock()
	fake.CountBySpecStub = nil
	fake.countBySpecReturns = struct {
		result1 int
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *PromptCounter) CountBySpecReturnsOnCall(i int, result1 int, result2 int, result3 error) {
	fake.countBySpecMutex.Lock()
	defer fake.countBySpecMutex.Unlock()
	fake.CountBySpecStub = nil
	if fake.countBySpecReturnsOnCall == nil {
		fake.countBySpecReturnsOnCall = make(map[int]struct {
			result1 int
			result2 int
			result3 error
		})
	}
	fake.countBySpecReturnsOnCall[i] = struct {
		result1 int
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *PromptCounter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PromptCounter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ prompt.Counter = new(PromptCounter)
