// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/prompt"
	"github.com/bborbe/dark-factory/pkg/queuescanner"
)

type PromptProcessor struct {
	ProcessPromptStub        func(context.Context, prompt.Prompt) error
	processPromptMutex       sync.RWMutex
	processPromptArgsForCall []struct {
		arg1 context.Context
		arg2 prompt.Prompt
	}
	processPromptReturns struct {
		result1 error
	}
	processPromptReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PromptProcessor) ProcessPrompt(arg1 context.Context, arg2 prompt.Prompt) error {
	fake.processPromptMutex.Lock()
	ret, specificReturn := fake.processPromptReturnsOnCall[len(fake.processPromptArgsForCall)]
	fake.processPromptArgsForCall = append(fake.processPromptArgsForCall, struct {
		arg1 context.Context
		arg2 prompt.Prompt
	}{arg1, arg2})
	stub := fake.ProcessPromptStub
	fakeReturns := fake.processPromptReturns
	fake.recordInvocation("ProcessPrompt", []interface{}{arg1, arg2})
	fake.processPromptMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PromptProcessor) ProcessPromptCallCount() int {
	fake.processPromptMutex.RLock()
	defer fake.processPromptMutex.RUnlock()
	return len(fake.processPromptArgsForCall)
}

func (fake *PromptProcessor) ProcessPromptCalls(stub func(context.Context, prompt.Prompt) error) {
	fake.processPromptMutex.Lock()
	defer fake.processPromptMutex.Unlock()
	fake.ProcessPromptStub = stub
}

func (fake *PromptProcessor) ProcessPromptArgsForCall(i int) (context.Context, prompt.Prompt) {
	fake.processPromptMutex.RLock()
	defer fake.processPromptMutex.RUnlock()
	argsForCall := fake.processPromptArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PromptProcessor) ProcessPromptReturns(result1 error) {
	fake.processPromptMutex.Lock()
	defer fake.processPromptMutex.Unlock()
	fake.ProcessPromptStub = nil
	fake.processPromptReturns = struct {
		result1 error
	}{result1}
}

func (fake *PromptProcessor) ProcessPromptReturnsOnCall(i int, result1 error) {
	fake.processPromptMutex.Lock()
	defer fake.processPromptMutex.Unlock()
	fake.ProcessPromptStub = nil
	if fake.processPromptReturnsOnCall == nil {
		fake.processPromptReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.processPromptReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PromptProcessor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PromptProcessor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ queuescanner.PromptProcessor = new(PromptProcessor)
