// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/prompt"
	"github.com/bborbe/dark-factory/pkg/queuescanner"
)

type QueueScannerPromptManager struct {
	AllPreviousCompletedStub        func(context.Context, int) bool
	allPreviousCompletedMutex       sync.RWMutex
	allPreviousCompletedArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	allPreviousCompletedReturns struct {
		result1 bool
	}
	allPreviousCompletedReturnsOnCall map[int]struct {
		result1 bool
	}
	FindMissingCompletedStub        func(context.Context, int) []int
	findMissingCompletedMutex       sync.RWMutex
	findMissingCompletedArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	findMissingCompletedReturns struct {
		result1 []int
	}
	findMissingCompletedReturnsOnCall map[int]struct {
		result1 []int
	}
	FindPromptStatusInProgressStub        func(context.Context, int) string
	findPromptStatusInProgressMutex       sync.RWMutex
	findPromptStatusInProgressArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	findPromptStatusInProgressReturns struct {
		result1 string
	}
	findPromptStatusInProgressReturnsOnCall map[int]struct {
		result1 string
	}
	ListQueuedStub        func(context.Context) ([]prompt.Prompt, error)
	listQueuedMutex       sync.RWMutex
	listQueuedArgsForCall []struct {
		arg1 context.Context
	}
	listQueuedReturns struct {
		result1 []prompt.Prompt
		result2 error
	}
	listQueuedReturnsOnCall map[int]struct {
		result1 []prompt.Prompt
		result2 error
	}
	LoadStub        func(context.Context, string) (*prompt.PromptFile, error)
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	loadReturns struct {
		result1 *prompt.PromptFile
		result2 error
	}
	loadReturnsOnCall map[int]struct {
		result1 *prompt.PromptFile
		result2 error
	}
	SetStatusStub        func(context.Context, string, string) error
	setStatusMutex       sync.RWMutex
	setStatusArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	setStatusReturns struct {
		result1 error
	}
	setStatusReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *QueueScannerPromptManager) AllPreviousCompleted(arg1 context.Context, arg2 int) bool {
	fake.allPreviousCompletedMutex.Lock()
	ret, specificReturn := fake.allPreviousCompletedReturnsOnCall[len(fake.allPreviousCompletedArgsForCall)]
	fake.allPreviousCompletedArgsForCall = append(fake.allPreviousCompletedArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.AllPreviousCompletedStub
	fakeReturns := fake.allPreviousCompletedReturns
	fake.recordInvocation("AllPreviousCompleted", []interface{}{arg1, arg2})
	fake.allPreviousCompletedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *QueueScannerPromptManager) AllPreviousCompletedCallCount() int {
	fake.allPreviousCompletedMutex.RLock()
	defer fake.allPreviousCompletedMutex.RUnlock()
	return len(fake.allPreviousCompletedArgsForCall)
}

func (fake *QueueScannerPromptManager) AllPreviousCompletedCalls(stub func(context.Context, int) bool) {
	fake.allPreviousCompletedMutex.Lock()
	defer fake.allPreviousCompletedMutex.Unlock()
	fake.AllPreviousCompletedStub = stub
}

func (fake *QueueScannerPromptManager) AllPreviousCompletedArgsForCall(i int) (context.Context, int) {
	fake.allPreviousCompletedMutex.RLock()
	defer fake.allPreviousCompletedMutex.RUnlock()
	argsForCall := fake.allPreviousCompletedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *QueueScannerPromptManager) AllPreviousCompletedReturns(result1 bool) {
	fake.allPreviousCompletedMutex.Lock()
	defer fake.allPreviousCompletedMutex.Unlock()
	fake.AllPreviousCompletedStub = nil
	fake.allPreviousCompletedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *QueueScannerPromptManager) AllPreviousCompletedReturnsOnCall(i int, result1 bool) {
	fake.allPreviousCompletedMutex.Lock()
	defer fake.allPreviousCompletedMutex.Unlock()
	fake.AllPreviousCompletedStub = nil
	if fake.allPreviousCompletedReturnsOnCall == nil {
		fake.allPreviousCompletedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.allPreviousCompletedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *QueueScannerPromptManager) FindMissingCompleted(arg1 context.Context, arg2 int) []int {
	fake.findMissingCompletedMutex.Lock()
	ret, specificReturn := fake.findMissingCompletedReturnsOnCall[len(fake.findMissingCompletedArgsForCall)]
	fake.findMissingCompletedArgsForCall = append(fake.findMissingCompletedArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.FindMissingCompletedStub
	fakeReturns := fake.findMissingCompletedReturns
	fake.recordInvocation("FindMissingCompleted", []interface{}{arg1, arg2})
	fake.findMissingCompletedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *QueueScannerPromptManager) FindMissingCompletedCallCount() int {
	fake.findMissingCompletedMutex.RLock()
	defer fake.findMissingCompletedMutex.RUnlock()
	return len(fake.findMissingCompletedArgsForCall)
}

func (fake *QueueScannerPromptManager) FindMissingCompletedCalls(stub func(context.Context, int) []int) {
	fake.findMissingCompletedMutex.Lock()
	defer fake.findMissingCompletedMutex.Unlock()
	fake.FindMissingCompletedStub = stub
}

func (fake *QueueScannerPromptManager) FindMissingCompletedArgsForCall(i int) (context.Context, int) {
	fake.findMissingCompletedMutex.RLock()
	defer fake.findMissingCompletedMutex.RUnlock()
	argsForCall := fake.findMissingCompletedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *QueueScannerPromptManager) FindMissingCompletedReturns(result1 []int) {
	fake.findMissingCompletedMutex.Lock()
	defer fake.findMissingCompletedMutex.Unlock()
	fake.FindMissingCompletedStub = nil
	fake.findMissingCompletedReturns = struct {
		result1 []int
	}{result1}
}

func (fake *QueueScannerPromptManager) FindMissingCompletedReturnsOnCall(i int, result1 []int) {
	fake.findMissingCompletedMutex.Lock()
	defer fake.findMissingCompletedMutex.Unlock()
	fake.FindMissingCompletedStub = nil
	if fake.findMissingCompletedReturnsOnCall == nil {
		fake.findMissingCompletedReturnsOnCall = make(map[int]struct {
			result1 []int
		})
	}
	fake.findMissingCompletedReturnsOnCall[i] = struct {
		result1 []int
	}{result1}
}

func (fake *QueueScannerPromptManager) FindPromptStatusInProgress(arg1 context.Context, arg2 int) string {
	fake.findPromptStatusInProgressMutex.Lock()
	ret, specificReturn := fake.findPromptStatusInProgressReturnsOnCall[len(fake.findPromptStatusInProgressArgsForCall)]
	fake.findPromptStatusInProgressArgsForCall = append(fake.findPromptStatusInProgressArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.FindPromptStatusInProgressStub
	fakeReturns := fake.findPromptStatusInProgressReturns
	fake.recordInvocation("FindPromptStatusInProgress", []interface{}{arg1, arg2})
	fake.findPromptStatusInProgressMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *QueueScannerPromptManager) FindPromptStatusInProgressCallCount() int {
	fake.findPromptStatusInProgressMutex.RLock()
	defer fake.findPromptStatusInProgressMutex.RUnlock()
	return len(fake.findPromptStatusInProgressArgsForCall)
}

func (fake *QueueScannerPromptManager) FindPromptStatusInProgressCalls(stub func(context.Context, int) string) {
	fake.findPromptStatusInProgressMutex.Lock()
	defer fake.findPromptStatusInProgressMutex.Unlock()
	fake.FindPromptStatusInProgressStub = stub
}

func (fake *QueueScannerPromptManager) FindPromptStatusInProgressArgsForCall(i int) (context.Context, int) {
	fake.findPromptStatusInProgressMutex.RLock()
	defer fake.findPromptStatusInProgressMutex.RUnlock()
	argsForCall := fake.findPromptStatusInProgressArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *QueueScannerPromptManager) FindPromptStatusInProgressReturns(result1 string) {
	fake.findPromptStatusInProgressMutex.Lock()
	defer fake.findPromptStatusInProgressMutex.Unlock()
	fake.FindPromptStatusInProgressStub = nil
	fake.findPromptStatusInProgressReturns = struct {
		result1 string
	}{result1}
}

func (fake *QueueScannerPromptManager) FindPromptStatusInProgressReturnsOnCall(i int, result1 string) {
	fake.findPromptStatusInProgressMutex.Lock()
	defer fake.findPromptStatusInProgressMutex.Unlock()
	fake.FindPromptStatusInProgressStub = nil
	if fake.findPromptStatusInProgressReturnsOnCall == nil {
		fake.findPromptStatusInProgressReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.findPromptStatusInProgressReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *QueueScannerPromptManager) ListQueued(arg1 context.Context) ([]prompt.Prompt, error) {
	fake.listQueuedMutex.Lock()
	ret, specificReturn := fake.listQueuedReturnsOnCall[len(fake.listQueuedArgsForCall)]
	fake.listQueuedArgsForCall = append(fake.listQueuedArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListQueuedStub
	fakeReturns := fake.listQueuedReturns
	fake.recordInvocation("ListQueued", []interface{}{arg1})
	fake.listQueuedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *QueueScannerPromptManager) ListQueuedCallCount() int {
	fake.listQueuedMutex.RLock()
	defer fake.listQueuedMutex.RUnlock()
	return len(fake.listQueuedArgsForCall)
}

func (fake *QueueScannerPromptManager) ListQueuedCalls(stub func(context.Context) ([]prompt.Prompt, error)) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = stub
}

func (fake *QueueScannerPromptManager) ListQueuedArgsForCall(i int) context.Context {
	fake.listQueuedMutex.RLock()
	defer fake.listQueuedMutex.RUnlock()
	argsForCall := fake.listQueuedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *QueueScannerPromptManager) ListQueuedReturns(result1 []prompt.Prompt, result2 error) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = nil
	fake.listQueuedReturns = struct {
		result1 []prompt.Prompt
		result2 error
	}{result1, result2}
}

func (fake *QueueScannerPromptManager) ListQueuedReturnsOnCall(i int, result1 []prompt.Prompt, result2 error) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = nil
	if fake.listQueuedReturnsOnCall == nil {
		fake.listQueuedReturnsOnCall = make(map[int]struct {
			result1 []prompt.Prompt
			result2 error
		})
	}
	fake.listQueuedReturnsOnCall[i] = struct {
		result1 []prompt.Prompt
		result2 error
	}{result1, result2}
}

func (fake *QueueScannerPromptManager) Load(arg1 context.Context, arg2 string) (*prompt.PromptFile, error) {
	fake.loadMutex.Lock()
	ret, specificReturn := fake.loadReturnsOnCall[len(fake.loadArgsForCall)]
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LoadStub
	fakeReturns := fake.loadReturns
	fake.recordInvocation("Load", []interface{}{arg1, arg2})
	fake.loadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *QueueScannerPromptManager) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *QueueScannerPromptManager) LoadCalls(stub func(context.Context, string) (*prompt.PromptFile, error)) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = stub
}

func (fake *QueueScannerPromptManager) LoadArgsForCall(i int) (context.Context, string) {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	argsForCall := fake.loadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *QueueScannerPromptManager) LoadReturns(result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *QueueScannerPromptManager) LoadReturnsOnCall(i int, result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	if fake.loadReturnsOnCall == nil {
		fake.loadReturnsOnCall = make(map[int]struct {
			result1 *prompt.PromptFile
			result2 error
		})
	}
	fake.loadReturnsOnCall[i] = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *QueueScannerPromptManager) SetStatus(arg1 context.Context, arg2 string, arg3 string) error {
	fake.setStatusMutex.Lock()
	ret, specificReturn := fake.setStatusReturnsOnCall[len(fake.setStatusArgsForCall)]
	fake.setStatusArgsForCall = append(fake.setStatusArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SetStatusStub
	fakeReturns := fake.setStatusReturns
	fake.recordInvocation("SetStatus", []interface{}{arg1, arg2, arg3})
	fake.setStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *QueueScannerPromptManager) SetStatusCallCount() int {
	fake.setStatusMutex.RLock()
	defer fake.setStatusMutex.RUnlock()
	return len(fake.setStatusArgsForCall)
}

func (fake *QueueScannerPromptManager) SetStatusCalls(stub func(context.Context, string, string) error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = stub
}

func (fake *QueueScannerPromptManager) SetStatusArgsForCall(i int) (context.Context, string, string) {
	fake.setStatusMutex.RLock()
	defer fake.setStatusMutex.RUnlock()
	argsForCall := fake.setStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *QueueScannerPromptManager) SetStatusReturns(result1 error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = nil
	fake.setStatusReturns = struct {
		result1 error
	}{result1}
}

func (fake *QueueScannerPromptManager) SetStatusReturnsOnCall(i int, result1 error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = nil
	if fake.setStatusReturnsOnCall == nil {
		fake.setStatusReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setStatusReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *QueueScannerPromptManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *QueueScannerPromptManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ queuescanner.PromptManager = new(QueueScannerPromptManager)
