// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/queuescanner"
)

type QueueScanner struct {
	ClearSkippedCacheStub        func()
	clearSkippedCacheMutex       sync.RWMutex
	clearSkippedCacheArgsForCall []struct {
	}
	HasPendingVerificationStub        func(context.Context) bool
	hasPendingVerificationMutex       sync.RWMutex
	hasPendingVerificationArgsForCall []struct {
		arg1 context.Context
	}
	hasPendingVerificationReturns struct {
		result1 bool
	}
	hasPendingVerificationReturnsOnCall map[int]struct {
		result1 bool
	}
	ScanAndProcessStub        func(context.Context) (int, error)
	scanAndProcessMutex       sync.RWMutex
	scanAndProcessArgsForCall []struct {
		arg1 context.Context
	}
	scanAndProcessReturns struct {
		result1 int
		result2 error
	}
	scanAndProcessReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *QueueScanner) ClearSkippedCache() {
	fake.clearSkippedCacheMutex.Lock()
	fake.clearSkippedCacheArgsForCall = append(fake.clearSkippedCacheArgsForCall, struct {
	}{})
	stub := fake.ClearSkippedCacheStub
	fake.recordInvocation("ClearSkippedCache", []interface{}{})
	fake.clearSkippedCacheMutex.Unlock()
	if stub != nil {
		fake.ClearSkippedCacheStub()
	}
}

func (fake *QueueScanner) ClearSkippedCacheCallCount() int {
	fake.clearSkippedCacheMutex.RLock()
	defer fake.clearSkippedCacheMutex.RUnlock()
	return len(fake.clearSkippedCacheArgsForCall)
}

func (fake *QueueScanner) ClearSkippedCacheCalls(stub func()) {
	fake.clearSkippedCacheMutex.Lock()
	defer fake.clearSkippedCacheMutex.Unlock()
	fake.ClearSkippedCacheStub = stub
}

func (fake *QueueScanner) HasPendingVerification(arg1 context.Context) bool {
	fake.hasPendingVerificationMutex.Lock()
	ret, specificReturn := fake.hasPendingVerificationReturnsOnCall[len(fake.hasPendingVerificationArgsForCall)]
	fake.hasPendingVerificationArgsForCall = append(fake.hasPendingVerificationArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.HasPendingVerificationStub
	fakeReturns := fake.hasPendingVerificationReturns
	fake.recordInvocation("HasPendingVerification", []interface{}{arg1})
	fake.hasPendingVerificationMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *QueueScanner) HasPendingVerificationCallCount() int {
	fake.hasPendingVerificationMutex.RLock()
	defer fake.hasPendingVerificationMutex.RUnlock()
	return len(fake.hasPendingVerificationArgsForCall)
}

func (fake *QueueScanner) HasPendingVerificationCalls(stub func(context.Context) bool) {
	fake.hasPendingVerificationMutex.Lock()
	defer fake.hasPendingVerificationMutex.Unlock()
	fake.HasPendingVerificationStub = stub
}

func (fake *QueueScanner) HasPendingVerificationArgsForCall(i int) context.Context {
	fake.hasPendingVerificationMutex.RLock()
	defer fake.hasPendingVerificationMutex.RUnlock()
	argsForCall := fake.hasPendingVerificationArgsForCall[i]
	return argsForCall.arg1
}

func (fake *QueueScanner) HasPendingVerificationReturns(result1 bool) {
	fake.hasPendingVerificationMutex.Lock()
	defer fake.hasPendingVerificationMutex.Unlock()
	fake.HasPendingVerificationStub = nil
	fake.hasPendingVerificationReturns = struct {
		result1 bool
	}{result1}
}

func (fake *QueueScanner) HasPendingVerificationReturnsOnCall(i int, result1 bool) {
	fake.hasPendingVerificationMutex.Lock()
	defer fake.hasPendingVerificationMutex.Unlock()
	fake.HasPendingVerificationStub = nil
	if fake.hasPendingVerificationReturnsOnCall == nil {
		fake.hasPendingVerificationReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.hasPendingVerificationReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *QueueScanner) ScanAndProcess(arg1 context.Context) (int, error) {
	fake.scanAndProcessMutex.Lock()
	ret, specificReturn := fake.scanAndProcessReturnsOnCall[len(fake.scanAndProcessArgsForCall)]
	fake.scanAndProcessArgsForCall = append(fake.scanAndProcessArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ScanAndProcessStub
	fakeReturns := fake.scanAndProcessReturns
	fake.recordInvocation("ScanAndProcess", []interface{}{arg1})
	fake.scanAndProcessMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *QueueScanner) ScanAndProcessCallCount() int {
	fake.scanAndProcessMutex.RLock()
	defer fake.scanAndProcessMutex.RUnlock()
	return len(fake.scanAndProcessArgsForCall)
}

func (fake *QueueScanner) ScanAndProcessCalls(stub func(context.Context) (int, error)) {
	fake.scanAndProcessMutex.Lock()
	defer fake.scanAndProcessMutex.Unlock()
	fake.ScanAndProcessStub = stub
}

func (fake *QueueScanner) ScanAndProcessArgsForCall(i int) context.Context {
	fake.scanAndProcessMutex.RLock()
	defer fake.scanAndProcessMutex.RUnlock()
	argsForCall := fake.scanAndProcessArgsForCall[i]
	return argsForCall.arg1
}

func (fake *QueueScanner) ScanAndProcessReturns(result1 int, result2 error) {
	fake.scanAndProcessMutex.Lock()
	defer fake.scanAndProcessMutex.Unlock()
	fake.ScanAndProcessStub = nil
	fake.scanAndProcessReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *QueueScanner) ScanAndProcessReturnsOnCall(i int, result1 int, result2 error) {
	fake.scanAndProcessMutex.Lock()
	defer fake.scanAndProcessMutex.Unlock()
	fake.ScanAndProcessStub = nil
	if fake.scanAndProcessReturnsOnCall == nil {
		fake.scanAndProcessReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.scanAndProcessReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *QueueScanner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *QueueScanner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ queuescanner.Scanner = new(QueueScanner)
