// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/reindex"
)

type Reindexer struct {
	ReindexStub        func(context.Context) ([]reindex.Rename, error)
	reindexMutex       sync.RWMutex
	reindexArgsForCall []struct {
		arg1 context.Context
	}
	reindexReturns struct {
		result1 []reindex.Rename
		result2 error
	}
	reindexReturnsOnCall map[int]struct {
		result1 []reindex.Rename
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Reindexer) Reindex(arg1 context.Context) ([]reindex.Rename, error) {
	fake.reindexMutex.Lock()
	ret, specificReturn := fake.reindexReturnsOnCall[len(fake.reindexArgsForCall)]
	fake.reindexArgsForCall = append(fake.reindexArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ReindexStub
	fakeReturns := fake.reindexReturns
	fake.recordInvocation("Reindex", []interface{}{arg1})
	fake.reindexMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Reindexer) ReindexCallCount() int {
	fake.reindexMutex.RLock()
	defer fake.reindexMutex.RUnlock()
	return len(fake.reindexArgsForCall)
}

func (fake *Reindexer) ReindexCalls(stub func(context.Context) ([]reindex.Rename, error)) {
	fake.reindexMutex.Lock()
	defer fake.reindexMutex.Unlock()
	fake.ReindexStub = stub
}

func (fake *Reindexer) ReindexArgsForCall(i int) context.Context {
	fake.reindexMutex.RLock()
	defer fake.reindexMutex.RUnlock()
	argsForCall := fake.reindexArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Reindexer) ReindexReturns(result1 []reindex.Rename, result2 error) {
	fake.reindexMutex.Lock()
	defer fake.reindexMutex.Unlock()
	fake.ReindexStub = nil
	fake.reindexReturns = struct {
		result1 []reindex.Rename
		result2 error
	}{result1, result2}
}

func (fake *Reindexer) ReindexReturnsOnCall(i int, result1 []reindex.Rename, result2 error) {
	fake.reindexMutex.Lock()
	defer fake.reindexMutex.Unlock()
	fake.ReindexStub = nil
	if fake.reindexReturnsOnCall == nil {
		fake.reindexReturnsOnCall = make(map[int]struct {
			result1 []reindex.Rename
			result2 error
		})
	}
	fake.reindexReturnsOnCall[i] = struct {
		result1 []reindex.Rename
		result2 error
	}{result1, result2}
}

func (fake *Reindexer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Reindexer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ reindex.Reindexer = new(Reindexer)
