// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/git"
)

type Releaser struct {
	CommitAndReleaseStub        func(context.Context, string) error
	commitAndReleaseMutex       sync.RWMutex
	commitAndReleaseArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	commitAndReleaseReturns struct {
		result1 error
	}
	commitAndReleaseReturnsOnCall map[int]struct {
		result1 error
	}
	CommitCompletedFileStub        func(context.Context, string) error
	commitCompletedFileMutex       sync.RWMutex
	commitCompletedFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	commitCompletedFileReturns struct {
		result1 error
	}
	commitCompletedFileReturnsOnCall map[int]struct {
		result1 error
	}
	CommitOnlyStub        func(context.Context, string) error
	commitOnlyMutex       sync.RWMutex
	commitOnlyArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	commitOnlyReturns struct {
		result1 error
	}
	commitOnlyReturnsOnCall map[int]struct {
		result1 error
	}
	GetNextVersionStub        func(context.Context) (string, error)
	getNextVersionMutex       sync.RWMutex
	getNextVersionArgsForCall []struct {
		arg1 context.Context
	}
	getNextVersionReturns struct {
		result1 string
		result2 error
	}
	getNextVersionReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	HasChangelogStub        func(context.Context) bool
	hasChangelogMutex       sync.RWMutex
	hasChangelogArgsForCall []struct {
		arg1 context.Context
	}
	hasChangelogReturns struct {
		result1 bool
	}
	hasChangelogReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Releaser) CommitAndRelease(arg1 context.Context, arg2 string) error {
	fake.commitAndReleaseMutex.Lock()
	ret, specificReturn := fake.commitAndReleaseReturnsOnCall[len(fake.commitAndReleaseArgsForCall)]
	fake.commitAndReleaseArgsForCall = append(fake.commitAndReleaseArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CommitAndReleaseStub
	fakeReturns := fake.commitAndReleaseReturns
	fake.recordInvocation("CommitAndRelease", []interface{}{arg1, arg2})
	fake.commitAndReleaseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Releaser) CommitAndReleaseCallCount() int {
	fake.commitAndReleaseMutex.RLock()
	defer fake.commitAndReleaseMutex.RUnlock()
	return len(fake.commitAndReleaseArgsForCall)
}

func (fake *Releaser) CommitAndReleaseCalls(stub func(context.Context, string) error) {
	fake.commitAndReleaseMutex.Lock()
	defer fake.commitAndReleaseMutex.Unlock()
	fake.CommitAndReleaseStub = stub
}

func (fake *Releaser) CommitAndReleaseArgsForCall(i int) (context.Context, string) {
	fake.commitAndReleaseMutex.RLock()
	defer fake.commitAndReleaseMutex.RUnlock()
	argsForCall := fake.commitAndReleaseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Releaser) CommitAndReleaseReturns(result1 error) {
	fake.commitAndReleaseMutex.Lock()
	defer fake.commitAndReleaseMutex.Unlock()
	fake.CommitAndReleaseStub = nil
	fake.commitAndReleaseReturns = struct {
		result1 error
	}{result1}
}

func (fake *Releaser) CommitAndReleaseReturnsOnCall(i int, result1 error) {
	fake.commitAndReleaseMutex.Lock()
	defer fake.commitAndReleaseMutex.Unlock()
	fake.CommitAndReleaseStub = nil
	if fake.commitAndReleaseReturnsOnCall == nil {
		fake.commitAndReleaseReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.commitAndReleaseReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Releaser) CommitCompletedFile(arg1 context.Context, arg2 string) error {
	fake.commitCompletedFileMutex.Lock()
	ret, specificReturn := fake.commitCompletedFileReturnsOnCall[len(fake.commitCompletedFileArgsForCall)]
	fake.commitCompletedFileArgsForCall = append(fake.commitCompletedFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CommitCompletedFileStub
	fakeReturns := fake.commitCompletedFileReturns
	fake.recordInvocation("CommitCompletedFile", []interface{}{arg1, arg2})
	fake.commitCompletedFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Releaser) CommitCompletedFileCallCount() int {
	fake.commitCompletedFileMutex.RLock()
	defer fake.commitCompletedFileMutex.RUnlock()
	return len(fake.commitCompletedFileArgsForCall)
}

func (fake *Releaser) CommitCompletedFileCalls(stub func(context.Context, string) error) {
	fake.commitCompletedFileMutex.Lock()
	defer fake.commitCompletedFileMutex.Unlock()
	fake.CommitCompletedFileStub = stub
}

func (fake *Releaser) CommitCompletedFileArgsForCall(i int) (context.Context, string) {
	fake.commitCompletedFileMutex.RLock()
	defer fake.commitCompletedFileMutex.RUnlock()
	argsForCall := fake.commitCompletedFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Releaser) CommitCompletedFileReturns(result1 error) {
	fake.commitCompletedFileMutex.Lock()
	defer fake.commitCompletedFileMutex.Unlock()
	fake.CommitCompletedFileStub = nil
	fake.commitCompletedFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *Releaser) CommitCompletedFileReturnsOnCall(i int, result1 error) {
	fake.commitCompletedFileMutex.Lock()
	defer fake.commitCompletedFileMutex.Unlock()
	fake.CommitCompletedFileStub = nil
	if fake.commitCompletedFileReturnsOnCall == nil {
		fake.commitCompletedFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.commitCompletedFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Releaser) CommitOnly(arg1 context.Context, arg2 string) error {
	fake.commitOnlyMutex.Lock()
	ret, specificReturn := fake.commitOnlyReturnsOnCall[len(fake.commitOnlyArgsForCall)]
	fake.commitOnlyArgsForCall = append(fake.commitOnlyArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CommitOnlyStub
	fakeReturns := fake.commitOnlyReturns
	fake.recordInvocation("CommitOnly", []interface{}{arg1, arg2})
	fake.commitOnlyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Releaser) CommitOnlyCallCount() int {
	fake.commitOnlyMutex.RLock()
	defer fake.commitOnlyMutex.RUnlock()
	return len(fake.commitOnlyArgsForCall)
}

func (fake *Releaser) CommitOnlyCalls(stub func(context.Context, string) error) {
	fake.commitOnlyMutex.Lock()
	defer fake.commitOnlyMutex.Unlock()
	fake.CommitOnlyStub = stub
}

func (fake *Releaser) CommitOnlyArgsForCall(i int) (context.Context, string) {
	fake.commitOnlyMutex.RLock()
	defer fake.commitOnlyMutex.RUnlock()
	argsForCall := fake.commitOnlyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Releaser) CommitOnlyReturns(result1 error) {
	fake.commitOnlyMutex.Lock()
	defer fake.commitOnlyMutex.Unlock()
	fake.CommitOnlyStub = nil
	fake.commitOnlyReturns = struct {
		result1 error
	}{result1}
}

func (fake *Releaser) CommitOnlyReturnsOnCall(i int, result1 error) {
	fake.commitOnlyMutex.Lock()
	defer fake.commitOnlyMutex.Unlock()
	fake.CommitOnlyStub = nil
	if fake.commitOnlyReturnsOnCall == nil {
		fake.commitOnlyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.commitOnlyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Releaser) GetNextVersion(arg1 context.Context) (string, error) {
	fake.getNextVersionMutex.Lock()
	ret, specificReturn := fake.getNextVersionReturnsOnCall[len(fake.getNextVersionArgsForCall)]
	fake.getNextVersionArgsForCall = append(fake.getNextVersionArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetNextVersionStub
	fakeReturns := fake.getNextVersionReturns
	fake.recordInvocation("GetNextVersion", []interface{}{arg1})
	fake.getNextVersionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Releaser) GetNextVersionCallCount() int {
	fake.getNextVersionMutex.RLock()
	defer fake.getNextVersionMutex.RUnlock()
	return len(fake.getNextVersionArgsForCall)
}

func (fake *Releaser) GetNextVersionCalls(stub func(context.Context) (string, error)) {
	fake.getNextVersionMutex.Lock()
	defer fake.getNextVersionMutex.Unlock()
	fake.GetNextVersionStub = stub
}

func (fake *Releaser) GetNextVersionArgsForCall(i int) context.Context {
	fake.getNextVersionMutex.RLock()
	defer fake.getNextVersionMutex.RUnlock()
	argsForCall := fake.getNextVersionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Releaser) GetNextVersionReturns(result1 string, result2 error) {
	fake.getNextVersionMutex.Lock()
	defer fake.getNextVersionMutex.Unlock()
	fake.GetNextVersionStub = nil
	fake.getNextVersionReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Releaser) GetNextVersionReturnsOnCall(i int, result1 string, result2 error) {
	fake.getNextVersionMutex.Lock()
	defer fake.getNextVersionMutex.Unlock()
	fake.GetNextVersionStub = nil
	if fake.getNextVersionReturnsOnCall == nil {
		fake.getNextVersionReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getNextVersionReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Releaser) HasChangelog(arg1 context.Context) bool {
	fake.hasChangelogMutex.Lock()
	ret, specificReturn := fake.hasChangelogReturnsOnCall[len(fake.hasChangelogArgsForCall)]
	fake.hasChangelogArgsForCall = append(fake.hasChangelogArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.HasChangelogStub
	fakeReturns := fake.hasChangelogReturns
	fake.recordInvocation("HasChangelog", []interface{}{arg1})
	fake.hasChangelogMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Releaser) HasChangelogCallCount() int {
	fake.hasChangelogMutex.RLock()
	defer fake.hasChangelogMutex.RUnlock()
	return len(fake.hasChangelogArgsForCall)
}

func (fake *Releaser) HasChangelogCalls(stub func(context.Context) bool) {
	fake.hasChangelogMutex.Lock()
	defer fake.hasChangelogMutex.Unlock()
	fake.HasChangelogStub = stub
}

func (fake *Releaser) HasChangelogArgsForCall(i int) context.Context {
	fake.hasChangelogMutex.RLock()
	defer fake.hasChangelogMutex.RUnlock()
	argsForCall := fake.hasChangelogArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Releaser) HasChangelogReturns(result1 bool) {
	fake.hasChangelogMutex.Lock()
	defer fake.hasChangelogMutex.Unlock()
	fake.HasChangelogStub = nil
	fake.hasChangelogReturns = struct {
		result1 bool
	}{result1}
}

func (fake *Releaser) HasChangelogReturnsOnCall(i int, result1 bool) {
	fake.hasChangelogMutex.Lock()
	defer fake.hasChangelogMutex.Unlock()
	fake.HasChangelogStub = nil
	if fake.hasChangelogReturnsOnCall == nil {
		fake.hasChangelogReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.hasChangelogReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *Releaser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Releaser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ git.Releaser = new(Releaser)
