// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/report"
)

type ReportParser struct {
	ParseFromLogStub        func(context.Context, string) (*report.CompletionReport, error)
	parseFromLogMutex       sync.RWMutex
	parseFromLogArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	parseFromLogReturns struct {
		result1 *report.CompletionReport
		result2 error
	}
	parseFromLogReturnsOnCall map[int]struct {
		result1 *report.CompletionReport
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ReportParser) ParseFromLog(arg1 context.Context, arg2 string) (*report.CompletionReport, error) {
	fake.parseFromLogMutex.Lock()
	ret, specificReturn := fake.parseFromLogReturnsOnCall[len(fake.parseFromLogArgsForCall)]
	fake.parseFromLogArgsForCall = append(fake.parseFromLogArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ParseFromLogStub
	fakeReturns := fake.parseFromLogReturns
	fake.recordInvocation("ParseFromLog", []interface{}{arg1, arg2})
	fake.parseFromLogMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ReportParser) ParseFromLogCallCount() int {
	fake.parseFromLogMutex.RLock()
	defer fake.parseFromLogMutex.RUnlock()
	return len(fake.parseFromLogArgsForCall)
}

func (fake *ReportParser) ParseFromLogCalls(stub func(context.Context, string) (*report.CompletionReport, error)) {
	fake.parseFromLogMutex.Lock()
	defer fake.parseFromLogMutex.Unlock()
	fake.ParseFromLogStub = stub
}

func (fake *ReportParser) ParseFromLogArgsForCall(i int) (context.Context, string) {
	fake.parseFromLogMutex.RLock()
	defer fake.parseFromLogMutex.RUnlock()
	argsForCall := fake.parseFromLogArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ReportParser) ParseFromLogReturns(result1 *report.CompletionReport, result2 error) {
	fake.parseFromLogMutex.Lock()
	defer fake.parseFromLogMutex.Unlock()
	fake.ParseFromLogStub = nil
	fake.parseFromLogReturns = struct {
		result1 *report.CompletionReport
		result2 error
	}{result1, result2}
}

func (fake *ReportParser) ParseFromLogReturnsOnCall(i int, result1 *report.CompletionReport, result2 error) {
	fake.parseFromLogMutex.Lock()
	defer fake.parseFromLogMutex.Unlock()
	fake.ParseFromLogStub = nil
	if fake.parseFromLogReturnsOnCall == nil {
		fake.parseFromLogReturnsOnCall = make(map[int]struct {
			result1 *report.CompletionReport
			result2 error
		})
	}
	fake.parseFromLogReturnsOnCall[i] = struct {
		result1 *report.CompletionReport
		result2 error
	}{result1, result2}
}

func (fake *ReportParser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ReportParser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ report.Parser = new(ReportParser)
