// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/git"
)

type ReviewFetcher struct {
	FetchLatestReviewStub        func(context.Context, string, []string) (*git.ReviewResult, error)
	fetchLatestReviewMutex       sync.RWMutex
	fetchLatestReviewArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}
	fetchLatestReviewReturns struct {
		result1 *git.ReviewResult
		result2 error
	}
	fetchLatestReviewReturnsOnCall map[int]struct {
		result1 *git.ReviewResult
		result2 error
	}
	FetchPRStateStub        func(context.Context, string) (string, error)
	fetchPRStateMutex       sync.RWMutex
	fetchPRStateArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	fetchPRStateReturns struct {
		result1 string
		result2 error
	}
	fetchPRStateReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ReviewFetcher) FetchLatestReview(arg1 context.Context, arg2 string, arg3 []string) (*git.ReviewResult, error) {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.fetchLatestReviewMutex.Lock()
	ret, specificReturn := fake.fetchLatestReviewReturnsOnCall[len(fake.fetchLatestReviewArgsForCall)]
	fake.fetchLatestReviewArgsForCall = append(fake.fetchLatestReviewArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}{arg1, arg2, arg3Copy})
	stub := fake.FetchLatestReviewStub
	fakeReturns := fake.fetchLatestReviewReturns
	fake.recordInvocation("FetchLatestReview", []interface{}{arg1, arg2, arg3Copy})
	fake.fetchLatestReviewMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ReviewFetcher) FetchLatestReviewCallCount() int {
	fake.fetchLatestReviewMutex.RLock()
	defer fake.fetchLatestReviewMutex.RUnlock()
	return len(fake.fetchLatestReviewArgsForCall)
}

func (fake *ReviewFetcher) FetchLatestReviewCalls(stub func(context.Context, string, []string) (*git.ReviewResult, error)) {
	fake.fetchLatestReviewMutex.Lock()
	defer fake.fetchLatestReviewMutex.Unlock()
	fake.FetchLatestReviewStub = stub
}

func (fake *ReviewFetcher) FetchLatestReviewArgsForCall(i int) (context.Context, string, []string) {
	fake.fetchLatestReviewMutex.RLock()
	defer fake.fetchLatestReviewMutex.RUnlock()
	argsForCall := fake.fetchLatestReviewArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ReviewFetcher) FetchLatestReviewReturns(result1 *git.ReviewResult, result2 error) {
	fake.fetchLatestReviewMutex.Lock()
	defer fake.fetchLatestReviewMutex.Unlock()
	fake.FetchLatestReviewStub = nil
	fake.fetchLatestReviewReturns = struct {
		result1 *git.ReviewResult
		result2 error
	}{result1, result2}
}

func (fake *ReviewFetcher) FetchLatestReviewReturnsOnCall(i int, result1 *git.ReviewResult, result2 error) {
	fake.fetchLatestReviewMutex.Lock()
	defer fake.fetchLatestReviewMutex.Unlock()
	fake.FetchLatestReviewStub = nil
	if fake.fetchLatestReviewReturnsOnCall == nil {
		fake.fetchLatestReviewReturnsOnCall = make(map[int]struct {
			result1 *git.ReviewResult
			result2 error
		})
	}
	fake.fetchLatestReviewReturnsOnCall[i] = struct {
		result1 *git.ReviewResult
		result2 error
	}{result1, result2}
}

func (fake *ReviewFetcher) FetchPRState(arg1 context.Context, arg2 string) (string, error) {
	fake.fetchPRStateMutex.Lock()
	ret, specificReturn := fake.fetchPRStateReturnsOnCall[len(fake.fetchPRStateArgsForCall)]
	fake.fetchPRStateArgsForCall = append(fake.fetchPRStateArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FetchPRStateStub
	fakeReturns := fake.fetchPRStateReturns
	fake.recordInvocation("FetchPRState", []interface{}{arg1, arg2})
	fake.fetchPRStateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ReviewFetcher) FetchPRStateCallCount() int {
	fake.fetchPRStateMutex.RLock()
	defer fake.fetchPRStateMutex.RUnlock()
	return len(fake.fetchPRStateArgsForCall)
}

func (fake *ReviewFetcher) FetchPRStateCalls(stub func(context.Context, string) (string, error)) {
	fake.fetchPRStateMutex.Lock()
	defer fake.fetchPRStateMutex.Unlock()
	fake.FetchPRStateStub = stub
}

func (fake *ReviewFetcher) FetchPRStateArgsForCall(i int) (context.Context, string) {
	fake.fetchPRStateMutex.RLock()
	defer fake.fetchPRStateMutex.RUnlock()
	argsForCall := fake.fetchPRStateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ReviewFetcher) FetchPRStateReturns(result1 string, result2 error) {
	fake.fetchPRStateMutex.Lock()
	defer fake.fetchPRStateMutex.Unlock()
	fake.FetchPRStateStub = nil
	fake.fetchPRStateReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ReviewFetcher) FetchPRStateReturnsOnCall(i int, result1 string, result2 error) {
	fake.fetchPRStateMutex.Lock()
	defer fake.fetchPRStateMutex.Unlock()
	fake.FetchPRStateStub = nil
	if fake.fetchPRStateReturnsOnCall == nil {
		fake.fetchPRStateReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.fetchPRStateReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ReviewFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ReviewFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ git.ReviewFetcher = new(ReviewFetcher)
