// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/prompt"
	"github.com/bborbe/dark-factory/pkg/review"
)

type ReviewPromptManager struct {
	IncrementRetryCountStub        func(context.Context, string) error
	incrementRetryCountMutex       sync.RWMutex
	incrementRetryCountArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	incrementRetryCountReturns struct {
		result1 error
	}
	incrementRetryCountReturnsOnCall map[int]struct {
		result1 error
	}
	LoadStub        func(context.Context, string) (*prompt.PromptFile, error)
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	loadReturns struct {
		result1 *prompt.PromptFile
		result2 error
	}
	loadReturnsOnCall map[int]struct {
		result1 *prompt.PromptFile
		result2 error
	}
	MoveToCompletedStub        func(context.Context, string) error
	moveToCompletedMutex       sync.RWMutex
	moveToCompletedArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	moveToCompletedReturns struct {
		result1 error
	}
	moveToCompletedReturnsOnCall map[int]struct {
		result1 error
	}
	ReadFrontmatterStub        func(context.Context, string) (*prompt.Frontmatter, error)
	readFrontmatterMutex       sync.RWMutex
	readFrontmatterArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	readFrontmatterReturns struct {
		result1 *prompt.Frontmatter
		result2 error
	}
	readFrontmatterReturnsOnCall map[int]struct {
		result1 *prompt.Frontmatter
		result2 error
	}
	SetStatusStub        func(context.Context, string, string) error
	setStatusMutex       sync.RWMutex
	setStatusArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	setStatusReturns struct {
		result1 error
	}
	setStatusReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ReviewPromptManager) IncrementRetryCount(arg1 context.Context, arg2 string) error {
	fake.incrementRetryCountMutex.Lock()
	ret, specificReturn := fake.incrementRetryCountReturnsOnCall[len(fake.incrementRetryCountArgsForCall)]
	fake.incrementRetryCountArgsForCall = append(fake.incrementRetryCountArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.IncrementRetryCountStub
	fakeReturns := fake.incrementRetryCountReturns
	fake.recordInvocation("IncrementRetryCount", []interface{}{arg1, arg2})
	fake.incrementRetryCountMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ReviewPromptManager) IncrementRetryCountCallCount() int {
	fake.incrementRetryCountMutex.RLock()
	defer fake.incrementRetryCountMutex.RUnlock()
	return len(fake.incrementRetryCountArgsForCall)
}

func (fake *ReviewPromptManager) IncrementRetryCountCalls(stub func(context.Context, string) error) {
	fake.incrementRetryCountMutex.Lock()
	defer fake.incrementRetryCountMutex.Unlock()
	fake.IncrementRetryCountStub = stub
}

func (fake *ReviewPromptManager) IncrementRetryCountArgsForCall(i int) (context.Context, string) {
	fake.incrementRetryCountMutex.RLock()
	defer fake.incrementRetryCountMutex.RUnlock()
	argsForCall := fake.incrementRetryCountArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ReviewPromptManager) IncrementRetryCountReturns(result1 error) {
	fake.incrementRetryCountMutex.Lock()
	defer fake.incrementRetryCountMutex.Unlock()
	fake.IncrementRetryCountStub = nil
	fake.incrementRetryCountReturns = struct {
		result1 error
	}{result1}
}

func (fake *ReviewPromptManager) IncrementRetryCountReturnsOnCall(i int, result1 error) {
	fake.incrementRetryCountMutex.Lock()
	defer fake.incrementRetryCountMutex.Unlock()
	fake.IncrementRetryCountStub = nil
	if fake.incrementRetryCountReturnsOnCall == nil {
		fake.incrementRetryCountReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.incrementRetryCountReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ReviewPromptManager) Load(arg1 context.Context, arg2 string) (*prompt.PromptFile, error) {
	fake.loadMutex.Lock()
	ret, specificReturn := fake.loadReturnsOnCall[len(fake.loadArgsForCall)]
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LoadStub
	fakeReturns := fake.loadReturns
	fake.recordInvocation("Load", []interface{}{arg1, arg2})
	fake.loadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ReviewPromptManager) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *ReviewPromptManager) LoadCalls(stub func(context.Context, string) (*prompt.PromptFile, error)) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = stub
}

func (fake *ReviewPromptManager) LoadArgsForCall(i int) (context.Context, string) {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	argsForCall := fake.loadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ReviewPromptManager) LoadReturns(result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *ReviewPromptManager) LoadReturnsOnCall(i int, result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	if fake.loadReturnsOnCall == nil {
		fake.loadReturnsOnCall = make(map[int]struct {
			result1 *prompt.PromptFile
			result2 error
		})
	}
	fake.loadReturnsOnCall[i] = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *ReviewPromptManager) MoveToCompleted(arg1 context.Context, arg2 string) error {
	fake.moveToCompletedMutex.Lock()
	ret, specificReturn := fake.moveToCompletedReturnsOnCall[len(fake.moveToCompletedArgsForCall)]
	fake.moveToCompletedArgsForCall = append(fake.moveToCompletedArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.MoveToCompletedStub
	fakeReturns := fake.moveToCompletedReturns
	fake.recordInvocation("MoveToCompleted", []interface{}{arg1, arg2})
	fake.moveToCompletedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ReviewPromptManager) MoveToCompletedCallCount() int {
	fake.moveToCompletedMutex.RLock()
	defer fake.moveToCompletedMutex.RUnlock()
	return len(fake.moveToCompletedArgsForCall)
}

func (fake *ReviewPromptManager) MoveToCompletedCalls(stub func(context.Context, string) error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = stub
}

func (fake *ReviewPromptManager) MoveToCompletedArgsForCall(i int) (context.Context, string) {
	fake.moveToCompletedMutex.RLock()
	defer fake.moveToCompletedMutex.RUnlock()
	argsForCall := fake.moveToCompletedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ReviewPromptManager) MoveToCompletedReturns(result1 error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = nil
	fake.moveToCompletedReturns = struct {
		result1 error
	}{result1}
}

func (fake *ReviewPromptManager) MoveToCompletedReturnsOnCall(i int, result1 error) {
	fake.moveToCompletedMutex.Lock()
	defer fake.moveToCompletedMutex.Unlock()
	fake.MoveToCompletedStub = nil
	if fake.moveToCompletedReturnsOnCall == nil {
		fake.moveToCompletedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.moveToCompletedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ReviewPromptManager) ReadFrontmatter(arg1 context.Context, arg2 string) (*prompt.Frontmatter, error) {
	fake.readFrontmatterMutex.Lock()
	ret, specificReturn := fake.readFrontmatterReturnsOnCall[len(fake.readFrontmatterArgsForCall)]
	fake.readFrontmatterArgsForCall = append(fake.readFrontmatterArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ReadFrontmatterStub
	fakeReturns := fake.readFrontmatterReturns
	fake.recordInvocation("ReadFrontmatter", []interface{}{arg1, arg2})
	fake.readFrontmatterMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ReviewPromptManager) ReadFrontmatterCallCount() int {
	fake.readFrontmatterMutex.RLock()
	defer fake.readFrontmatterMutex.RUnlock()
	return len(fake.readFrontmatterArgsForCall)
}

func (fake *ReviewPromptManager) ReadFrontmatterCalls(stub func(context.Context, string) (*prompt.Frontmatter, error)) {
	fake.readFrontmatterMutex.Lock()
	defer fake.readFrontmatterMutex.Unlock()
	fake.ReadFrontmatterStub = stub
}

func (fake *ReviewPromptManager) ReadFrontmatterArgsForCall(i int) (context.Context, string) {
	fake.readFrontmatterMutex.RLock()
	defer fake.readFrontmatterMutex.RUnlock()
	argsForCall := fake.readFrontmatterArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ReviewPromptManager) ReadFrontmatterReturns(result1 *prompt.Frontmatter, result2 error) {
	fake.readFrontmatterMutex.Lock()
	defer fake.readFrontmatterMutex.Unlock()
	fake.ReadFrontmatterStub = nil
	fake.readFrontmatterReturns = struct {
		result1 *prompt.Frontmatter
		result2 error
	}{result1, result2}
}

func (fake *ReviewPromptManager) ReadFrontmatterReturnsOnCall(i int, result1 *prompt.Frontmatter, result2 error) {
	fake.readFrontmatterMutex.Lock()
	defer fake.readFrontmatterMutex.Unlock()
	fake.ReadFrontmatterStub = nil
	if fake.readFrontmatterReturnsOnCall == nil {
		fake.readFrontmatterReturnsOnCall = make(map[int]struct {
			result1 *prompt.Frontmatter
			result2 error
		})
	}
	fake.readFrontmatterReturnsOnCall[i] = struct {
		result1 *prompt.Frontmatter
		result2 error
	}{result1, result2}
}

func (fake *ReviewPromptManager) SetStatus(arg1 context.Context, arg2 string, arg3 string) error {
	fake.setStatusMutex.Lock()
	ret, specificReturn := fake.setStatusReturnsOnCall[len(fake.setStatusArgsForCall)]
	fake.setStatusArgsForCall = append(fake.setStatusArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SetStatusStub
	fakeReturns := fake.setStatusReturns
	fake.recordInvocation("SetStatus", []interface{}{arg1, arg2, arg3})
	fake.setStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ReviewPromptManager) SetStatusCallCount() int {
	fake.setStatusMutex.RLock()
	defer fake.setStatusMutex.RUnlock()
	return len(fake.setStatusArgsForCall)
}

func (fake *ReviewPromptManager) SetStatusCalls(stub func(context.Context, string, string) error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = stub
}

func (fake *ReviewPromptManager) SetStatusArgsForCall(i int) (context.Context, string, string) {
	fake.setStatusMutex.RLock()
	defer fake.setStatusMutex.RUnlock()
	argsForCall := fake.setStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ReviewPromptManager) SetStatusReturns(result1 error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = nil
	fake.setStatusReturns = struct {
		result1 error
	}{result1}
}

func (fake *ReviewPromptManager) SetStatusReturnsOnCall(i int, result1 error) {
	fake.setStatusMutex.Lock()
	defer fake.setStatusMutex.Unlock()
	fake.SetStatusStub = nil
	if fake.setStatusReturnsOnCall == nil {
		fake.setStatusReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setStatusReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ReviewPromptManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ReviewPromptManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ review.PromptManager = new(ReviewPromptManager)
