// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/prompt"
	"github.com/bborbe/dark-factory/pkg/runner"
)

type RunnerPromptManager struct {
	ListQueuedStub        func(context.Context) ([]prompt.Prompt, error)
	listQueuedMutex       sync.RWMutex
	listQueuedArgsForCall []struct {
		arg1 context.Context
	}
	listQueuedReturns struct {
		result1 []prompt.Prompt
		result2 error
	}
	listQueuedReturnsOnCall map[int]struct {
		result1 []prompt.Prompt
		result2 error
	}
	LoadStub        func(context.Context, string) (*prompt.PromptFile, error)
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	loadReturns struct {
		result1 *prompt.PromptFile
		result2 error
	}
	loadReturnsOnCall map[int]struct {
		result1 *prompt.PromptFile
		result2 error
	}
	NormalizeFilenamesStub        func(context.Context, string) ([]prompt.Rename, error)
	normalizeFilenamesMutex       sync.RWMutex
	normalizeFilenamesArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	normalizeFilenamesReturns struct {
		result1 []prompt.Rename
		result2 error
	}
	normalizeFilenamesReturnsOnCall map[int]struct {
		result1 []prompt.Rename
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *RunnerPromptManager) ListQueued(arg1 context.Context) ([]prompt.Prompt, error) {
	fake.listQueuedMutex.Lock()
	ret, specificReturn := fake.listQueuedReturnsOnCall[len(fake.listQueuedArgsForCall)]
	fake.listQueuedArgsForCall = append(fake.listQueuedArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListQueuedStub
	fakeReturns := fake.listQueuedReturns
	fake.recordInvocation("ListQueued", []interface{}{arg1})
	fake.listQueuedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RunnerPromptManager) ListQueuedCallCount() int {
	fake.listQueuedMutex.RLock()
	defer fake.listQueuedMutex.RUnlock()
	return len(fake.listQueuedArgsForCall)
}

func (fake *RunnerPromptManager) ListQueuedCalls(stub func(context.Context) ([]prompt.Prompt, error)) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = stub
}

func (fake *RunnerPromptManager) ListQueuedArgsForCall(i int) context.Context {
	fake.listQueuedMutex.RLock()
	defer fake.listQueuedMutex.RUnlock()
	argsForCall := fake.listQueuedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *RunnerPromptManager) ListQueuedReturns(result1 []prompt.Prompt, result2 error) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = nil
	fake.listQueuedReturns = struct {
		result1 []prompt.Prompt
		result2 error
	}{result1, result2}
}

func (fake *RunnerPromptManager) ListQueuedReturnsOnCall(i int, result1 []prompt.Prompt, result2 error) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = nil
	if fake.listQueuedReturnsOnCall == nil {
		fake.listQueuedReturnsOnCall = make(map[int]struct {
			result1 []prompt.Prompt
			result2 error
		})
	}
	fake.listQueuedReturnsOnCall[i] = struct {
		result1 []prompt.Prompt
		result2 error
	}{result1, result2}
}

func (fake *RunnerPromptManager) Load(arg1 context.Context, arg2 string) (*prompt.PromptFile, error) {
	fake.loadMutex.Lock()
	ret, specificReturn := fake.loadReturnsOnCall[len(fake.loadArgsForCall)]
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LoadStub
	fakeReturns := fake.loadReturns
	fake.recordInvocation("Load", []interface{}{arg1, arg2})
	fake.loadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RunnerPromptManager) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *RunnerPromptManager) LoadCalls(stub func(context.Context, string) (*prompt.PromptFile, error)) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = stub
}

func (fake *RunnerPromptManager) LoadArgsForCall(i int) (context.Context, string) {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	argsForCall := fake.loadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RunnerPromptManager) LoadReturns(result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *RunnerPromptManager) LoadReturnsOnCall(i int, result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	if fake.loadReturnsOnCall == nil {
		fake.loadReturnsOnCall = make(map[int]struct {
			result1 *prompt.PromptFile
			result2 error
		})
	}
	fake.loadReturnsOnCall[i] = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *RunnerPromptManager) NormalizeFilenames(arg1 context.Context, arg2 string) ([]prompt.Rename, error) {
	fake.normalizeFilenamesMutex.Lock()
	ret, specificReturn := fake.normalizeFilenamesReturnsOnCall[len(fake.normalizeFilenamesArgsForCall)]
	fake.normalizeFilenamesArgsForCall = append(fake.normalizeFilenamesArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.NormalizeFilenamesStub
	fakeReturns := fake.normalizeFilenamesReturns
	fake.recordInvocation("NormalizeFilenames", []interface{}{arg1, arg2})
	fake.normalizeFilenamesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *RunnerPromptManager) NormalizeFilenamesCallCount() int {
	fake.normalizeFilenamesMutex.RLock()
	defer fake.normalizeFilenamesMutex.RUnlock()
	return len(fake.normalizeFilenamesArgsForCall)
}

func (fake *RunnerPromptManager) NormalizeFilenamesCalls(stub func(context.Context, string) ([]prompt.Rename, error)) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = stub
}

func (fake *RunnerPromptManager) NormalizeFilenamesArgsForCall(i int) (context.Context, string) {
	fake.normalizeFilenamesMutex.RLock()
	defer fake.normalizeFilenamesMutex.RUnlock()
	argsForCall := fake.normalizeFilenamesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *RunnerPromptManager) NormalizeFilenamesReturns(result1 []prompt.Rename, result2 error) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = nil
	fake.normalizeFilenamesReturns = struct {
		result1 []prompt.Rename
		result2 error
	}{result1, result2}
}

func (fake *RunnerPromptManager) NormalizeFilenamesReturnsOnCall(i int, result1 []prompt.Rename, result2 error) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = nil
	if fake.normalizeFilenamesReturnsOnCall == nil {
		fake.normalizeFilenamesReturnsOnCall = make(map[int]struct {
			result1 []prompt.Rename
			result2 error
		})
	}
	fake.normalizeFilenamesReturnsOnCall[i] = struct {
		result1 []prompt.Rename
		result2 error
	}{result1, result2}
}

func (fake *RunnerPromptManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RunnerPromptManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ runner.PromptManager = new(RunnerPromptManager)
