// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/scenario"
)

type ScenarioLister struct {
	FindStub        func(context.Context, string) ([]*scenario.ScenarioFile, error)
	findMutex       sync.RWMutex
	findArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	findReturns struct {
		result1 []*scenario.ScenarioFile
		result2 error
	}
	findReturnsOnCall map[int]struct {
		result1 []*scenario.ScenarioFile
		result2 error
	}
	ListStub        func(context.Context) ([]*scenario.ScenarioFile, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
		arg1 context.Context
	}
	listReturns struct {
		result1 []*scenario.ScenarioFile
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 []*scenario.ScenarioFile
		result2 error
	}
	SummaryStub        func(context.Context) (*scenario.Summary, error)
	summaryMutex       sync.RWMutex
	summaryArgsForCall []struct {
		arg1 context.Context
	}
	summaryReturns struct {
		result1 *scenario.Summary
		result2 error
	}
	summaryReturnsOnCall map[int]struct {
		result1 *scenario.Summary
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ScenarioLister) Find(arg1 context.Context, arg2 string) ([]*scenario.ScenarioFile, error) {
	fake.findMutex.Lock()
	ret, specificReturn := fake.findReturnsOnCall[len(fake.findArgsForCall)]
	fake.findArgsForCall = append(fake.findArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FindStub
	fakeReturns := fake.findReturns
	fake.recordInvocation("Find", []interface{}{arg1, arg2})
	fake.findMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ScenarioLister) FindCallCount() int {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return len(fake.findArgsForCall)
}

func (fake *ScenarioLister) FindCalls(stub func(context.Context, string) ([]*scenario.ScenarioFile, error)) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = stub
}

func (fake *ScenarioLister) FindArgsForCall(i int) (context.Context, string) {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	argsForCall := fake.findArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ScenarioLister) FindReturns(result1 []*scenario.ScenarioFile, result2 error) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	fake.findReturns = struct {
		result1 []*scenario.ScenarioFile
		result2 error
	}{result1, result2}
}

func (fake *ScenarioLister) FindReturnsOnCall(i int, result1 []*scenario.ScenarioFile, result2 error) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	if fake.findReturnsOnCall == nil {
		fake.findReturnsOnCall = make(map[int]struct {
			result1 []*scenario.ScenarioFile
			result2 error
		})
	}
	fake.findReturnsOnCall[i] = struct {
		result1 []*scenario.ScenarioFile
		result2 error
	}{result1, result2}
}

func (fake *ScenarioLister) List(arg1 context.Context) ([]*scenario.ScenarioFile, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{arg1})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ScenarioLister) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *ScenarioLister) ListCalls(stub func(context.Context) ([]*scenario.ScenarioFile, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *ScenarioLister) ListArgsForCall(i int) context.Context {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	argsForCall := fake.listArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ScenarioLister) ListReturns(result1 []*scenario.ScenarioFile, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []*scenario.ScenarioFile
		result2 error
	}{result1, result2}
}

func (fake *ScenarioLister) ListReturnsOnCall(i int, result1 []*scenario.ScenarioFile, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 []*scenario.ScenarioFile
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 []*scenario.ScenarioFile
		result2 error
	}{result1, result2}
}

func (fake *ScenarioLister) Summary(arg1 context.Context) (*scenario.Summary, error) {
	fake.summaryMutex.Lock()
	ret, specificReturn := fake.summaryReturnsOnCall[len(fake.summaryArgsForCall)]
	fake.summaryArgsForCall = append(fake.summaryArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SummaryStub
	fakeReturns := fake.summaryReturns
	fake.recordInvocation("Summary", []interface{}{arg1})
	fake.summaryMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ScenarioLister) SummaryCallCount() int {
	fake.summaryMutex.RLock()
	defer fake.summaryMutex.RUnlock()
	return len(fake.summaryArgsForCall)
}

func (fake *ScenarioLister) SummaryCalls(stub func(context.Context) (*scenario.Summary, error)) {
	fake.summaryMutex.Lock()
	defer fake.summaryMutex.Unlock()
	fake.SummaryStub = stub
}

func (fake *ScenarioLister) SummaryArgsForCall(i int) context.Context {
	fake.summaryMutex.RLock()
	defer fake.summaryMutex.RUnlock()
	argsForCall := fake.summaryArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ScenarioLister) SummaryReturns(result1 *scenario.Summary, result2 error) {
	fake.summaryMutex.Lock()
	defer fake.summaryMutex.Unlock()
	fake.SummaryStub = nil
	fake.summaryReturns = struct {
		result1 *scenario.Summary
		result2 error
	}{result1, result2}
}

func (fake *ScenarioLister) SummaryReturnsOnCall(i int, result1 *scenario.Summary, result2 error) {
	fake.summaryMutex.Lock()
	defer fake.summaryMutex.Unlock()
	fake.SummaryStub = nil
	if fake.summaryReturnsOnCall == nil {
		fake.summaryReturnsOnCall = make(map[int]struct {
			result1 *scenario.Summary
			result2 error
		})
	}
	fake.summaryReturnsOnCall[i] = struct {
		result1 *scenario.Summary
		result2 error
	}{result1, result2}
}

func (fake *ScenarioLister) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ScenarioLister) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ scenario.Lister = new(ScenarioLister)
