// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/server"
)

type Server struct {
	ListenAndServeStub        func(context.Context) error
	listenAndServeMutex       sync.RWMutex
	listenAndServeArgsForCall []struct {
		arg1 context.Context
	}
	listenAndServeReturns struct {
		result1 error
	}
	listenAndServeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Server) ListenAndServe(arg1 context.Context) error {
	fake.listenAndServeMutex.Lock()
	ret, specificReturn := fake.listenAndServeReturnsOnCall[len(fake.listenAndServeArgsForCall)]
	fake.listenAndServeArgsForCall = append(fake.listenAndServeArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListenAndServeStub
	fakeReturns := fake.listenAndServeReturns
	fake.recordInvocation("ListenAndServe", []interface{}{arg1})
	fake.listenAndServeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Server) ListenAndServeCallCount() int {
	fake.listenAndServeMutex.RLock()
	defer fake.listenAndServeMutex.RUnlock()
	return len(fake.listenAndServeArgsForCall)
}

func (fake *Server) ListenAndServeCalls(stub func(context.Context) error) {
	fake.listenAndServeMutex.Lock()
	defer fake.listenAndServeMutex.Unlock()
	fake.ListenAndServeStub = stub
}

func (fake *Server) ListenAndServeArgsForCall(i int) context.Context {
	fake.listenAndServeMutex.RLock()
	defer fake.listenAndServeMutex.RUnlock()
	argsForCall := fake.listenAndServeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Server) ListenAndServeReturns(result1 error) {
	fake.listenAndServeMutex.Lock()
	defer fake.listenAndServeMutex.Unlock()
	fake.ListenAndServeStub = nil
	fake.listenAndServeReturns = struct {
		result1 error
	}{result1}
}

func (fake *Server) ListenAndServeReturnsOnCall(i int, result1 error) {
	fake.listenAndServeMutex.Lock()
	defer fake.listenAndServeMutex.Unlock()
	fake.ListenAndServeStub = nil
	if fake.listenAndServeReturnsOnCall == nil {
		fake.listenAndServeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.listenAndServeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Server) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Server) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ server.Server = new(Server)
