// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/specsweeper"
)

type Sweeper struct {
	SweepStub        func(context.Context) (int, error)
	sweepMutex       sync.RWMutex
	sweepArgsForCall []struct {
		arg1 context.Context
	}
	sweepReturns struct {
		result1 int
		result2 error
	}
	sweepReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Sweeper) Sweep(arg1 context.Context) (int, error) {
	fake.sweepMutex.Lock()
	ret, specificReturn := fake.sweepReturnsOnCall[len(fake.sweepArgsForCall)]
	fake.sweepArgsForCall = append(fake.sweepArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SweepStub
	fakeReturns := fake.sweepReturns
	fake.recordInvocation("Sweep", []interface{}{arg1})
	fake.sweepMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Sweeper) SweepCallCount() int {
	fake.sweepMutex.RLock()
	defer fake.sweepMutex.RUnlock()
	return len(fake.sweepArgsForCall)
}

func (fake *Sweeper) SweepCalls(stub func(context.Context) (int, error)) {
	fake.sweepMutex.Lock()
	defer fake.sweepMutex.Unlock()
	fake.SweepStub = stub
}

func (fake *Sweeper) SweepArgsForCall(i int) context.Context {
	fake.sweepMutex.RLock()
	defer fake.sweepMutex.RUnlock()
	argsForCall := fake.sweepArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Sweeper) SweepReturns(result1 int, result2 error) {
	fake.sweepMutex.Lock()
	defer fake.sweepMutex.Unlock()
	fake.SweepStub = nil
	fake.sweepReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *Sweeper) SweepReturnsOnCall(i int, result1 int, result2 error) {
	fake.sweepMutex.Lock()
	defer fake.sweepMutex.Unlock()
	fake.SweepStub = nil
	if fake.sweepReturnsOnCall == nil {
		fake.sweepReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.sweepReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *Sweeper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Sweeper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ specsweeper.Sweeper = new(Sweeper)
