// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/spec"
)

type AutoCompleter struct {
	CheckAndCompleteStub        func(context.Context, string) error
	checkAndCompleteMutex       sync.RWMutex
	checkAndCompleteArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	checkAndCompleteReturns struct {
		result1 error
	}
	checkAndCompleteReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AutoCompleter) CheckAndComplete(arg1 context.Context, arg2 string) error {
	fake.checkAndCompleteMutex.Lock()
	ret, specificReturn := fake.checkAndCompleteReturnsOnCall[len(fake.checkAndCompleteArgsForCall)]
	fake.checkAndCompleteArgsForCall = append(fake.checkAndCompleteArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CheckAndCompleteStub
	fakeReturns := fake.checkAndCompleteReturns
	fake.recordInvocation("CheckAndComplete", []interface{}{arg1, arg2})
	fake.checkAndCompleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *AutoCompleter) CheckAndCompleteCallCount() int {
	fake.checkAndCompleteMutex.RLock()
	defer fake.checkAndCompleteMutex.RUnlock()
	return len(fake.checkAndCompleteArgsForCall)
}

func (fake *AutoCompleter) CheckAndCompleteCalls(stub func(context.Context, string) error) {
	fake.checkAndCompleteMutex.Lock()
	defer fake.checkAndCompleteMutex.Unlock()
	fake.CheckAndCompleteStub = stub
}

func (fake *AutoCompleter) CheckAndCompleteArgsForCall(i int) (context.Context, string) {
	fake.checkAndCompleteMutex.RLock()
	defer fake.checkAndCompleteMutex.RUnlock()
	argsForCall := fake.checkAndCompleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AutoCompleter) CheckAndCompleteReturns(result1 error) {
	fake.checkAndCompleteMutex.Lock()
	defer fake.checkAndCompleteMutex.Unlock()
	fake.CheckAndCompleteStub = nil
	fake.checkAndCompleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *AutoCompleter) CheckAndCompleteReturnsOnCall(i int, result1 error) {
	fake.checkAndCompleteMutex.Lock()
	defer fake.checkAndCompleteMutex.Unlock()
	fake.CheckAndCompleteStub = nil
	if fake.checkAndCompleteReturnsOnCall == nil {
		fake.checkAndCompleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.checkAndCompleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *AutoCompleter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AutoCompleter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ spec.AutoCompleter = new(AutoCompleter)
