// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/slugmigrator"
)

type SpecSlugMigrator struct {
	MigrateDirsStub        func(context.Context, []string) error
	migrateDirsMutex       sync.RWMutex
	migrateDirsArgsForCall []struct {
		arg1 context.Context
		arg2 []string
	}
	migrateDirsReturns struct {
		result1 error
	}
	migrateDirsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *SpecSlugMigrator) MigrateDirs(arg1 context.Context, arg2 []string) error {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.migrateDirsMutex.Lock()
	ret, specificReturn := fake.migrateDirsReturnsOnCall[len(fake.migrateDirsArgsForCall)]
	fake.migrateDirsArgsForCall = append(fake.migrateDirsArgsForCall, struct {
		arg1 context.Context
		arg2 []string
	}{arg1, arg2Copy})
	stub := fake.MigrateDirsStub
	fakeReturns := fake.migrateDirsReturns
	fake.recordInvocation("MigrateDirs", []interface{}{arg1, arg2Copy})
	fake.migrateDirsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *SpecSlugMigrator) MigrateDirsCallCount() int {
	fake.migrateDirsMutex.RLock()
	defer fake.migrateDirsMutex.RUnlock()
	return len(fake.migrateDirsArgsForCall)
}

func (fake *SpecSlugMigrator) MigrateDirsCalls(stub func(context.Context, []string) error) {
	fake.migrateDirsMutex.Lock()
	defer fake.migrateDirsMutex.Unlock()
	fake.MigrateDirsStub = stub
}

func (fake *SpecSlugMigrator) MigrateDirsArgsForCall(i int) (context.Context, []string) {
	fake.migrateDirsMutex.RLock()
	defer fake.migrateDirsMutex.RUnlock()
	argsForCall := fake.migrateDirsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *SpecSlugMigrator) MigrateDirsReturns(result1 error) {
	fake.migrateDirsMutex.Lock()
	defer fake.migrateDirsMutex.Unlock()
	fake.MigrateDirsStub = nil
	fake.migrateDirsReturns = struct {
		result1 error
	}{result1}
}

func (fake *SpecSlugMigrator) MigrateDirsReturnsOnCall(i int, result1 error) {
	fake.migrateDirsMutex.Lock()
	defer fake.migrateDirsMutex.Unlock()
	fake.MigrateDirsStub = nil
	if fake.migrateDirsReturnsOnCall == nil {
		fake.migrateDirsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.migrateDirsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *SpecSlugMigrator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *SpecSlugMigrator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ slugmigrator.Migrator = new(SpecSlugMigrator)
