// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/status"
)

type Checker struct {
	GetCompletedPromptsStub        func(context.Context, int) ([]status.CompletedPrompt, error)
	getCompletedPromptsMutex       sync.RWMutex
	getCompletedPromptsArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	getCompletedPromptsReturns struct {
		result1 []status.CompletedPrompt
		result2 error
	}
	getCompletedPromptsReturnsOnCall map[int]struct {
		result1 []status.CompletedPrompt
		result2 error
	}
	GetQueuedPromptsStub        func(context.Context) ([]status.QueuedPrompt, error)
	getQueuedPromptsMutex       sync.RWMutex
	getQueuedPromptsArgsForCall []struct {
		arg1 context.Context
	}
	getQueuedPromptsReturns struct {
		result1 []status.QueuedPrompt
		result2 error
	}
	getQueuedPromptsReturnsOnCall map[int]struct {
		result1 []status.QueuedPrompt
		result2 error
	}
	GetStatusStub        func(context.Context) (*status.Status, error)
	getStatusMutex       sync.RWMutex
	getStatusArgsForCall []struct {
		arg1 context.Context
	}
	getStatusReturns struct {
		result1 *status.Status
		result2 error
	}
	getStatusReturnsOnCall map[int]struct {
		result1 *status.Status
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Checker) GetCompletedPrompts(arg1 context.Context, arg2 int) ([]status.CompletedPrompt, error) {
	fake.getCompletedPromptsMutex.Lock()
	ret, specificReturn := fake.getCompletedPromptsReturnsOnCall[len(fake.getCompletedPromptsArgsForCall)]
	fake.getCompletedPromptsArgsForCall = append(fake.getCompletedPromptsArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.GetCompletedPromptsStub
	fakeReturns := fake.getCompletedPromptsReturns
	fake.recordInvocation("GetCompletedPrompts", []interface{}{arg1, arg2})
	fake.getCompletedPromptsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Checker) GetCompletedPromptsCallCount() int {
	fake.getCompletedPromptsMutex.RLock()
	defer fake.getCompletedPromptsMutex.RUnlock()
	return len(fake.getCompletedPromptsArgsForCall)
}

func (fake *Checker) GetCompletedPromptsCalls(stub func(context.Context, int) ([]status.CompletedPrompt, error)) {
	fake.getCompletedPromptsMutex.Lock()
	defer fake.getCompletedPromptsMutex.Unlock()
	fake.GetCompletedPromptsStub = stub
}

func (fake *Checker) GetCompletedPromptsArgsForCall(i int) (context.Context, int) {
	fake.getCompletedPromptsMutex.RLock()
	defer fake.getCompletedPromptsMutex.RUnlock()
	argsForCall := fake.getCompletedPromptsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Checker) GetCompletedPromptsReturns(result1 []status.CompletedPrompt, result2 error) {
	fake.getCompletedPromptsMutex.Lock()
	defer fake.getCompletedPromptsMutex.Unlock()
	fake.GetCompletedPromptsStub = nil
	fake.getCompletedPromptsReturns = struct {
		result1 []status.CompletedPrompt
		result2 error
	}{result1, result2}
}

func (fake *Checker) GetCompletedPromptsReturnsOnCall(i int, result1 []status.CompletedPrompt, result2 error) {
	fake.getCompletedPromptsMutex.Lock()
	defer fake.getCompletedPromptsMutex.Unlock()
	fake.GetCompletedPromptsStub = nil
	if fake.getCompletedPromptsReturnsOnCall == nil {
		fake.getCompletedPromptsReturnsOnCall = make(map[int]struct {
			result1 []status.CompletedPrompt
			result2 error
		})
	}
	fake.getCompletedPromptsReturnsOnCall[i] = struct {
		result1 []status.CompletedPrompt
		result2 error
	}{result1, result2}
}

func (fake *Checker) GetQueuedPrompts(arg1 context.Context) ([]status.QueuedPrompt, error) {
	fake.getQueuedPromptsMutex.Lock()
	ret, specificReturn := fake.getQueuedPromptsReturnsOnCall[len(fake.getQueuedPromptsArgsForCall)]
	fake.getQueuedPromptsArgsForCall = append(fake.getQueuedPromptsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetQueuedPromptsStub
	fakeReturns := fake.getQueuedPromptsReturns
	fake.recordInvocation("GetQueuedPrompts", []interface{}{arg1})
	fake.getQueuedPromptsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Checker) GetQueuedPromptsCallCount() int {
	fake.getQueuedPromptsMutex.RLock()
	defer fake.getQueuedPromptsMutex.RUnlock()
	return len(fake.getQueuedPromptsArgsForCall)
}

func (fake *Checker) GetQueuedPromptsCalls(stub func(context.Context) ([]status.QueuedPrompt, error)) {
	fake.getQueuedPromptsMutex.Lock()
	defer fake.getQueuedPromptsMutex.Unlock()
	fake.GetQueuedPromptsStub = stub
}

func (fake *Checker) GetQueuedPromptsArgsForCall(i int) context.Context {
	fake.getQueuedPromptsMutex.RLock()
	defer fake.getQueuedPromptsMutex.RUnlock()
	argsForCall := fake.getQueuedPromptsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Checker) GetQueuedPromptsReturns(result1 []status.QueuedPrompt, result2 error) {
	fake.getQueuedPromptsMutex.Lock()
	defer fake.getQueuedPromptsMutex.Unlock()
	fake.GetQueuedPromptsStub = nil
	fake.getQueuedPromptsReturns = struct {
		result1 []status.QueuedPrompt
		result2 error
	}{result1, result2}
}

func (fake *Checker) GetQueuedPromptsReturnsOnCall(i int, result1 []status.QueuedPrompt, result2 error) {
	fake.getQueuedPromptsMutex.Lock()
	defer fake.getQueuedPromptsMutex.Unlock()
	fake.GetQueuedPromptsStub = nil
	if fake.getQueuedPromptsReturnsOnCall == nil {
		fake.getQueuedPromptsReturnsOnCall = make(map[int]struct {
			result1 []status.QueuedPrompt
			result2 error
		})
	}
	fake.getQueuedPromptsReturnsOnCall[i] = struct {
		result1 []status.QueuedPrompt
		result2 error
	}{result1, result2}
}

func (fake *Checker) GetStatus(arg1 context.Context) (*status.Status, error) {
	fake.getStatusMutex.Lock()
	ret, specificReturn := fake.getStatusReturnsOnCall[len(fake.getStatusArgsForCall)]
	fake.getStatusArgsForCall = append(fake.getStatusArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetStatusStub
	fakeReturns := fake.getStatusReturns
	fake.recordInvocation("GetStatus", []interface{}{arg1})
	fake.getStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Checker) GetStatusCallCount() int {
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	return len(fake.getStatusArgsForCall)
}

func (fake *Checker) GetStatusCalls(stub func(context.Context) (*status.Status, error)) {
	fake.getStatusMutex.Lock()
	defer fake.getStatusMutex.Unlock()
	fake.GetStatusStub = stub
}

func (fake *Checker) GetStatusArgsForCall(i int) context.Context {
	fake.getStatusMutex.RLock()
	defer fake.getStatusMutex.RUnlock()
	argsForCall := fake.getStatusArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Checker) GetStatusReturns(result1 *status.Status, result2 error) {
	fake.getStatusMutex.Lock()
	defer fake.getStatusMutex.Unlock()
	fake.GetStatusStub = nil
	fake.getStatusReturns = struct {
		result1 *status.Status
		result2 error
	}{result1, result2}
}

func (fake *Checker) GetStatusReturnsOnCall(i int, result1 *status.Status, result2 error) {
	fake.getStatusMutex.Lock()
	defer fake.getStatusMutex.Unlock()
	fake.GetStatusStub = nil
	if fake.getStatusReturnsOnCall == nil {
		fake.getStatusReturnsOnCall = make(map[int]struct {
			result1 *status.Status
			result2 error
		})
	}
	fake.getStatusReturnsOnCall[i] = struct {
		result1 *status.Status
		result2 error
	}{result1, result2}
}

func (fake *Checker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Checker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ status.Checker = new(Checker)
