// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/dark-factory/pkg/status"
)

type Formatter struct {
	FormatStub        func(*status.Status) string
	formatMutex       sync.RWMutex
	formatArgsForCall []struct {
		arg1 *status.Status
	}
	formatReturns struct {
		result1 string
	}
	formatReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Formatter) Format(arg1 *status.Status) string {
	fake.formatMutex.Lock()
	ret, specificReturn := fake.formatReturnsOnCall[len(fake.formatArgsForCall)]
	fake.formatArgsForCall = append(fake.formatArgsForCall, struct {
		arg1 *status.Status
	}{arg1})
	stub := fake.FormatStub
	fakeReturns := fake.formatReturns
	fake.recordInvocation("Format", []interface{}{arg1})
	fake.formatMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Formatter) FormatCallCount() int {
	fake.formatMutex.RLock()
	defer fake.formatMutex.RUnlock()
	return len(fake.formatArgsForCall)
}

func (fake *Formatter) FormatCalls(stub func(*status.Status) string) {
	fake.formatMutex.Lock()
	defer fake.formatMutex.Unlock()
	fake.FormatStub = stub
}

func (fake *Formatter) FormatArgsForCall(i int) *status.Status {
	fake.formatMutex.RLock()
	defer fake.formatMutex.RUnlock()
	argsForCall := fake.formatArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Formatter) FormatReturns(result1 string) {
	fake.formatMutex.Lock()
	defer fake.formatMutex.Unlock()
	fake.FormatStub = nil
	fake.formatReturns = struct {
		result1 string
	}{result1}
}

func (fake *Formatter) FormatReturnsOnCall(i int, result1 string) {
	fake.formatMutex.Lock()
	defer fake.formatMutex.Unlock()
	fake.FormatStub = nil
	if fake.formatReturnsOnCall == nil {
		fake.formatReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.formatReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *Formatter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Formatter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ status.Formatter = new(Formatter)
