// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/prompt"
	"github.com/bborbe/dark-factory/pkg/status"
)

type StatusPromptManager struct {
	FindCommittingStub        func(context.Context) ([]string, error)
	findCommittingMutex       sync.RWMutex
	findCommittingArgsForCall []struct {
		arg1 context.Context
	}
	findCommittingReturns struct {
		result1 []string
		result2 error
	}
	findCommittingReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	HasExecutingStub        func(context.Context) bool
	hasExecutingMutex       sync.RWMutex
	hasExecutingArgsForCall []struct {
		arg1 context.Context
	}
	hasExecutingReturns struct {
		result1 bool
	}
	hasExecutingReturnsOnCall map[int]struct {
		result1 bool
	}
	ListQueuedStub        func(context.Context) ([]prompt.Prompt, error)
	listQueuedMutex       sync.RWMutex
	listQueuedArgsForCall []struct {
		arg1 context.Context
	}
	listQueuedReturns struct {
		result1 []prompt.Prompt
		result2 error
	}
	listQueuedReturnsOnCall map[int]struct {
		result1 []prompt.Prompt
		result2 error
	}
	ReadFrontmatterStub        func(context.Context, string) (*prompt.Frontmatter, error)
	readFrontmatterMutex       sync.RWMutex
	readFrontmatterArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	readFrontmatterReturns struct {
		result1 *prompt.Frontmatter
		result2 error
	}
	readFrontmatterReturnsOnCall map[int]struct {
		result1 *prompt.Frontmatter
		result2 error
	}
	TitleStub        func(context.Context, string) (string, error)
	titleMutex       sync.RWMutex
	titleArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	titleReturns struct {
		result1 string
		result2 error
	}
	titleReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *StatusPromptManager) FindCommitting(arg1 context.Context) ([]string, error) {
	fake.findCommittingMutex.Lock()
	ret, specificReturn := fake.findCommittingReturnsOnCall[len(fake.findCommittingArgsForCall)]
	fake.findCommittingArgsForCall = append(fake.findCommittingArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.FindCommittingStub
	fakeReturns := fake.findCommittingReturns
	fake.recordInvocation("FindCommitting", []interface{}{arg1})
	fake.findCommittingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *StatusPromptManager) FindCommittingCallCount() int {
	fake.findCommittingMutex.RLock()
	defer fake.findCommittingMutex.RUnlock()
	return len(fake.findCommittingArgsForCall)
}

func (fake *StatusPromptManager) FindCommittingCalls(stub func(context.Context) ([]string, error)) {
	fake.findCommittingMutex.Lock()
	defer fake.findCommittingMutex.Unlock()
	fake.FindCommittingStub = stub
}

func (fake *StatusPromptManager) FindCommittingArgsForCall(i int) context.Context {
	fake.findCommittingMutex.RLock()
	defer fake.findCommittingMutex.RUnlock()
	argsForCall := fake.findCommittingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *StatusPromptManager) FindCommittingReturns(result1 []string, result2 error) {
	fake.findCommittingMutex.Lock()
	defer fake.findCommittingMutex.Unlock()
	fake.FindCommittingStub = nil
	fake.findCommittingReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *StatusPromptManager) FindCommittingReturnsOnCall(i int, result1 []string, result2 error) {
	fake.findCommittingMutex.Lock()
	defer fake.findCommittingMutex.Unlock()
	fake.FindCommittingStub = nil
	if fake.findCommittingReturnsOnCall == nil {
		fake.findCommittingReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.findCommittingReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *StatusPromptManager) HasExecuting(arg1 context.Context) bool {
	fake.hasExecutingMutex.Lock()
	ret, specificReturn := fake.hasExecutingReturnsOnCall[len(fake.hasExecutingArgsForCall)]
	fake.hasExecutingArgsForCall = append(fake.hasExecutingArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.HasExecutingStub
	fakeReturns := fake.hasExecutingReturns
	fake.recordInvocation("HasExecuting", []interface{}{arg1})
	fake.hasExecutingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *StatusPromptManager) HasExecutingCallCount() int {
	fake.hasExecutingMutex.RLock()
	defer fake.hasExecutingMutex.RUnlock()
	return len(fake.hasExecutingArgsForCall)
}

func (fake *StatusPromptManager) HasExecutingCalls(stub func(context.Context) bool) {
	fake.hasExecutingMutex.Lock()
	defer fake.hasExecutingMutex.Unlock()
	fake.HasExecutingStub = stub
}

func (fake *StatusPromptManager) HasExecutingArgsForCall(i int) context.Context {
	fake.hasExecutingMutex.RLock()
	defer fake.hasExecutingMutex.RUnlock()
	argsForCall := fake.hasExecutingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *StatusPromptManager) HasExecutingReturns(result1 bool) {
	fake.hasExecutingMutex.Lock()
	defer fake.hasExecutingMutex.Unlock()
	fake.HasExecutingStub = nil
	fake.hasExecutingReturns = struct {
		result1 bool
	}{result1}
}

func (fake *StatusPromptManager) HasExecutingReturnsOnCall(i int, result1 bool) {
	fake.hasExecutingMutex.Lock()
	defer fake.hasExecutingMutex.Unlock()
	fake.HasExecutingStub = nil
	if fake.hasExecutingReturnsOnCall == nil {
		fake.hasExecutingReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.hasExecutingReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *StatusPromptManager) ListQueued(arg1 context.Context) ([]prompt.Prompt, error) {
	fake.listQueuedMutex.Lock()
	ret, specificReturn := fake.listQueuedReturnsOnCall[len(fake.listQueuedArgsForCall)]
	fake.listQueuedArgsForCall = append(fake.listQueuedArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListQueuedStub
	fakeReturns := fake.listQueuedReturns
	fake.recordInvocation("ListQueued", []interface{}{arg1})
	fake.listQueuedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *StatusPromptManager) ListQueuedCallCount() int {
	fake.listQueuedMutex.RLock()
	defer fake.listQueuedMutex.RUnlock()
	return len(fake.listQueuedArgsForCall)
}

func (fake *StatusPromptManager) ListQueuedCalls(stub func(context.Context) ([]prompt.Prompt, error)) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = stub
}

func (fake *StatusPromptManager) ListQueuedArgsForCall(i int) context.Context {
	fake.listQueuedMutex.RLock()
	defer fake.listQueuedMutex.RUnlock()
	argsForCall := fake.listQueuedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *StatusPromptManager) ListQueuedReturns(result1 []prompt.Prompt, result2 error) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = nil
	fake.listQueuedReturns = struct {
		result1 []prompt.Prompt
		result2 error
	}{result1, result2}
}

func (fake *StatusPromptManager) ListQueuedReturnsOnCall(i int, result1 []prompt.Prompt, result2 error) {
	fake.listQueuedMutex.Lock()
	defer fake.listQueuedMutex.Unlock()
	fake.ListQueuedStub = nil
	if fake.listQueuedReturnsOnCall == nil {
		fake.listQueuedReturnsOnCall = make(map[int]struct {
			result1 []prompt.Prompt
			result2 error
		})
	}
	fake.listQueuedReturnsOnCall[i] = struct {
		result1 []prompt.Prompt
		result2 error
	}{result1, result2}
}

func (fake *StatusPromptManager) ReadFrontmatter(arg1 context.Context, arg2 string) (*prompt.Frontmatter, error) {
	fake.readFrontmatterMutex.Lock()
	ret, specificReturn := fake.readFrontmatterReturnsOnCall[len(fake.readFrontmatterArgsForCall)]
	fake.readFrontmatterArgsForCall = append(fake.readFrontmatterArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ReadFrontmatterStub
	fakeReturns := fake.readFrontmatterReturns
	fake.recordInvocation("ReadFrontmatter", []interface{}{arg1, arg2})
	fake.readFrontmatterMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *StatusPromptManager) ReadFrontmatterCallCount() int {
	fake.readFrontmatterMutex.RLock()
	defer fake.readFrontmatterMutex.RUnlock()
	return len(fake.readFrontmatterArgsForCall)
}

func (fake *StatusPromptManager) ReadFrontmatterCalls(stub func(context.Context, string) (*prompt.Frontmatter, error)) {
	fake.readFrontmatterMutex.Lock()
	defer fake.readFrontmatterMutex.Unlock()
	fake.ReadFrontmatterStub = stub
}

func (fake *StatusPromptManager) ReadFrontmatterArgsForCall(i int) (context.Context, string) {
	fake.readFrontmatterMutex.RLock()
	defer fake.readFrontmatterMutex.RUnlock()
	argsForCall := fake.readFrontmatterArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *StatusPromptManager) ReadFrontmatterReturns(result1 *prompt.Frontmatter, result2 error) {
	fake.readFrontmatterMutex.Lock()
	defer fake.readFrontmatterMutex.Unlock()
	fake.ReadFrontmatterStub = nil
	fake.readFrontmatterReturns = struct {
		result1 *prompt.Frontmatter
		result2 error
	}{result1, result2}
}

func (fake *StatusPromptManager) ReadFrontmatterReturnsOnCall(i int, result1 *prompt.Frontmatter, result2 error) {
	fake.readFrontmatterMutex.Lock()
	defer fake.readFrontmatterMutex.Unlock()
	fake.ReadFrontmatterStub = nil
	if fake.readFrontmatterReturnsOnCall == nil {
		fake.readFrontmatterReturnsOnCall = make(map[int]struct {
			result1 *prompt.Frontmatter
			result2 error
		})
	}
	fake.readFrontmatterReturnsOnCall[i] = struct {
		result1 *prompt.Frontmatter
		result2 error
	}{result1, result2}
}

func (fake *StatusPromptManager) Title(arg1 context.Context, arg2 string) (string, error) {
	fake.titleMutex.Lock()
	ret, specificReturn := fake.titleReturnsOnCall[len(fake.titleArgsForCall)]
	fake.titleArgsForCall = append(fake.titleArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.TitleStub
	fakeReturns := fake.titleReturns
	fake.recordInvocation("Title", []interface{}{arg1, arg2})
	fake.titleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *StatusPromptManager) TitleCallCount() int {
	fake.titleMutex.RLock()
	defer fake.titleMutex.RUnlock()
	return len(fake.titleArgsForCall)
}

func (fake *StatusPromptManager) TitleCalls(stub func(context.Context, string) (string, error)) {
	fake.titleMutex.Lock()
	defer fake.titleMutex.Unlock()
	fake.TitleStub = stub
}

func (fake *StatusPromptManager) TitleArgsForCall(i int) (context.Context, string) {
	fake.titleMutex.RLock()
	defer fake.titleMutex.RUnlock()
	argsForCall := fake.titleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *StatusPromptManager) TitleReturns(result1 string, result2 error) {
	fake.titleMutex.Lock()
	defer fake.titleMutex.Unlock()
	fake.TitleStub = nil
	fake.titleReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *StatusPromptManager) TitleReturnsOnCall(i int, result1 string, result2 error) {
	fake.titleMutex.Lock()
	defer fake.titleMutex.Unlock()
	fake.TitleStub = nil
	if fake.titleReturnsOnCall == nil {
		fake.titleReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.titleReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *StatusPromptManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *StatusPromptManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ status.PromptManager = new(StatusPromptManager)
