// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/subproc"
)

type SubprocRunner struct {
	RunWithWarnAndTimeoutStub        func(context.Context, string, string, ...string) ([]byte, error)
	runWithWarnAndTimeoutMutex       sync.RWMutex
	runWithWarnAndTimeoutArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 []string
	}
	runWithWarnAndTimeoutReturns struct {
		result1 []byte
		result2 error
	}
	runWithWarnAndTimeoutReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	RunWithWarnAndTimeoutDirStub        func(context.Context, string, string, string, ...string) ([]byte, error)
	runWithWarnAndTimeoutDirMutex       sync.RWMutex
	runWithWarnAndTimeoutDirArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 []string
	}
	runWithWarnAndTimeoutDirReturns struct {
		result1 []byte
		result2 error
	}
	runWithWarnAndTimeoutDirReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *SubprocRunner) RunWithWarnAndTimeout(arg1 context.Context, arg2 string, arg3 string, arg4 ...string) ([]byte, error) {
	fake.runWithWarnAndTimeoutMutex.Lock()
	ret, specificReturn := fake.runWithWarnAndTimeoutReturnsOnCall[len(fake.runWithWarnAndTimeoutArgsForCall)]
	fake.runWithWarnAndTimeoutArgsForCall = append(fake.runWithWarnAndTimeoutArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 []string
	}{arg1, arg2, arg3, arg4})
	stub := fake.RunWithWarnAndTimeoutStub
	fakeReturns := fake.runWithWarnAndTimeoutReturns
	fake.recordInvocation("RunWithWarnAndTimeout", []interface{}{arg1, arg2, arg3, arg4})
	fake.runWithWarnAndTimeoutMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *SubprocRunner) RunWithWarnAndTimeoutCallCount() int {
	fake.runWithWarnAndTimeoutMutex.RLock()
	defer fake.runWithWarnAndTimeoutMutex.RUnlock()
	return len(fake.runWithWarnAndTimeoutArgsForCall)
}

func (fake *SubprocRunner) RunWithWarnAndTimeoutCalls(stub func(context.Context, string, string, ...string) ([]byte, error)) {
	fake.runWithWarnAndTimeoutMutex.Lock()
	defer fake.runWithWarnAndTimeoutMutex.Unlock()
	fake.RunWithWarnAndTimeoutStub = stub
}

func (fake *SubprocRunner) RunWithWarnAndTimeoutArgsForCall(i int) (context.Context, string, string, []string) {
	fake.runWithWarnAndTimeoutMutex.RLock()
	defer fake.runWithWarnAndTimeoutMutex.RUnlock()
	argsForCall := fake.runWithWarnAndTimeoutArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *SubprocRunner) RunWithWarnAndTimeoutReturns(result1 []byte, result2 error) {
	fake.runWithWarnAndTimeoutMutex.Lock()
	defer fake.runWithWarnAndTimeoutMutex.Unlock()
	fake.RunWithWarnAndTimeoutStub = nil
	fake.runWithWarnAndTimeoutReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *SubprocRunner) RunWithWarnAndTimeoutReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.runWithWarnAndTimeoutMutex.Lock()
	defer fake.runWithWarnAndTimeoutMutex.Unlock()
	fake.RunWithWarnAndTimeoutStub = nil
	if fake.runWithWarnAndTimeoutReturnsOnCall == nil {
		fake.runWithWarnAndTimeoutReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.runWithWarnAndTimeoutReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *SubprocRunner) RunWithWarnAndTimeoutDir(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 ...string) ([]byte, error) {
	fake.runWithWarnAndTimeoutDirMutex.Lock()
	ret, specificReturn := fake.runWithWarnAndTimeoutDirReturnsOnCall[len(fake.runWithWarnAndTimeoutDirArgsForCall)]
	fake.runWithWarnAndTimeoutDirArgsForCall = append(fake.runWithWarnAndTimeoutDirArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 []string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.RunWithWarnAndTimeoutDirStub
	fakeReturns := fake.runWithWarnAndTimeoutDirReturns
	fake.recordInvocation("RunWithWarnAndTimeoutDir", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.runWithWarnAndTimeoutDirMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *SubprocRunner) RunWithWarnAndTimeoutDirCallCount() int {
	fake.runWithWarnAndTimeoutDirMutex.RLock()
	defer fake.runWithWarnAndTimeoutDirMutex.RUnlock()
	return len(fake.runWithWarnAndTimeoutDirArgsForCall)
}

func (fake *SubprocRunner) RunWithWarnAndTimeoutDirCalls(stub func(context.Context, string, string, string, ...string) ([]byte, error)) {
	fake.runWithWarnAndTimeoutDirMutex.Lock()
	defer fake.runWithWarnAndTimeoutDirMutex.Unlock()
	fake.RunWithWarnAndTimeoutDirStub = stub
}

func (fake *SubprocRunner) RunWithWarnAndTimeoutDirArgsForCall(i int) (context.Context, string, string, string, []string) {
	fake.runWithWarnAndTimeoutDirMutex.RLock()
	defer fake.runWithWarnAndTimeoutDirMutex.RUnlock()
	argsForCall := fake.runWithWarnAndTimeoutDirArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *SubprocRunner) RunWithWarnAndTimeoutDirReturns(result1 []byte, result2 error) {
	fake.runWithWarnAndTimeoutDirMutex.Lock()
	defer fake.runWithWarnAndTimeoutDirMutex.Unlock()
	fake.RunWithWarnAndTimeoutDirStub = nil
	fake.runWithWarnAndTimeoutDirReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *SubprocRunner) RunWithWarnAndTimeoutDirReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.runWithWarnAndTimeoutDirMutex.Lock()
	defer fake.runWithWarnAndTimeoutDirMutex.Unlock()
	fake.RunWithWarnAndTimeoutDirStub = nil
	if fake.runWithWarnAndTimeoutDirReturnsOnCall == nil {
		fake.runWithWarnAndTimeoutDirReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.runWithWarnAndTimeoutDirReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *SubprocRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *SubprocRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ subproc.Runner = new(SubprocRunner)
