// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/prompt"
	"github.com/bborbe/dark-factory/pkg/watcher"
)

type WatcherPromptManager struct {
	LoadStub        func(context.Context, string) (*prompt.PromptFile, error)
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	loadReturns struct {
		result1 *prompt.PromptFile
		result2 error
	}
	loadReturnsOnCall map[int]struct {
		result1 *prompt.PromptFile
		result2 error
	}
	NormalizeFilenamesStub        func(context.Context, string) ([]prompt.Rename, error)
	normalizeFilenamesMutex       sync.RWMutex
	normalizeFilenamesArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	normalizeFilenamesReturns struct {
		result1 []prompt.Rename
		result2 error
	}
	normalizeFilenamesReturnsOnCall map[int]struct {
		result1 []prompt.Rename
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *WatcherPromptManager) Load(arg1 context.Context, arg2 string) (*prompt.PromptFile, error) {
	fake.loadMutex.Lock()
	ret, specificReturn := fake.loadReturnsOnCall[len(fake.loadArgsForCall)]
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LoadStub
	fakeReturns := fake.loadReturns
	fake.recordInvocation("Load", []interface{}{arg1, arg2})
	fake.loadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *WatcherPromptManager) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *WatcherPromptManager) LoadCalls(stub func(context.Context, string) (*prompt.PromptFile, error)) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = stub
}

func (fake *WatcherPromptManager) LoadArgsForCall(i int) (context.Context, string) {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	argsForCall := fake.loadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *WatcherPromptManager) LoadReturns(result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *WatcherPromptManager) LoadReturnsOnCall(i int, result1 *prompt.PromptFile, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	if fake.loadReturnsOnCall == nil {
		fake.loadReturnsOnCall = make(map[int]struct {
			result1 *prompt.PromptFile
			result2 error
		})
	}
	fake.loadReturnsOnCall[i] = struct {
		result1 *prompt.PromptFile
		result2 error
	}{result1, result2}
}

func (fake *WatcherPromptManager) NormalizeFilenames(arg1 context.Context, arg2 string) ([]prompt.Rename, error) {
	fake.normalizeFilenamesMutex.Lock()
	ret, specificReturn := fake.normalizeFilenamesReturnsOnCall[len(fake.normalizeFilenamesArgsForCall)]
	fake.normalizeFilenamesArgsForCall = append(fake.normalizeFilenamesArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.NormalizeFilenamesStub
	fakeReturns := fake.normalizeFilenamesReturns
	fake.recordInvocation("NormalizeFilenames", []interface{}{arg1, arg2})
	fake.normalizeFilenamesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *WatcherPromptManager) NormalizeFilenamesCallCount() int {
	fake.normalizeFilenamesMutex.RLock()
	defer fake.normalizeFilenamesMutex.RUnlock()
	return len(fake.normalizeFilenamesArgsForCall)
}

func (fake *WatcherPromptManager) NormalizeFilenamesCalls(stub func(context.Context, string) ([]prompt.Rename, error)) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = stub
}

func (fake *WatcherPromptManager) NormalizeFilenamesArgsForCall(i int) (context.Context, string) {
	fake.normalizeFilenamesMutex.RLock()
	defer fake.normalizeFilenamesMutex.RUnlock()
	argsForCall := fake.normalizeFilenamesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *WatcherPromptManager) NormalizeFilenamesReturns(result1 []prompt.Rename, result2 error) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = nil
	fake.normalizeFilenamesReturns = struct {
		result1 []prompt.Rename
		result2 error
	}{result1, result2}
}

func (fake *WatcherPromptManager) NormalizeFilenamesReturnsOnCall(i int, result1 []prompt.Rename, result2 error) {
	fake.normalizeFilenamesMutex.Lock()
	defer fake.normalizeFilenamesMutex.Unlock()
	fake.NormalizeFilenamesStub = nil
	if fake.normalizeFilenamesReturnsOnCall == nil {
		fake.normalizeFilenamesReturnsOnCall = make(map[int]struct {
			result1 []prompt.Rename
			result2 error
		})
	}
	fake.normalizeFilenamesReturnsOnCall[i] = struct {
		result1 []prompt.Rename
		result2 error
	}{result1, result2}
}

func (fake *WatcherPromptManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *WatcherPromptManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ watcher.PromptManager = new(WatcherPromptManager)
