// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/dark-factory/pkg/processor"
	"github.com/bborbe/dark-factory/pkg/prompt"
)

type WorkflowExecutor struct {
	CleanupOnErrorStub        func(context.Context)
	cleanupOnErrorMutex       sync.RWMutex
	cleanupOnErrorArgsForCall []struct {
		arg1 context.Context
	}
	CompleteStub        func(context.Context, context.Context, *prompt.PromptFile, string, string, string) error
	completeMutex       sync.RWMutex
	completeArgsForCall []struct {
		arg1 context.Context
		arg2 context.Context
		arg3 *prompt.PromptFile
		arg4 string
		arg5 string
		arg6 string
	}
	completeReturns struct {
		result1 error
	}
	completeReturnsOnCall map[int]struct {
		result1 error
	}
	ReconstructStateStub        func(context.Context, prompt.BaseName, *prompt.PromptFile) (bool, error)
	reconstructStateMutex       sync.RWMutex
	reconstructStateArgsForCall []struct {
		arg1 context.Context
		arg2 prompt.BaseName
		arg3 *prompt.PromptFile
	}
	reconstructStateReturns struct {
		result1 bool
		result2 error
	}
	reconstructStateReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	SetupStub        func(context.Context, prompt.BaseName, *prompt.PromptFile) error
	setupMutex       sync.RWMutex
	setupArgsForCall []struct {
		arg1 context.Context
		arg2 prompt.BaseName
		arg3 *prompt.PromptFile
	}
	setupReturns struct {
		result1 error
	}
	setupReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *WorkflowExecutor) CleanupOnError(arg1 context.Context) {
	fake.cleanupOnErrorMutex.Lock()
	fake.cleanupOnErrorArgsForCall = append(fake.cleanupOnErrorArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CleanupOnErrorStub
	fake.recordInvocation("CleanupOnError", []interface{}{arg1})
	fake.cleanupOnErrorMutex.Unlock()
	if stub != nil {
		fake.CleanupOnErrorStub(arg1)
	}
}

func (fake *WorkflowExecutor) CleanupOnErrorCallCount() int {
	fake.cleanupOnErrorMutex.RLock()
	defer fake.cleanupOnErrorMutex.RUnlock()
	return len(fake.cleanupOnErrorArgsForCall)
}

func (fake *WorkflowExecutor) CleanupOnErrorCalls(stub func(context.Context)) {
	fake.cleanupOnErrorMutex.Lock()
	defer fake.cleanupOnErrorMutex.Unlock()
	fake.CleanupOnErrorStub = stub
}

func (fake *WorkflowExecutor) CleanupOnErrorArgsForCall(i int) context.Context {
	fake.cleanupOnErrorMutex.RLock()
	defer fake.cleanupOnErrorMutex.RUnlock()
	argsForCall := fake.cleanupOnErrorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *WorkflowExecutor) Complete(arg1 context.Context, arg2 context.Context, arg3 *prompt.PromptFile, arg4 string, arg5 string, arg6 string) error {
	fake.completeMutex.Lock()
	ret, specificReturn := fake.completeReturnsOnCall[len(fake.completeArgsForCall)]
	fake.completeArgsForCall = append(fake.completeArgsForCall, struct {
		arg1 context.Context
		arg2 context.Context
		arg3 *prompt.PromptFile
		arg4 string
		arg5 string
		arg6 string
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.CompleteStub
	fakeReturns := fake.completeReturns
	fake.recordInvocation("Complete", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.completeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *WorkflowExecutor) CompleteCallCount() int {
	fake.completeMutex.RLock()
	defer fake.completeMutex.RUnlock()
	return len(fake.completeArgsForCall)
}

func (fake *WorkflowExecutor) CompleteCalls(stub func(context.Context, context.Context, *prompt.PromptFile, string, string, string) error) {
	fake.completeMutex.Lock()
	defer fake.completeMutex.Unlock()
	fake.CompleteStub = stub
}

func (fake *WorkflowExecutor) CompleteArgsForCall(i int) (context.Context, context.Context, *prompt.PromptFile, string, string, string) {
	fake.completeMutex.RLock()
	defer fake.completeMutex.RUnlock()
	argsForCall := fake.completeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *WorkflowExecutor) CompleteReturns(result1 error) {
	fake.completeMutex.Lock()
	defer fake.completeMutex.Unlock()
	fake.CompleteStub = nil
	fake.completeReturns = struct {
		result1 error
	}{result1}
}

func (fake *WorkflowExecutor) CompleteReturnsOnCall(i int, result1 error) {
	fake.completeMutex.Lock()
	defer fake.completeMutex.Unlock()
	fake.CompleteStub = nil
	if fake.completeReturnsOnCall == nil {
		fake.completeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.completeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *WorkflowExecutor) ReconstructState(arg1 context.Context, arg2 prompt.BaseName, arg3 *prompt.PromptFile) (bool, error) {
	fake.reconstructStateMutex.Lock()
	ret, specificReturn := fake.reconstructStateReturnsOnCall[len(fake.reconstructStateArgsForCall)]
	fake.reconstructStateArgsForCall = append(fake.reconstructStateArgsForCall, struct {
		arg1 context.Context
		arg2 prompt.BaseName
		arg3 *prompt.PromptFile
	}{arg1, arg2, arg3})
	stub := fake.ReconstructStateStub
	fakeReturns := fake.reconstructStateReturns
	fake.recordInvocation("ReconstructState", []interface{}{arg1, arg2, arg3})
	fake.reconstructStateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *WorkflowExecutor) ReconstructStateCallCount() int {
	fake.reconstructStateMutex.RLock()
	defer fake.reconstructStateMutex.RUnlock()
	return len(fake.reconstructStateArgsForCall)
}

func (fake *WorkflowExecutor) ReconstructStateCalls(stub func(context.Context, prompt.BaseName, *prompt.PromptFile) (bool, error)) {
	fake.reconstructStateMutex.Lock()
	defer fake.reconstructStateMutex.Unlock()
	fake.ReconstructStateStub = stub
}

func (fake *WorkflowExecutor) ReconstructStateArgsForCall(i int) (context.Context, prompt.BaseName, *prompt.PromptFile) {
	fake.reconstructStateMutex.RLock()
	defer fake.reconstructStateMutex.RUnlock()
	argsForCall := fake.reconstructStateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *WorkflowExecutor) ReconstructStateReturns(result1 bool, result2 error) {
	fake.reconstructStateMutex.Lock()
	defer fake.reconstructStateMutex.Unlock()
	fake.ReconstructStateStub = nil
	fake.reconstructStateReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *WorkflowExecutor) ReconstructStateReturnsOnCall(i int, result1 bool, result2 error) {
	fake.reconstructStateMutex.Lock()
	defer fake.reconstructStateMutex.Unlock()
	fake.ReconstructStateStub = nil
	if fake.reconstructStateReturnsOnCall == nil {
		fake.reconstructStateReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.reconstructStateReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *WorkflowExecutor) Setup(arg1 context.Context, arg2 prompt.BaseName, arg3 *prompt.PromptFile) error {
	fake.setupMutex.Lock()
	ret, specificReturn := fake.setupReturnsOnCall[len(fake.setupArgsForCall)]
	fake.setupArgsForCall = append(fake.setupArgsForCall, struct {
		arg1 context.Context
		arg2 prompt.BaseName
		arg3 *prompt.PromptFile
	}{arg1, arg2, arg3})
	stub := fake.SetupStub
	fakeReturns := fake.setupReturns
	fake.recordInvocation("Setup", []interface{}{arg1, arg2, arg3})
	fake.setupMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *WorkflowExecutor) SetupCallCount() int {
	fake.setupMutex.RLock()
	defer fake.setupMutex.RUnlock()
	return len(fake.setupArgsForCall)
}

func (fake *WorkflowExecutor) SetupCalls(stub func(context.Context, prompt.BaseName, *prompt.PromptFile) error) {
	fake.setupMutex.Lock()
	defer fake.setupMutex.Unlock()
	fake.SetupStub = stub
}

func (fake *WorkflowExecutor) SetupArgsForCall(i int) (context.Context, prompt.BaseName, *prompt.PromptFile) {
	fake.setupMutex.RLock()
	defer fake.setupMutex.RUnlock()
	argsForCall := fake.setupArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *WorkflowExecutor) SetupReturns(result1 error) {
	fake.setupMutex.Lock()
	defer fake.setupMutex.Unlock()
	fake.SetupStub = nil
	fake.setupReturns = struct {
		result1 error
	}{result1}
}

func (fake *WorkflowExecutor) SetupReturnsOnCall(i int, result1 error) {
	fake.setupMutex.Lock()
	defer fake.setupMutex.Unlock()
	fake.SetupStub = nil
	if fake.setupReturnsOnCall == nil {
		fake.setupReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setupReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *WorkflowExecutor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *WorkflowExecutor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ processor.WorkflowExecutor = new(WorkflowExecutor)
