#!/usr/bin/env bash
#
# Scans the six hot-path packages for bare package-level slog.Info/Warn/Error calls.
# These should be replaced with log.From(ctx).Info/Warn/Error (context-bound logger).
#
# Usage:
#   hotpath-logcheck.sh warn    — print offenders, always exit 0 (current mode)
#   hotpath-logcheck.sh strict  — print offenders, exit 1 if any found
#
# The package allow-list is defined in PACKAGES below and is the canonical list of
# hot-path packages subject to context-threaded logging (see docs/rules/logging-conventions.md).
#
# Run from repo root (Makefile target `hotpath-logcheck`).

MODE="${1:-warn}"

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

PACKAGES="pkg/processor pkg/executor pkg/promptresumer pkg/committingrecoverer pkg/cancellationwatcher pkg/queuescanner"

OFFENDERS=""

for pkg in $PACKAGES; do
    if [ ! -d "$pkg" ]; then
        continue
    fi
    for f in "$pkg"/*.go; do
        [ -f "$f" ] || continue

        # Skip test files
        case "$f" in
            *_test.go) continue ;;
        esac

        # Skip counterfeiter-generated files
        if head -3 "$f" | grep -q "Code generated by counterfeiter"; then
            continue
        fi

        # Skip the documented exclusion: pkg/executor/launch.go
        case "$f" in
            pkg/executor/launch.go) continue ;;
        esac

        # Search for bare slog.Info(, slog.Warn(, slog.Error( calls
        # Do NOT match slog.InfoContext(, slog.WarnContext(, slog.ErrorContext(
        # Use POSIX grep: match slog.(Info|Warn|Error)( but not slog.(Info|Warn|Error)Context(
        matches=$(grep -nE 'slog\.(Info|Warn|Error)\(' "$f" | grep -v 'slog\.\(Info\|Warn\|Error\)Context(')
        if [ -n "$matches" ]; then
            while IFS= read -r line; do
                OFFENDERS="$OFFENDERS
$f:$line"
            done <<EOF
$matches
EOF
        fi
    done
done

# Strip leading newline
OFFENDERS=$(printf '%s' "$OFFENDERS" | sed '/^$/d')

if [ -n "$OFFENDERS" ]; then
    printf 'hotpath-logcheck: bare slog calls found (replace with log.From(ctx).Info/Warn/Error):\n' >&2
    printf '%s\n' "$OFFENDERS" >&2
    if [ "$MODE" = "strict" ]; then
        exit 1
    fi
fi

exit 0
