#!/usr/bin/env bash
#
# Scans pkg/ recursively for raw string-literal references to the claude
# env keys ("ANTHROPIC_MODEL", "YOLO_PROMPT", "YOLO_PROMPT_FILE",
# "YOLO_OUTPUT"). Production code must build envOverlay maps via
# pkg/claudeargv (canonical owner of these strings).
#
# Before pkg/claudeargv existed, the literals were duplicated across
# pkg/executor (prompt runs) and pkg/cmd/healthcheck (claude probe);
# they drifted (e.g. probe missing ANTHROPIC_MODEL) and silently broke
# production paths. Consolidated 2026-06-27 as the final Phase-2 task
# of [[Harden Dark Factory Architecture]] following the architecture
# re-audit.
#
# Usage:
#   hotpath-claudeargv-check.sh warn    — print offenders, always exit 0
#   hotpath-claudeargv-check.sh strict  — print offenders, exit 1 if any found

MODE="${1:-warn}"

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

OFFENDERS=""

while IFS= read -r f; do
    case "$f" in
        *_test.go) continue ;;
    esac

    if head -3 "$f" | grep -q "Code generated by counterfeiter"; then
        continue
    fi

    # pkg/claudeargv OWNS these literals.
    case "$f" in
        pkg/claudeargv/*) continue ;;
    esac

    # Skip pure comment lines so architectural docs can quote the keys
    # in // comments (e.g. "ANTHROPIC_MODEL is set by the executor").
    matches=$(
        grep -nE '"(ANTHROPIC_MODEL|YOLO_PROMPT|YOLO_PROMPT_FILE|YOLO_OUTPUT)"' "$f" \
        | grep -vE '^[0-9]+:[[:space:]]*//'
    )
    if [ -n "$matches" ]; then
        while IFS= read -r line; do
            OFFENDERS="$OFFENDERS
$f:$line"
        done <<EOF
$matches
EOF
    fi
done < <(find pkg -type f -name '*.go')

OFFENDERS=$(printf '%s' "$OFFENDERS" | sed '/^$/d')

if [ -n "$OFFENDERS" ]; then
    printf 'hotpath-claudeargv-check: raw claude env-key literals found (use pkg/claudeargv constants):\n' >&2
    printf '%s\n' "$OFFENDERS" >&2
    if [ "$MODE" = "strict" ]; then
        exit 1
    fi
fi

exit 0
