#!/usr/bin/env bash
#
# Scans the backend-neutral packages for container-flavored tokens that must not
# re-leak into the abstraction layer (spec 102: executor-backend-neutral-naming).
#
# Container vocabulary is allowed ONLY inside pkg/executor, pkg/launchpolicy, and
# pkg/containerlock (the docker-CLI implementation). Every other package in scope
# must use the neutral names: executionID / ExecutionChecker / ExecutionStopper /
# executionslot.
#
# Usage:
#   hotpath-execution-naming-check.sh warn    — print offenders, always exit 0
#   hotpath-execution-naming-check.sh strict  — print offenders, exit 1 if any found
#   hotpath-execution-naming-check.sh selftest — verify the leak fixture is detectable
#
# Run from repo root (Makefile target `hotpath-execution-naming-check`).

MODE="${1:-warn}"

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT" || exit 1

# ---------------------------------------------------------------------------
# selftest: verify the leak fixture triggers detection
# ---------------------------------------------------------------------------
if [ "$MODE" = "selftest" ]; then
    FIXTURE="scripts/testdata/hotpath-execution-naming/leak.go.txt"
    if [ ! -f "$FIXTURE" ]; then
        printf 'selftest: fixture not found: %s\n' "$FIXTURE" >&2
        exit 1
    fi
    matches=$(grep -nE '\bcontainerName\b|\bContainerChecker\b|\bContainerStopper\b|\bcontainerslot\b' "$FIXTURE")
    if [ -z "$matches" ]; then
        printf 'selftest FAILED: fixture does not contain a detectable forbidden token\n' >&2
        exit 1
    fi
    printf 'selftest OK: fixture triggers detection:\n'
    printf '%s\n' "$matches"
    exit 0
fi

# ---------------------------------------------------------------------------
# Neutral-layer packages to scan (docker-CLI implementation dirs excluded)
# ---------------------------------------------------------------------------
NEUTRAL_DIRS="pkg/factory pkg/runner pkg/promptresumer pkg/cancellationwatcher pkg/queuescanner pkg/healthcheckgate pkg/generator pkg/processor pkg/executionslot"

OFFENDERS=""

for dir in $NEUTRAL_DIRS; do
    if [ ! -d "$dir" ]; then
        continue
    fi
    while IFS= read -r f; do
        # Skip test files
        case "$f" in
            *_test.go) continue ;;
        esac

        # Skip counterfeiter-generated files
        if head -3 "$f" | grep -q "Code generated by counterfeiter"; then
            continue
        fi

        # Search for forbidden container-flavored tokens
        matches=$(grep -nE '\bcontainerName\b|\bContainerChecker\b|\bContainerStopper\b|\bcontainerslot\b' "$f")
        if [ -n "$matches" ]; then
            while IFS= read -r line; do
                OFFENDERS="$OFFENDERS
$f:$line"
            done <<EOF
$matches
EOF
        fi
    done < <(find "$dir" -type f -name '*.go')
done

# Strip leading blank line
OFFENDERS=$(printf '%s' "$OFFENDERS" | sed '/^$/d')

if [ -n "$OFFENDERS" ]; then
    printf 'hotpath-execution-naming-check: container vocabulary leaked into neutral layer (use executionID / ExecutionChecker / ExecutionStopper / executionslot; container words belong in pkg/executor, pkg/launchpolicy, pkg/containerlock):\n' >&2
    printf '%s\n' "$OFFENDERS" >&2
    if [ "$MODE" = "strict" ]; then
        exit 1
    fi
fi

exit 0
