#!/usr/bin/env bash
#
# Scans the six migrated hot-path targets for inline prompt.PromptStatus
# type-token usage (prompt.PromptStatus(...) casts and direct type references).
# These must be routed through pkg/promptstate (the single owner of
# prompt-state interpretation) rather than read inline.
#
# Pattern used: prompt\.PromptStatus (exact type token).
# Named constants (prompt.ApprovedPromptStatus, etc.) used for status-setting
# business logic (e.g. autoSetQueuedStatus in pkg/queuescanner) are NOT
# matched — they are not tuple-reading and were not in the migration scope.
# See ## Improvements in prompt 4 completion report for the reconciliation.
#
# Usage:
#   hotpath-statemachine-check.sh warn    — print offenders, always exit 0
#   hotpath-statemachine-check.sh strict  — print offenders, exit 1 if any found
#
# SCOPED GATE — six migrated targets only (mirrors hotpath-logcheck design):
#
#   In scope (files/packages this spec migrated):
#     pkg/runner/lifecycle.go
#     pkg/promptresumer/resumer.go
#     pkg/committingrecoverer/recoverer.go
#     pkg/queuescanner/scanner.go
#     pkg/cancellationwatcher/watcher.go
#     pkg/processor/*.go (non-test)
#
#   Out of scope — NOT scanned (legitimate status readers by design):
#     pkg/promptstate/*.go           — the OWNER; holds InterpretRawTuple /
#                                      IsPreExecutionStatus / StatusFromRaw
#     pkg/prompt/prompt.go           — the storage type definition
#     pkg/cmd/cancel.go              — interactive CLI command
#     pkg/cmd/prompt_complete.go     — interactive CLI command
#     pkg/cmd/reject.go              — interactive CLI command
#     pkg/cmd/spec_reject.go         — interactive CLI command
#     pkg/cmd/unapprove.go           — interactive CLI command
#     pkg/doctor/fix_orphan_in_progress.go   — repair tool
#     pkg/doctor/prompted_not_swept.go       — repair tool
#     pkg/doctor/status_dir_mismatch.go      — repair tool
#     pkg/runner/health_check.go     — healthcheck reads status by design
#
#   The AC-4 repo-wide grep in spec 101 is intentionally NOT enforced here
#   because it would force migrating out-of-scope CLI/doctor packages that the
#   spec did not list. The gate is scoped to the six targets (see spec
#   101-extract-unified-prompt-state-machine.md, AC-4 reconciliation).
#
# Run from repo root (Makefile target `hotpath-statemachine-check`).

MODE="${1:-strict}"

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

# Individual files to scan
FILES="pkg/runner/lifecycle.go pkg/promptresumer/resumer.go pkg/committingrecoverer/recoverer.go pkg/queuescanner/scanner.go pkg/cancellationwatcher/watcher.go"

# Package directories to scan (all non-test *.go files in each)
PACKAGES="pkg/processor"

OFFENDERS=""

# Scan package directories
for pkg in $PACKAGES; do
    if [ ! -d "$pkg" ]; then
        continue
    fi
    for f in "$pkg"/*.go; do
        [ -f "$f" ] || continue

        # Skip test files
        case "$f" in
            *_test.go) continue ;;
        esac

        # Skip counterfeiter-generated files
        if head -3 "$f" | grep -q "Code generated by counterfeiter"; then
            continue
        fi

        matches=$(grep -nE 'prompt\.PromptStatus' "$f")
        if [ -n "$matches" ]; then
            while IFS= read -r line; do
                OFFENDERS="$OFFENDERS
$f:$line"
            done <<EOF
$matches
EOF
        fi
    done
done

# Scan individual files
for f in $FILES; do
    [ -f "$f" ] || continue

    # Skip test files
    case "$f" in
        *_test.go) continue ;;
    esac

    # Skip counterfeiter-generated files
    if head -3 "$f" | grep -q "Code generated by counterfeiter"; then
        continue
    fi

    matches=$(grep -nE 'prompt\.PromptStatus' "$f")
    if [ -n "$matches" ]; then
        while IFS= read -r line; do
            OFFENDERS="$OFFENDERS
$f:$line"
        done <<EOF
$matches
EOF
    fi
done

# Strip leading newline
OFFENDERS=$(printf '%s' "$OFFENDERS" | sed '/^$/d')

if [ -n "$OFFENDERS" ]; then
    printf 'hotpath-statemachine-check: inline prompt-status comparison found (route via pkg/promptstate):\n' >&2
    printf '%s\n' "$OFFENDERS" >&2
    if [ "$MODE" = "strict" ]; then
        exit 1
    fi
fi

exit 0
