#!/usr/bin/env bash
#
# Scans pkg/ recursively for raw exec.Command / exec.CommandContext calls.
# These should be routed through pkg/subproc.Runner instead of being called directly.
# See spec 100 (centralize-subprocess-runner) for the full migration plan.
#
# Usage:
#   hotpath-execcheck.sh warn    — print offenders, always exit 0 (current mode)
#   hotpath-execcheck.sh strict  — print offenders, exit 1 if any found
#
# The docker allow-list below covers pkg/executor files that own the SIGINT/SIGKILL
# escalation protocol for Docker containers and are out of scope for this migration
# (spec 100 Non-goal). Extending the allow-list requires a separate spec.
#
# Run from repo root (Makefile target `hotpath-execcheck`).

MODE="${1:-warn}"

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

OFFENDERS=""

while IFS= read -r f; do
    # Skip test files
    case "$f" in
        *_test.go) continue ;;
    esac

    # Skip counterfeiter-generated files
    if head -3 "$f" | grep -q "Code generated by counterfeiter"; then
        continue
    fi

    # Skip the approved spawn primitive
    case "$f" in
        pkg/subproc/*) continue ;;
    esac

    # Docker-CLI spawn sites — own SIGINT-then-SIGKILL escalation protocol, out of scope (spec 100 Non-goal).
    case "$f" in
        pkg/executor/checker.go) continue ;;
        pkg/executor/stopper.go) continue ;;
        pkg/executor/executor.go) continue ;;
        pkg/executor/launch.go) continue ;;
        pkg/executor/local_subprocess.go) continue ;;
    esac

    # Search for raw exec spawns; skip comment-only lines (e.g. architecture docs that
    # reference exec.Command as examples within // comments).
    matches=$(grep -nE 'exec\.Command(Context)?\(' "$f" | grep -vE '^[0-9]+:[[:space:]]*//')
    if [ -n "$matches" ]; then
        while IFS= read -r line; do
            OFFENDERS="$OFFENDERS
$f:$line"
        done <<EOF
$matches
EOF
    fi
done < <(find pkg -type f -name '*.go')

# Strip leading newline
OFFENDERS=$(printf '%s' "$OFFENDERS" | sed '/^$/d')

if [ -n "$OFFENDERS" ]; then
    printf 'hotpath-execcheck: raw exec.Command(Context) found (route through pkg/subproc.Runner):\n' >&2
    printf '%s\n' "$OFFENDERS" >&2
    if [ "$MODE" = "strict" ]; then
        exit 1
    fi
fi

exit 0
