#!/usr/bin/env bash
#
# Scans pkg/ recursively for the inline hideGit resolution formula:
#   cfg.Workflow == config.WorkflowWorktree || cfg.HideGit
#
# Production code must use `cfg.EffectiveHideGit()` (or
# `p.EffectiveHideGit()` for ProcessorConfig) instead. The formula was
# promoted to a method on Config (and ProcessorConfig) on 2026-06-27 as
# Phase-2 cleanup of [[Harden Dark Factory Architecture]] — previously
# `pkg/factory.resolveHideGit` existed and was applied at 1 of 3 sites;
# the other 2 inlined the formula and silently drifted. The same
# divergence pattern caused the 2026-06-26 silent minimax healthcheck
# regression at a different call site.
#
# Usage:
#   hotpath-hidegit-check.sh warn    — print offenders, always exit 0
#   hotpath-hidegit-check.sh strict  — print offenders, exit 1 if any found
#
# Allow-list:
#   pkg/config/config.go             — defines `Config.EffectiveHideGit`
#   pkg/factory/factory.go           — defines `ProcessorConfig.EffectiveHideGit`
#   pkg/config/loader.go             — loader assembling cfg from YAML (raw field reads OK)

MODE="${1:-warn}"

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

OFFENDERS=""

while IFS= read -r f; do
    case "$f" in
        *_test.go) continue ;;
    esac

    if head -3 "$f" | grep -q "Code generated by counterfeiter"; then
        continue
    fi

    case "$f" in
        pkg/config/config.go) continue ;;
        pkg/factory/factory.go) continue ;;
        pkg/config/loader.go) continue ;;
    esac

    # The inline formula spans patterns like:
    #   cfg.Workflow == config.WorkflowWorktree || cfg.HideGit
    #   c.Workflow == WorkflowWorktree || c.HideGit
    # Skip pure comment lines (//) so architectural docs can quote it.
    matches=$(
        grep -nE 'Workflow[[:space:]]*==[[:space:]]*(config\.)?WorkflowWorktree[[:space:]]*\|\|[[:space:]]*[a-zA-Z_][a-zA-Z0-9_]*\.HideGit' "$f" \
        | grep -vE '^[0-9]+:[[:space:]]*//'
    )
    if [ -n "$matches" ]; then
        while IFS= read -r line; do
            OFFENDERS="$OFFENDERS
$f:$line"
        done <<EOF
$matches
EOF
    fi
done < <(find pkg -type f -name '*.go')

OFFENDERS=$(printf '%s' "$OFFENDERS" | sed '/^$/d')

if [ -n "$OFFENDERS" ]; then
    printf 'hotpath-hidegit-check: inline hideGit formula found (use cfg.EffectiveHideGit() / p.EffectiveHideGit()):\n' >&2
    printf '%s\n' "$OFFENDERS" >&2
    if [ "$MODE" = "strict" ]; then
        exit 1
    fi
fi

exit 0
